.TH "/home/ashiroji/Arduino/libraries/CoolBoard Directory Reference" 3 "Tue Jun 27 2017" "COOLAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCoolBoard\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCoolBoard\&.h\fP"
.br
.ti -1c
.RI "file \fBCoolBoardLed\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCoolBoardLed\&.h\fP"
.br
.ti -1c
.RI "file \fBCoolBoardSensors\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCoolBoardSensors\&.h\fP"
.br
.ti -1c
.RI "file \fBCoolFileSystem\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCoolFileSystem\&.h\fP"
.br
.ti -1c
.RI "file \fBCoolMQTT\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCoolMQTT\&.h\fP"
.br
.ti -1c
.RI "file \fBCoolTime\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCoolTime\&.h\fP"
.br
.ti -1c
.RI "file \fBExternalSensor\&.h\fP"
.br
.ti -1c
.RI "file \fBExternalSensors\&.cpp\fP"
.br
.ti -1c
.RI "file \fBExternalSensors\&.h\fP"
.br
.ti -1c
.RI "file \fBirene3000\&.cpp\fP"
.br
.ti -1c
.RI "file \fBIrene3000\&.h\fP"
.br
.ti -1c
.RI "file \fBJetpack\&.cpp\fP"
.br
.ti -1c
.RI "file \fBJetpack\&.h\fP"
.br
.in -1c
