.TH "BaseExternalSensor" 3 "Wed Jul 5 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseExternalSensor \- This class is a generic external Sensor it is a way to access real external sensor methods through run Time polymorphism\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExternalSensor\&.h>\fP
.PP
Inherited by \fBExternalSensor< T >\fP, \fBExternalSensor< DallasTemperature >\fP, and \fBExternalSensor< NDIR_I2C >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseExternalSensor\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual float \fBread\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is a generic external Sensor it is a way to access real external sensor methods through run Time polymorphism\&. 
.PP
Definition at line 22 of file ExternalSensor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BaseExternalSensor::BaseExternalSensor ()\fC [inline]\fP"
\fBBaseExternalSensor()\fP: Base class generic Constructor 
.PP
Definition at line 30 of file ExternalSensor\&.h\&.
.PP
.nf
31     {
32         Serial\&.println("BaseExternalSensor Constructor");
33         Serial\&.println();
34     }
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual uint8_t BaseExternalSensor::begin ()\fC [inline]\fP, \fC [virtual]\fP"
\fBbegin()\fP: Base class virtual generic begin method
.PP
\fBReturns:\fP
.RS 4
generic value as it's not supposed to be used 
.RE
.PP

.PP
Reimplemented in \fBExternalSensor< DallasTemperature >\fP, \fBExternalSensor< NDIR_I2C >\fP, and \fBExternalSensor< T >\fP\&.
.PP
Definition at line 43 of file ExternalSensor\&.h\&.
.PP
Referenced by ExternalSensors::begin()\&.
.PP
.nf
44     {
45         Serial\&.println("BaseExternalSensor\&.begin()");
46         Serial\&.println();
47 
48         return(-2);
49     }
.fi
.SS "virtual float BaseExternalSensor::read ()\fC [inline]\fP, \fC [virtual]\fP"
\fBread()\fP: Base class virtual generic read method
.PP
\fBReturns:\fP
.RS 4
generic value as it is not supposed to be used 
.RE
.PP

.PP
Reimplemented in \fBExternalSensor< DallasTemperature >\fP, \fBExternalSensor< NDIR_I2C >\fP, and \fBExternalSensor< T >\fP\&.
.PP
Definition at line 60 of file ExternalSensor\&.h\&.
.PP
.nf
61     {
62         Serial\&.println("BaseExternalSensor\&.read()");
63         Serial\&.println();        
64         
65         return(-2);
66     }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
