.TH "BaseExternalSensor" 3 "Tue Jun 27 2017" "COOLAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseExternalSensor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExternalSensor\&.h>\fP
.PP
Inherited by \fBExternalSensor< T >\fP, \fBExternalSensor< DallasTemperature >\fP, and \fBExternalSensor< NDIR_I2C >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseExternalSensor\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual int \fBread\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBExternalSensor\&.h\fP This class handles the actual usage and creation of the external sensors \fBBaseExternalSensor\fP: This class is a generic external Sensor it is a way to access real external sensor methods through run Time polymorphism 
.PP
Definition at line 21 of file ExternalSensor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BaseExternalSensor::BaseExternalSensor ()\fC [inline]\fP"
\fBBaseExternalSensor()\fP: Base class generic Constructor 
.PP
Definition at line 29 of file ExternalSensor\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual uint8_t BaseExternalSensor::begin ()\fC [inline]\fP, \fC [virtual]\fP"
\fBbegin()\fP: Base class virtual generic begin method 
.PP
Reimplemented in \fBExternalSensor< DallasTemperature >\fP, \fBExternalSensor< NDIR_I2C >\fP, and \fBExternalSensor< T >\fP\&.
.PP
Definition at line 38 of file ExternalSensor\&.h\&.
.SS "virtual int BaseExternalSensor::read ()\fC [inline]\fP, \fC [virtual]\fP"
\fBread()\fP: Base class virtual generic read method 
.PP
Reimplemented in \fBExternalSensor< DallasTemperature >\fP, \fBExternalSensor< NDIR_I2C >\fP, and \fBExternalSensor< T >\fP\&.
.PP
Definition at line 49 of file ExternalSensor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COOLAPI from the source code\&.
