.TH "/home/ashiroji/Arduino/libraries/CoolBoard/CoolBoard.h" 3 "Tue Jun 27 2017" "COOLAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/CoolBoard.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CoolFileSystem\&.h'\fP
.br
\fC#include 'CoolBoardSensors\&.h'\fP
.br
\fC#include 'CoolBoardLed\&.h'\fP
.br
\fC#include 'CoolTime\&.h'\fP
.br
\fC#include 'CoolMQTT\&.h'\fP
.br
\fC#include 'Jetpack\&.h'\fP
.br
\fC#include 'Irene3000\&.h'\fP
.br
\fC#include 'ExternalSensors\&.h'\fP
.br
\fC#include <ESP8266WiFi\&.h>\fP
.br
\fC#include <DNSServer\&.h>\fP
.br
\fC#include <ESP8266WebServer\&.h>\fP
.br
\fC#include <WiFiManager\&.h>\fP
.br
\fC#include 'Arduino\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCoolBoard\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for COOLAPI from the source code\&.
