.TH "CoolTime.cpp" 3 "Mon Jul 3 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoolTime.cpp \- \fBCoolTime\fP Source File\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'FS\&.h'\fP
.br
\fC#include 'Arduino\&.h'\fP
.br
\fC#include 'CoolTime\&.h'\fP
.br
\fC#include 'ArduinoJson\&.h'\fP
.br
\fC#include 'TimeLib\&.h'\fP
.br

.SH "Detailed Description"
.PP 
\fBCoolTime\fP Source File\&. 


.PP
\fBAuthor:\fP
.RS 4
Mehdi Zemzem 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
27/06/2017 
.RE
.PP

.PP
Definition in file \fBCoolTime\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
