.TH "CoolTime" 3 "Wed Jul 12 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoolTime \- This class manages the DS1337 RTC \&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CoolTime\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBbegin\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "bool \fBconfig\fP ()"
.br
.ti -1c
.RI "void \fBconfig\fP (IPAddress \fBtimeServer\fP, unsigned int \fBlocalPort\fP)"
.br
.ti -1c
.RI "void \fBprintConf\fP ()"
.br
.ti -1c
.RI "void \fBsetDateTime\fP (int year, int month, int day, int hour, int minutes, int seconds)"
.br
.ti -1c
.RI "tmElements_t \fBgetTimeDate\fP ()"
.br
.ti -1c
.RI "String \fBgetESDate\fP ()"
.br
.ti -1c
.RI "unsigned long \fBgetLastSyncTime\fP ()"
.br
.ti -1c
.RI "bool \fBisTimeSync\fP (unsigned long seconds=604800)"
.br
.ti -1c
.RI "time_t \fBgetNtpTime\fP ()"
.br
.ti -1c
.RI "void \fBsendNTPpacket\fP (IPAddress &address)"
.br
.ti -1c
.RI "String \fBformatDigits\fP (int digits)"
.br
.ti -1c
.RI "bool \fBsaveTimeSync\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBtimeSync\fP =0"
.br
.ti -1c
.RI "IPAddress \fBtimeServer\fP"
.br
.ti -1c
.RI "WiFiUDP \fBUdp\fP"
.br
.ti -1c
.RI "unsigned int \fBlocalPort\fP =0"
.br
.ti -1c
.RI "byte \fBpacketBuffer\fP [\fBNTP_PACKET_SIZE\fP]"
.br
.ti -1c
.RI "tmElements_t \fBtmSet\fP"
.br
.ti -1c
.RI "DS1337RTC \fBrtc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class manages the DS1337 RTC \&. 
.PP
Definition at line 31 of file CoolTime\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void CoolTime::begin ()"
\fBCoolTime::begin()\fP: This method is provided to init the udp connection 
.PP
Definition at line 41 of file CoolTime\&.cpp\&.
.PP
References localPort, Udp, and update()\&.
.PP
Referenced by CoolBoard::begin()\&.
.PP
.nf
42 {
43 
44 #if DEBUG == 1 
45 
46     Serial\&.println( F("Entering CoolTime\&.begin()") );
47     Serial\&.println();
48 
49 #endif 
50 
51 
52     Udp\&.begin(localPort);
53     
54     this->update();
55     
56 }
.fi
.SS "bool CoolTime::config ()"
\fBCoolTime::config()\fP: This method is provided to configure the \fBCoolTime\fP object through a configuration file\&.
.PP
\fBReturns:\fP
.RS 4
true if successful,false otherwise 
.RE
.PP

.PP
Definition at line 424 of file CoolTime\&.cpp\&.
.PP
References localPort, timeServer, and timeSync\&.
.PP
Referenced by CoolBoard::begin(), and CoolBoard::update()\&.
.PP
.nf
425 {
426 
427 #if DEBUG == 1 
428 
429     Serial\&.println( F("Enter CoolTime\&.config()") );
430     Serial\&.println();
431 
432 #endif 
433 
434     File rtcConfig = SPIFFS\&.open("/rtcConfig\&.json", "r");
435 
436     if (!rtcConfig) 
437     {
438     
439     #if DEBUG == 1 
440 
441         Serial\&.println( F("failed to read /rtcConfig\&.json") );
442         Serial\&.println();
443     
444     #endif
445 
446         return(false);
447     }
448     else
449     {
450         size_t size = rtcConfig\&.size();
451         // Allocate a buffer to store contents of the file\&.
452         std::unique_ptr<char[]> buf(new char[size]);
453 
454         rtcConfig\&.readBytes(buf\&.get(), size);
455         DynamicJsonBuffer jsonBuffer;
456         JsonObject& json = jsonBuffer\&.parseObject(buf\&.get());
457         if (!json\&.success()) 
458         {
459         
460         #if DEBUG == 1 
461 
462             Serial\&.println( F("failed to parse json") );
463             Serial\&.println();
464         
465         #endif 
466 
467             return(false);
468         } 
469         else
470         {  
471         
472         #if DEBUG == 1 
473 
474             Serial\&.println( F("configuration json is :") );
475             json\&.printTo(Serial);
476             Serial\&.println();
477 
478         #endif
479 
480             String ip;
481             
482             if(json["timeServer"]\&.success() )
483             {           
484                  ip=json["timeServer"]\&.as<String>();
485                 this->timeServer\&.fromString(ip);
486                 
487             }
488             else
489             {
490                 this->timeServer=this->timeServer;
491             }
492             json["timeServer"]=ip;
493             
494             if(json["localPort"]\&.success() )
495             {                       
496                 this->localPort=json["localPort"];
497             }
498             else
499             {
500                 this->localPort=this->localPort;
501             }
502             json["localPort"]=this->localPort;
503 
504 
505             if( json["timeSync"]\&.success() )
506             {
507 
508                 this->timeSync=json["timeSync"];
509             }
510             else
511             {
512                 this->timeSync=this->timeSync;
513             }
514             json["timeSync"]=this->timeSync;
515 
516             rtcConfig\&.close();
517             rtcConfig= SPIFFS\&.open("/rtcConfig\&.json", "w");
518             
519             if(!rtcConfig)
520             {
521             
522             #if DEBUG == 1
523 
524                 Serial\&.println( F("failed to write to /rtcConfig\&.json") );
525                 Serial\&.println();
526             
527             #endif
528 
529                 return(false);
530             }
531             
532             json\&.printTo(rtcConfig);
533             rtcConfig\&.close();
534 
535         #if DEBUG == 1 
536 
537             Serial\&.println( F("configuration is :") );
538             json\&.printTo(Serial);
539             Serial\&.println();
540         
541         #endif
542         
543             return(true); 
544         }
545     }   
546 
547 
548 
549 }
.fi
.SS "void CoolTime::config (IPAddress timeServer, unsigned int localPort)"
CoolTime::config(Time server IP , udp Port): This method is provided to do manual configuration\&. 
.PP
Definition at line 401 of file CoolTime\&.cpp\&.
.PP
References localPort, and timeServer\&.
.PP
.nf
402 {
403 
404 #if DEBUG == 1 
405 
406     Serial\&.println( F("Enter CoomTime\&.config() , no SPIFFS variant ") );
407     Serial\&.println();
408 
409 #endif 
410 
411     this->timeServer=timeServer;
412     this->localPort=localPort;
413     
414 } 
.fi
.SS "String CoolTime::formatDigits (int digits)"
CoolTime::printDigits(digit)
.PP
utility method for digital clock display adds leading 0
.PP
\fBReturns:\fP
.RS 4
formatted string of the input digit 
.RE
.PP

.PP
Definition at line 691 of file CoolTime\&.cpp\&.
.PP
Referenced by getESDate(), getTimeDate(), and setDateTime()\&.
.PP
.nf
692 {
693 
694 #if DEBUG == 1 
695 
696     Serial\&.println( F("Entering CoolTime\&.formatDigits()") );
697     Serial\&.println();
698 
699 #endif 
700 
701     if(digits < 10)
702     {
703     
704     #if DEBUG == 1
705 
706         Serial\&.println( F("output digit : ") );
707         Serial\&.println( String("0") + String(digits) );
708 
709     #endif
710 
711         return( String("0") + String(digits) );
712     }
713     
714 #if DEBUG == 1 
715 
716     Serial\&.println( F("output digit : ") );
717     Serial\&.println(digits);
718 
719 #endif
720 
721     return( String(digits) );
722 }
.fi
.SS "String CoolTime::getESDate ()"
CoolTime::getESD(): This method is provided to return an Elastic Search compatible date Format
.PP
\fBReturns:\fP
.RS 4
date String in Elastic Search format 
.RE
.PP

.PP
Definition at line 193 of file CoolTime\&.cpp\&.
.PP
References formatDigits(), and getTimeDate()\&.
.PP
Referenced by setDateTime(), and CoolBoard::userData()\&.
.PP
.nf
194 {
195 
196 #if DEBUG == 1 
197 
198     Serial\&.println( F("Entering CoolTime\&.getESDate()") );
199     Serial\&.println();
200 
201 #endif 
202 
203     tmElements_t tm=this->getTimeDate();
204 
205     //"20yy-mm-ddT00:00:00Z"
206     String elasticSearchString =String(tm\&.Year+1970)+"-"+this->formatDigits(tm\&.Month)+"-";
207 
208     elasticSearchString +=this->formatDigits(tm\&.Day)+"T"+this->formatDigits(tm\&.Hour)+":";
209     
210     elasticSearchString +=this->formatDigits(tm\&.Minute)+":"+this->formatDigits(tm\&.Second)+"Z";
211 
212 #if DEBUG == 1 
213 
214     Serial\&.print( F("elastic Search date : ") );
215     Serial\&.println(elasticSearchString);
216     Serial\&.println();
217 
218 #endif
219 
220     return (elasticSearchString);
221 }
.fi
.SS "unsigned long CoolTime::getLastSyncTime ()"
\fBCoolTime::getLastSyncTime()\fP: This method is provided to get the last time we syncronised the time
.PP
\fBReturns:\fP
.RS 4
unsigned long representation of last syncronisation time in seconds 
.RE
.PP

.PP
Definition at line 231 of file CoolTime\&.cpp\&.
.PP
References timeSync\&.
.PP
Referenced by isTimeSync()\&.
.PP
.nf
232 {
233 
234 #if DEBUG == 1 
235 
236     Serial\&.println( F("Entering CoolTime\&.getLastSyncTime()") );
237     Serial\&.println();
238     
239     Serial\&.print( F("last sync time : ") );
240     Serial\&.println(this->timeSync);
241 
242 #endif 
243 
244     return(this->timeSync);
245 }
.fi
.SS "time_t CoolTime::getNtpTime ()"
CoolTime::getNtopTime(): This method is provided to get the Time through an NTP request to a Time Server
.PP
\fBReturns:\fP
.RS 4
a time_t (unsigned long ) timestamp in seconds 
.RE
.PP

.PP
Definition at line 299 of file CoolTime\&.cpp\&.
.PP
References NTP_PACKET_SIZE, packetBuffer, sendNTPpacket(), timeServer, and Udp\&.
.PP
Referenced by update()\&.
.PP
.nf
300 {
301 
302 #if DEBUG == 1 
303 
304     Serial\&.println( F("Entering CoolTime\&.getNtpTime()") );
305     Serial\&.println();
306 
307 #endif 
308 
309     while (Udp\&.parsePacket() > 0) ; // discard any previously received packets
310 
311 #if DEBUG == 1 
312     
313     Serial\&.println( F("Transmit NTP Request") );
314 
315 #endif 
316 
317     sendNTPpacket(timeServer);
318 
319     uint32_t beginWait = millis();
320 
321     while (millis() - beginWait < 1500) 
322     {
323         int size = Udp\&.parsePacket();
324         if (size >= NTP_PACKET_SIZE) 
325         {
326         
327         #if DEBUG == 1
328 
329             Serial\&.println( F("Receive NTP Response") );
330         
331         #endif
332 
333             Udp\&.read(packetBuffer, NTP_PACKET_SIZE);  // read packet into the buffer
334             unsigned long secsSince1900;
335             // convert four bytes starting at location 40 to a long integer
336             secsSince1900 =  (unsigned long)packetBuffer[40] << 24;
337             secsSince1900 |= (unsigned long)packetBuffer[41] << 16;
338             secsSince1900 |= (unsigned long)packetBuffer[42] << 8;
339             secsSince1900 |= (unsigned long)packetBuffer[43];
340         
341         #if DEBUG == 1 
342     
343             Serial\&.print( F("received unix time : ") );
344             Serial\&.println(secsSince1900 - 2208988800UL);
345             Serial\&.println();
346 
347         #endif 
348 
349             return secsSince1900 - 2208988800UL ;
350         }
351     }
352     
353 #if DEBUG == 1
354 
355     Serial\&.println( F("No NTP Response :-(") );
356 
357 #endif 
358 
359     return 0; // return 0 if unable to get the time
360 }
.fi
.SS "tmElements_t CoolTime::getTimeDate ()"
\fBCoolTime::getTimeDate()\fP: This method is provided to get the RTC Time
.PP
\fBReturns:\fP
.RS 4
a tmElements_t structre that has the time in it 
.RE
.PP

.PP
Definition at line 150 of file CoolTime\&.cpp\&.
.PP
References formatDigits(), and rtc\&.
.PP
Referenced by getESDate()\&.
.PP
.nf
151 {
152 
153 #if DEBUG == 1 
154     
155     Serial\&.println( F("Entering CoolTime\&.getTimeDate()") );
156     Serial\&.println();
157 
158 #endif
159 
160     tmElements_t tm;
161     time_t timeDate = this->rtc\&.get(CLOCK_ADDRESS);
162     breakTime(timeDate,tm);
163 
164 #if DEBUG == 1
165     
166     Serial\&.print( F("time is : ") );
167     Serial\&.print(tm\&.Year+ 1970 );
168     Serial\&.print( F("-") );
169     Serial\&.print( this->formatDigits( tm\&.Month ) );
170     Serial\&.print( F("-") );
171     Serial\&.print( this->formatDigits( tm\&.Day ) );
172     Serial\&.print( F("T") );
173     Serial\&.print( this->formatDigits( tm\&.Hour ) );
174     Serial\&.print( F(":") );
175     Serial\&.print( this->formatDigits( tm\&.Minute ) );
176     Serial\&.print( F(":") );
177     Serial\&.print( this->formatDigits( tm\&.Second ) );
178     Serial\&.print( F("Z") );
179 
180 #endif
181     
182     return(tm);
183 }
.fi
.SS "bool CoolTime::isTimeSync (unsigned long seconds = \fC604800\fP)"
CoolTime::isTimeSync( time in seconds): This method is provided to test if the time is syncronised or not\&. By default we test once per week\&.
.PP
\fBReturns:\fP
.RS 4
true if time is syncronised,false otherwise 
.RE
.PP

.PP
Definition at line 257 of file CoolTime\&.cpp\&.
.PP
References getLastSyncTime()\&.
.PP
Referenced by update()\&.
.PP
.nf
258 {
259 
260 #if DEBUG == 1
261 
262     Serial\&.println( F("Entering CoolTime\&.isTimeSync() ") );
263     Serial\&.println();
264 
265 #endif 
266 
267 
268     //default is once per week we try to get a time update
269     if( ( RTC\&.get(CLOCK_ADDRESS) - this->getLastSyncTime() ) > ( seconds ) ) 
270     {
271 
272     #if DEBUG == 1 
273 
274         Serial\&.println( F("time is not syncronised ") );
275     
276     #endif
277 
278         return(false);  
279     }
280     
281 #if DEBUG == 1 
282 
283     Serial\&.println( F("time is syncronised ") );
284 
285 #endif 
286 
287     return(true);
288 }
.fi
.SS "void CoolTime::printConf ()"
\fBCoolTime::printConf()\fP: This method is provided to print the \fBCoolTime\fP configuration to the Serial Monitor 
.PP
Definition at line 664 of file CoolTime\&.cpp\&.
.PP
References localPort, and timeServer\&.
.PP
Referenced by CoolBoard::begin()\&.
.PP
.nf
665 {
666 
667 #if DEBUG == 1
668 
669     Serial\&.println( F("Entering CoolTime\&.printConf()") );
670     Serial\&.println();
671 
672 #endif 
673 
674     Serial\&.println("RTC Configuration") ;
675 
676     Serial\&.print("timeServer : ");
677     Serial\&.println(timeServer);
678     
679     Serial\&.print("localPort : :");
680     Serial\&.println(localPort);
681 }
.fi
.SS "bool CoolTime::saveTimeSync ()"
\fBCoolTime::saveTimeSync()\fP This method is provided to save the last sync time in the SPIFFS\&.
.PP
\fBReturns:\fP
.RS 4
true if successful,false otherwise 
.RE
.PP

.PP
Definition at line 560 of file CoolTime\&.cpp\&.
.PP
References localPort, timeServer, and timeSync\&.
.PP
Referenced by update()\&.
.PP
.nf
561 {
562     Serial\&.println( F("Enter CoolTime\&.saveTimeSync()") );
563     Serial\&.println();
564 
565     File rtcConfig = SPIFFS\&.open("/rtcConfig\&.json", "r");
566 
567     if (!rtcConfig) 
568     {
569         Serial\&.println( F("failed to read /rtcConfig\&.json") );
570         Serial\&.println();
571 
572         return(false);
573     }
574     else
575     {
576         size_t size = rtcConfig\&.size();
577         // Allocate a buffer to store contents of the file\&.
578         std::unique_ptr<char[]> buf(new char[size]);
579 
580         rtcConfig\&.readBytes(buf\&.get(), size);
581         DynamicJsonBuffer jsonBuffer;
582         JsonObject& json = jsonBuffer\&.parseObject(buf\&.get());
583         if (!json\&.success()) 
584         {
585             Serial\&.println( F("failed to parse json") );
586             Serial\&.println();
587 
588             return(false);
589         } 
590         else
591         {   
592             Serial\&.println( F("configuration json is :") );
593             json\&.printTo(Serial);
594             Serial\&.println();
595 
596             String ip;
597                     
598             if(json["timeServer"]\&.success() )
599             {           
600                  ip=json["timeServer"]\&.as<String>();
601                 this->timeServer\&.fromString(ip);
602                 
603             }
604             else
605             {
606                 this->timeServer=this->timeServer;
607             }
608             json["timeServer"]=ip;
609             
610             if(json["localPort"]\&.success() )
611             {                       
612                 this->localPort=json["localPort"];
613             }
614             else
615             {
616                 this->localPort=this->localPort;
617             }
618             json["localPort"]=this->localPort;
619 
620 
621             if( json["timeSync"]\&.success() )
622             {
623                 json["timeSync"]=this->timeSync;
624             }
625             else
626             {
627                 this->timeSync=this->timeSync;
628             }
629             json["timeSync"]=this->timeSync;
630 
631 
632             rtcConfig\&.close();
633             rtcConfig= SPIFFS\&.open("/rtcConfig\&.json", "w");
634             
635             if(!rtcConfig)
636             {
637                 Serial\&.println( F("failed to write timeSync to /rtcConfig\&.json") );
638                 Serial\&.println();
639 
640                 return(false);
641             }
642             
643             json\&.printTo(rtcConfig);
644             rtcConfig\&.close();
645 
646             Serial\&.println( F("configuration is :") );
647             json\&.printTo(Serial);
648             Serial\&.println();
649         
650             return(true); 
651         }
652     }   
653 
654 
655 
656 }
.fi
.SS "void CoolTime::sendNTPpacket (IPAddress & address)"
CoolTime::sendNTPpacket( Time Server IP address): This method is provided to send an NTP request to the time server at the given address 
.PP
Definition at line 367 of file CoolTime\&.cpp\&.
.PP
References NTP_PACKET_SIZE, packetBuffer, and Udp\&.
.PP
Referenced by getNtpTime()\&.
.PP
.nf
368 {
369 
370 #if DEBUG == 1 
371 
372     Serial\&.println( F("Enter CoolTime\&.sendNTPpacket()") );
373     Serial\&.println();
374 
375 #endif
376 
377     memset(packetBuffer, 0, NTP_PACKET_SIZE);
378     // Initialize values needed to form NTP request
379     // (see URL above for details on the packets)
380     packetBuffer[0] = 0b11100011;   // LI, Version, Mode
381     packetBuffer[1] = 0;     // Stratum, or type of clock
382     packetBuffer[2] = 6;     // Polling Interval
383     packetBuffer[3] = 0xEC;  // Peer Clock Precision
384     // 8 bytes of zero for Root Delay & Root Dispersion
385     packetBuffer[12]  = 49;
386     packetBuffer[13]  = 0x4E;
387     packetBuffer[14]  = 49;
388     packetBuffer[15]  = 52;
389     // all NTP fields have been given values, now
390     // you can send a packet requesting a timestamp:                 
391     Udp\&.beginPacket(address, 123); //NTP requests are to port 123
392     Udp\&.write(packetBuffer, NTP_PACKET_SIZE);
393     Udp\&.endPacket(); 
394 }
.fi
.SS "void CoolTime::setDateTime (int year, int month, int day, int hour, int minutes, int seconds)"
CoolTime::setDateTime(year,month,dat,hour,minutes,seconds): This method is provided to manually set the RTc Time 
.PP
Definition at line 96 of file CoolTime\&.cpp\&.
.PP
References formatDigits(), getESDate(), and rtc\&.
.PP
.nf
97 { 
98 
99 #if DEBUG == 1
100 
101     Serial\&.println( F("Entering CoolTime\&.setDateTime") );
102     Serial\&.println();
103 
104 #endif
105 
106     tmElements_t tm;
107     tm\&.Second=seconds; 
108     tm\&.Minute=minutes; 
109     tm\&.Hour=hour; 
110     tm\&.Day=day;
111     tm\&.Month=month; 
112     tm\&.Year=year;
113     
114     this->rtc\&.set(makeTime(tm),CLOCK_ADDRESS);   
115 
116 #if DEBUG == 1
117 
118     Serial\&.print( F("setting time to : ") );//"20yy-mm-ddT00:00:00Z
119 
120     Serial\&.print(tm\&.Year);
121     Serial\&.print( F("-") );
122     Serial\&.print( this->formatDigits( tm\&.Month ) );
123     Serial\&.print( F("-") );
124     Serial\&.print( this->formatDigits( tm\&.Day ) );
125     Serial\&.print( F("T") );
126     Serial\&.print( this->formatDigits( tm\&.Hour ) );
127     Serial\&.print( F(":") );
128     Serial\&.print( this->formatDigits( tm\&.Minute ) );
129     Serial\&.print( F(":") );
130     Serial\&.print( this->formatDigits( tm\&.Second ) );
131     Serial\&.print( F("Z") );
132 
133     Serial\&.println();
134     
135     Serial\&.print( F("time set to : ") );
136     Serial\&.println(this->getESDate());
137     Serial\&.println();
138 
139 #endif
140 
141 }
.fi
.SS "void CoolTime::update ()"
\fBCoolTime::update()\fP: This method is provided to correct the rtc Time when it drifts,once every week\&. 
.PP
Definition at line 63 of file CoolTime\&.cpp\&.
.PP
References getNtpTime(), isTimeSync(), rtc, saveTimeSync(), timeSync, and tmSet\&.
.PP
Referenced by begin(), and CoolBoard::onLineMode()\&.
.PP
.nf
64 {
65 
66 #if DEBUG == 1
67 
68     Serial\&.println( F("Entering CoolTime\&.update()") );
69     Serial\&.println();
70 
71 #endif 
72 
73     if( !( this->isTimeSync() ) )
74     {
75     
76     #if DEBUG == 1
77 
78         Serial\&.println( F("waiting for sync") );
79         Serial\&.println();
80 
81     #endif 
82 
83         this->timeSync=this->getNtpTime();
84         breakTime(this->getNtpTime(), this->tmSet);
85         this->rtc\&.set(makeTime(this->tmSet), CLOCK_ADDRESS); // set the clock
86         this->saveTimeSync();
87     }
88     
89 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "unsigned int CoolTime::localPort =0\fC [private]\fP"

.PP
Definition at line 71 of file CoolTime\&.h\&.
.PP
Referenced by begin(), config(), printConf(), and saveTimeSync()\&.
.SS "byte CoolTime::packetBuffer[\fBNTP_PACKET_SIZE\fP]\fC [private]\fP"

.PP
Definition at line 73 of file CoolTime\&.h\&.
.PP
Referenced by getNtpTime(), and sendNTPpacket()\&.
.SS "DS1337RTC CoolTime::rtc\fC [private]\fP"

.PP
Definition at line 77 of file CoolTime\&.h\&.
.PP
Referenced by getTimeDate(), setDateTime(), and update()\&.
.SS "IPAddress CoolTime::timeServer\fC [private]\fP"

.PP
Definition at line 67 of file CoolTime\&.h\&.
.PP
Referenced by config(), getNtpTime(), printConf(), and saveTimeSync()\&.
.SS "unsigned long CoolTime::timeSync =0\fC [private]\fP"

.PP
Definition at line 65 of file CoolTime\&.h\&.
.PP
Referenced by config(), getLastSyncTime(), saveTimeSync(), and update()\&.
.SS "tmElements_t CoolTime::tmSet\fC [private]\fP"

.PP
Definition at line 75 of file CoolTime\&.h\&.
.PP
Referenced by update()\&.
.SS "WiFiUDP CoolTime::Udp\fC [private]\fP"

.PP
Definition at line 69 of file CoolTime\&.h\&.
.PP
Referenced by begin(), getNtpTime(), and sendNTPpacket()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
