.TH "/home/ashiroji/Arduino/libraries/CoolBoard/CoolFileSystem.h" 3 "Mon Jul 31 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/CoolFileSystem.h \- \fBCoolFileSystem\fP Header File\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCoolFileSystem\fP"
.br
.RI "This class handles the file system\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBCoolFileSystem\fP Header File\&. 


.PP
\fBAuthor:\fP
.RS 4
Mehdi Zemzem 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
27/06/2017 
.RE
.PP

.PP
Definition in file \fBCoolFileSystem\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
