CoolTime
NAME
CoolTime - This class manages the DS1337 RTC .
SYNOPSIS
#include <CoolTime.h>
Public Member Functions
void begin ()
void update ()
bool config ()
void config (IPAddress timeServer, unsigned int localPort)
void printConf ()
void setDateTime (int year, int month, int day, int hour, int minutes, int seconds)
tmElements_t getTimeDate ()
String getESDate ()
unsigned long getLastSyncTime ()
bool isTimeSync (unsigned long seconds=604800)
time_t getNtpTime ()
void sendNTPpacket (IPAddress &address)
String formatDigits (int digits)
bool saveTimeSync ()
bool saveTimeSync ()
Private Attributes
unsigned long timeSync =0
IPAddress timeServer
WiFiUDP Udp
unsigned int localPort =0
byte packetBuffer [NTP_PACKET_SIZE]
tmElements_t tmSet
DS1337RTC rtc
Detailed Description
This class manages the DS1337 RTC .
Definition at line 31 of file CoolTime.h.
Member Function Documentation
void CoolTime::begin ()
CoolTime::begin(): This method is provided to init the udp connection
Definition at line 41 of file CoolTime.cpp.
References localPort, Udp, and update().
Referenced by CoolBoard::begin().
{
#if DEBUG == 1
    Serial.println("Entering CoolTime.begin()");
    Serial.println();
<<<<<<< HEAD
#endif
=======
>>>>>>> 022ecfccbd47fa628feca52fc7c1ee420c585e2b
    Udp.begin(localPort);
    this->update();
    
    this->update();
    
}
bool CoolTime::config ()
CoolTime::config(): This method is provided to configure the CoolTime object through a configuration file.
Returns:
true if successful,false otherwise
CoolTime::saveTimeSync() This method is provided to save last syncronisation time to the SPIFFS
CoolTime::printConf(): This method is provided to print the CoolTime configuration to the Serial Monitor
CoolTime::printDigits(digit)
utility method for digital clock display adds leading 0
Returns:
formatted string of the input digit
Definition at line 445 of file CoolTime.cpp.
References formatDigits(), localPort, printConf(), saveTimeSync(), timeServer, and timeSync.
Referenced by CoolBoard::begin(), and CoolBoard::update().
{
#if DEBUG == 1
    Serial.println("Enter CoolTime.config()");
    Serial.println();
#endif
    File rtcConfig = SPIFFS.open("/rtcConfig.json", "r");
    if (!rtcConfig)
    {
    
    #if DEBUG == 1
        Serial.println("failed to read /rtcConfig.json");
        Serial.println();
    
    #endif
        return(false);
    }
    else
    {
        size_t size = rtcConfig.size();
        // Allocate a buffer to store contents of the file.
        std::unique_ptr<char[]> buf(new char[size]);
        rtcConfig.readBytes(buf.get(), size);
        DynamicJsonBuffer jsonBuffer;
        JsonObject& json = jsonBuffer.parseObject(buf.get());
        if (!json.success())
        {
        
        #if DEBUG == 1
            Serial.println("failed to parse json");
            Serial.println();
        
        #endif
            return(false);
        }
        else
        {
        
        #if DEBUG == 1
            Serial.println("configuration json is :");
            json.printTo(Serial);
            Serial.println();
        #endif
            String ip;
            
            if(json["timeServer"].success() )
            {
                 ip=json["timeServer"].as<String>();
                this->timeServer.fromString(ip);
                
            }
            else
            {
                this->timeServer=this->timeServer;
            }
            json["timeServer"]=ip;
            
            if(json["localPort"].success() )
            {
                this->localPort=json["localPort"];
            }
            else
            {
                this->localPort=this->localPort;
            }
            json["localPort"]=this->localPort;
<<<<<<< HEAD
            if(json["timeSync"].success() )
            {
=======
            if( json["timeSync"].success() )
            {
>>>>>>> 022ecfccbd47fa628feca52fc7c1ee420c585e2b
                this->timeSync=json["timeSync"];
            }
            else
            {
                this->timeSync=this->timeSync;
            }
            json["timeSync"]=this->timeSync;
<<<<<<< HEAD
=======
>>>>>>> 022ecfccbd47fa628feca52fc7c1ee420c585e2b
            rtcConfig.close();
            rtcConfig= SPIFFS.open("/rtcConfig.json", "w");
            
            if(!rtcConfig)
            {
            
            #if DEBUG == 1
                Serial.println("failed to write to /rtcConfig.json");
                Serial.println();
            
            #endif
                return(false);
            }
            
            json.printTo(rtcConfig);
            rtcConfig.close();
        #if DEBUG == 1
            Serial.println("configuration is :");
            json.printTo(Serial);
            Serial.println();
        
        #endif
        
            return(true);
        }
    }
}
bool CoolTime::saveTimeSync()
{
    Serial.println("Enter CoolTime.saveTimeSync()");
    Serial.println();
    File rtcConfig = SPIFFS.open("/rtcConfig.json", "r");
    if (!rtcConfig)
    {
        Serial.println("failed to read /rtcConfig.json");
        Serial.println();
        return(false);
    }
    else
    {
        size_t size = rtcConfig.size();
        // Allocate a buffer to store contents of the file.
        std::unique_ptr<char[]> buf(new char[size]);
        rtcConfig.readBytes(buf.get(), size);
        DynamicJsonBuffer jsonBuffer;
        JsonObject& json = jsonBuffer.parseObject(buf.get());
        if (!json.success())
        {
            Serial.println("failed to parse json");
            Serial.println();
            return(false);
        }
        else
        {
            Serial.println("configuration json is :");
            json.printTo(Serial);
            Serial.println();
            String ip;
            
            if(json["timeZone"].success() )
            {
                this->timeZone=json["timeZone"] ;
            }
            else
            {
                this->timeZone=this->timeZone;
            }
            json["timeZone"]=this->timeZone;
            
            if(json["timeServer"].success() )
            {
                 ip=json["timeServer"].as<String>();
                this->timeServer.fromString(ip);
                
            }
            else
            {
                this->timeServer=this->timeServer;
            }
            json["timeServer"]=ip;
            
            if(json["localPort"].success() )
            {
                this->localPort=json["localPort"];
            }
            else
            {
                this->localPort=this->localPort;
            }
            json["localPort"]=this->localPort;
            if( json["timeSync"].success() )
            {
                json["timeSync"]=this->timeSync;
            }
            else
            {
                this->timeSync=this->timeSync;
            }
            json["timeSync"]=this->timeSync;
            rtcConfig.close();
            rtcConfig= SPIFFS.open("/rtcConfig.json", "w");
            
            if(!rtcConfig)
            {
                Serial.println("failed to write timeSync to /rtcConfig.json");
                Serial.println();
                return(false);
            }
            
            json.printTo(rtcConfig);
            rtcConfig.close();
            Serial.println("configuration is :");
            json.printTo(Serial);
            Serial.println();
        
            return(true);
        }
    }
}
void CoolTime::printConf()
{
#if DEBUG == 1
    Serial.println("Entering CoolTime.printConf()");
    Serial.println();
#endif
<<<<<<< HEAD
    Serial.println("RTC Configuration") ;
=======
    //Serial.print("timeZone : ");
    //Serial.println(timeZone);
>>>>>>> 022ecfccbd47fa628feca52fc7c1ee420c585e2b
    Serial.print("timeServer : ");
    Serial.println(timeServer);
    
    Serial.print("localPort : :");
    Serial.println(localPort);
}
String CoolTime::formatDigits(int digits)
{
<<<<<<< HEAD
#if DEBUG == 1
    Serial.println("Entering CoolTime.formatDigits()");
    Serial.println();
=======
    //Serial.println("Entering CoolTime.formatDigits()");
    //Serial.println();
>>>>>>> 022ecfccbd47fa628feca52fc7c1ee420c585e2b
#endif
    if(digits < 10)
    {
<<<<<<< HEAD
    
    #if DEBUG == 1
        Serial.println("output digit : ");
        Serial.println( String("0") + String(digits) );
    #endif
        return( String("0") + String(digits) );
    }
    
#if DEBUG == 1
    Serial.println("output digit : ");
    Serial.println(digits);
#endif
=======
        //Serial.println("output digit : ");
        //Serial.println( String("0") + String(digits) );
        return( String("0") + String(digits) );
    }
    
    //Serial.println("output digit : ");
    //Serial.println(digits);
>>>>>>> 022ecfccbd47fa628feca52fc7c1ee420c585e2b
    return( String(digits) );
}
void CoolTime::config (IPAddress timeServer, unsigned int localPort)
CoolTime::config(Time server IP , udp Port): This method is provided to do manual configuration.
Definition at line 422 of file CoolTime.cpp.
References localPort, and timeServer.
{
#if DEBUG == 1
    Serial.println("Enter CoomTime.config() , no SPIFFS variant ");
    Serial.println();
#endif
    this->timeServer=timeServer;
    this->localPort=localPort;
    
}
String CoolTime::formatDigits (int digits)
Referenced by config(), getESDate(), getTimeDate(), and setDateTime().
String CoolTime::getESDate ()
CoolTime::getESD(): This method is provided to return an Elastic Search compatible date Format
Returns:
date String in Elastic Search format
Definition at line 202 of file CoolTime.cpp.
References formatDigits(), and getTimeDate().
Referenced by setDateTime(), and CoolBoard::userData().
{
#if DEBUG == 1
    Serial.println("Entering CoolTime.getESDate()");
    Serial.println();
#endif
    tmElements_t tm=this->getTimeDate();
    //"20yy-mm-ddT00:00:00Z"
    String elasticSearchString =String(tm.Year+1970)+"-"+this->formatDigits(tm.Month)+"-";
    elasticSearchString +=this->formatDigits(tm.Day)+"T"+this->formatDigits(tm.Hour)+":";
    
    elasticSearchString +=this->formatDigits(tm.Minute)+":"+this->formatDigits(tm.Second)+"Z";
#if DEBUG == 1
    Serial.print("elastic Search date : ");
    Serial.println(elasticSearchString);
    Serial.println();
#endif
    return (elasticSearchString);
}
unsigned long CoolTime::getLastSyncTime ()
CoolTime::getLastSyncTime(): This method is provided to get the last time we syncronised the time
Returns:
unsigned long representation of last syncronisation time in seconds
Definition at line 240 of file CoolTime.cpp.
References timeSync.
Referenced by isTimeSync().
{
#if DEBUG == 1
    Serial.println("Entering CoolTime.getLastSyncTime()");
    Serial.println();
    
    Serial.print("last sync time : ");
    Serial.println(this->timeSync);
#endif
    return(this->timeSync);
}
time_t CoolTime::getNtpTime ()
CoolTime::getNtopTime(): This method is provided to get the Time through an NTP request to a Time Server
Returns:
a time_t (unsigned long ) timestamp in seconds
Definition at line 312 of file CoolTime.cpp.
References NTP_PACKET_SIZE, packetBuffer, sendNTPpacket(), timeServer, and Udp.
Referenced by update().
{
#if DEBUG == 1
    Serial.println("Entering CoolTime.getNtpTime()");
    Serial.println();
#endif
    while (Udp.parsePacket() > 0) ; // discard any previously received packets
#if DEBUG == 1
    
    Serial.println("Transmit NTP Request");
#endif
    sendNTPpacket(timeServer);
    uint32_t beginWait = millis();
    while (millis() - beginWait < 1500)
    {
        int size = Udp.parsePacket();
        if (size >= NTP_PACKET_SIZE)
        {
        
        #if DEBUG == 1
            Serial.println("Receive NTP Response");
        
        #endif
            Udp.read(packetBuffer, NTP_PACKET_SIZE); // read packet into the buffer
            unsigned long secsSince1900;
            // convert four bytes starting at location 40 to a long integer
            secsSince1900 = (unsigned long)packetBuffer[40] << 24;
            secsSince1900 |= (unsigned long)packetBuffer[41] << 16;
            secsSince1900 |= (unsigned long)packetBuffer[42] << 8;
            secsSince1900 |= (unsigned long)packetBuffer[43];
        
        #if DEBUG == 1
    
            Serial.print("received unix time : ");
            Serial.println(secsSince1900 - 2208988800UL);
            Serial.println();
<<<<<<< HEAD
        #endif
=======
            //Serial.print("received unix time +");
            //Serial.print(this->timeZone);
            //Serial.print(" : ");
            //Serial.println( secsSince1900 - 2208988800UL + this->timeZone * SECS_PER_HOUR );
            //Serial.println();
>>>>>>> 022ecfccbd47fa628feca52fc7c1ee420c585e2b
            
            return secsSince1900 - 2208988800UL ;
        }
    }
    
#if DEBUG == 1
    Serial.println("No NTP Response :-(");
#endif
    return 0; // return 0 if unable to get the time
}
tmElements_t CoolTime::getTimeDate ()
CoolTime::getTimeDate(): This method is provided to get the RTC Time
Returns:
a tmElements_t structre that has the time in it
Definition at line 159 of file CoolTime.cpp.
References formatDigits(), and rtc.
Referenced by getESDate().
{
#if DEBUG == 1
    
    Serial.println("Entering CoolTime.getTimeDate()");
    Serial.println();
#endif
    tmElements_t tm;
    time_t timeDate = this->rtc.get(CLOCK_ADDRESS);
    breakTime(timeDate,tm);
#if DEBUG == 1
    
    Serial.print("time is : ");
    Serial.print(tm.Year+ 1970 );
    Serial.print("-");
    Serial.print( this->formatDigits( tm.Month ) );
    Serial.print("-");
    Serial.print( this->formatDigits( tm.Day ) );
    Serial.print("T");
    Serial.print( this->formatDigits( tm.Hour ) );
    Serial.print(":");
    Serial.print( this->formatDigits( tm.Minute ) );
    Serial.print( ":" );
    Serial.print( this->formatDigits( tm.Second ) );
    Serial.print("Z");
#endif
    
    return(tm);
}
bool CoolTime::isTimeSync (unsigned long seconds = 604800)
CoolTime::isTimeSync( time in seconds): This method is provided to test if the time is syncronised or not. By default we test once per week.
Returns:
true if time is syncronised,false otherwise
Definition at line 266 of file CoolTime.cpp.
References getLastSyncTime().
Referenced by update().
{
#if DEBUG == 1
    Serial.println("Entering CoolTime.isTimeSync() ");
    Serial.println();
<<<<<<< HEAD
#endif
    //default is once per week we try to get a time update
    if( ( RTC.get( CLOCK_ADDRESS ) ) - ( this->getLastSyncTime() ) > ( seconds ) )
=======
//default is once per week we try to get a time update
    if( ( RTC.get(CLOCK_ADDRESS) - this->getLastSyncTime() ) > ( seconds ) )
>>>>>>> 022ecfccbd47fa628feca52fc7c1ee420c585e2b
    {
    #if DEBUG == 1
        Serial.println("time is not syncronised ");
    
    #endif
        return(false);
    }
    
#if DEBUG == 1
    Serial.println("time is syncronised ");
#endif
    return(true);
}
void CoolTime::printConf ()
Referenced by CoolBoard::begin(), and config().
bool CoolTime::saveTimeSync ()
CoolTime::saveTimeSync() This method is provided to save the last sync time in the SPIFFS.
Returns:
true if successful,false otherwise
Definition at line 790 of file CoolTime.cpp.
References localPort, timeServer, and timeSync.
Referenced by config(), and update().
{
#if DEBUG == 1
    Serial.println("Enter CoolTime.saveTimeSync()");
    Serial.println();
#endif
    File rtcConfig = SPIFFS.open("/rtcConfig.json", "r");
    if (!rtcConfig)
    {
    
    #if DEBUG == 1
        Serial.println("failed to read /rtcConfig.json");
        Serial.println();
    
    #endif
        return(false);
    }
    else
    {
        size_t size = rtcConfig.size();
        // Allocate a buffer to store contents of the file.
        std::unique_ptr<char[]> buf(new char[size]);
        rtcConfig.readBytes(buf.get(), size);
        DynamicJsonBuffer jsonBuffer;
        JsonObject& json = jsonBuffer.parseObject(buf.get());
        if (!json.success())
        {
        
        #if DEBUG == 1
            Serial.println("failed to parse json");
            Serial.println();
        
        #endif
            
            return(false);
        }
        else
        {
        
        #if DEBUG == 1
    
            Serial.println("configuration json is :");
            json.printTo(Serial);
            Serial.println();
        
        #endif
            String ip;
            
            if(json["timeServer"].success() )
            {
                 ip=json["timeServer"].as<String>();
                this->timeServer.fromString(ip);
                
            }
            else
            {
                this->timeServer=this->timeServer;
            }
            json["timeServer"]=ip;
            
            if(json["localPort"].success() )
            {
                this->localPort=json["localPort"];
            }
            else
            {
                this->localPort=this->localPort;
            }
            json["localPort"]=this->localPort;
            if(json["timeSync"].success() )
            {
                json["timeSync"]=this->timeSync;
            }
            else
            {
                this->timeSync=this->timeSync;
            }
            json["timeSync"]=this->timeSync;
            rtcConfig.close();
            rtcConfig= SPIFFS.open("/rtcConfig.json", "w");
            
            if(!rtcConfig)
            {
            
            #if DEBUG == 1
                Serial.println("failed to write to /rtcConfig.json");
                Serial.println();
            
            #endif
                return(false);
            }
            
            json.printTo(rtcConfig);
            rtcConfig.close();
        #if DEBUG == 1
            Serial.println("configuration is :");
            json.printTo(Serial);
            Serial.println();
        
        #endif
        
            return(true);
        }
    }
}
bool CoolTime::saveTimeSync ()
void CoolTime::sendNTPpacket (IPAddress & address)
CoolTime::sendNTPpacket( Time Server IP address): This method is provided to send an NTP request to the time server at the given address
Definition at line 388 of file CoolTime.cpp.
References NTP_PACKET_SIZE, packetBuffer, and Udp.
Referenced by getNtpTime().
{
#if DEBUG == 1
    Serial.println("Enter CoolTime.sendNTPpacket()");
    Serial.println();
#endif
    memset(packetBuffer, 0, NTP_PACKET_SIZE);
    // Initialize values needed to form NTP request
    // (see URL above for details on the packets)
    packetBuffer[0] = 0b11100011; // LI, Version, Mode
    packetBuffer[1] = 0; // Stratum, or type of clock
    packetBuffer[2] = 6; // Polling Interval
    packetBuffer[3] = 0xEC; // Peer Clock Precision
    // 8 bytes of zero for Root Delay & Root Dispersion
    packetBuffer[12] = 49;
    packetBuffer[13] = 0x4E;
    packetBuffer[14] = 49;
    packetBuffer[15] = 52;
    // all NTP fields have been given values, now
    // you can send a packet requesting a timestamp:
    Udp.beginPacket(address, 123); //NTP requests are to port 123
    Udp.write(packetBuffer, NTP_PACKET_SIZE);
    Udp.endPacket();
}
void CoolTime::setDateTime (int year, int month, int day, int hour, int minutes, int seconds)
CoolTime::setDateTime(year,month,dat,hour,minutes,seconds): This method is provided to manually set the RTc Time
Definition at line 105 of file CoolTime.cpp.
References formatDigits(), getESDate(), and rtc.
{
#if DEBUG == 1
    Serial.println("Entering CoolTime.setDateTime");
    Serial.println();
#endif
    tmElements_t tm;
    tm.Second=seconds;
    tm.Minute=minutes;
    tm.Hour=hour;
    tm.Day=day;
    tm.Month=month;
    tm.Year=year;
    
    this->rtc.set(makeTime(tm),CLOCK_ADDRESS);
#if DEBUG == 1
    Serial.print("setting time to : ");//"20yy-mm-ddT00:00:00Z
    Serial.print(tm.Year);
    Serial.print("-");
    Serial.print( this->formatDigits( tm.Month ) );
    Serial.print("-");
    Serial.print( this->formatDigits( tm.Day ) );
    Serial.print("T");
    Serial.print( this->formatDigits( tm.Hour ) );
    Serial.print(":");
    Serial.print( this->formatDigits( tm.Minute ) );
    Serial.print( ":" );
    Serial.print( this->formatDigits( tm.Second ) );
    Serial.print("Z");
    Serial.println();
    
    Serial.print("time set to : ");
    Serial.println(this->getESDate());
    Serial.println();
#endif
}
void CoolTime::update ()
CoolTime::update(): This method is provided to correct the rtc Time when it drifts,once every week.
Definition at line 68 of file CoolTime.cpp.
References getNtpTime(), isTimeSync(), rtc, saveTimeSync(), timeSync, and tmSet.
Referenced by begin(), and CoolBoard::onLineMode().
{
#if DEBUG == 1
    Serial.println("Entering CoolTime.update()");
    Serial.println();
#endif
    if( !( this->isTimeSync() ) )
    {
    
    #if DEBUG == 1
        Serial.println("waiting for sync");
        Serial.println();
    #endif
        this->timeSync=this->getNtpTime();
        breakTime(this->getNtpTime(), this->tmSet);
        this->rtc.set(makeTime(this->tmSet), CLOCK_ADDRESS); // set the clock
<<<<<<< HEAD
=======
>>>>>>> 022ecfccbd47fa628feca52fc7c1ee420c585e2b
        this->saveTimeSync();
    }
    
}
Member Data Documentation
unsigned int CoolTime::localPort =0 [private]
Definition at line 73 of file CoolTime.h.
Referenced by begin(), config(), and saveTimeSync().
byte CoolTime::packetBuffer[NTP_PACKET_SIZE] [private]
Definition at line 75 of file CoolTime.h.
Referenced by getNtpTime(), and sendNTPpacket().
DS1337RTC CoolTime::rtc [private]
Definition at line 79 of file CoolTime.h.
Referenced by getTimeDate(), setDateTime(), and update().
IPAddress CoolTime::timeServer [private]
Definition at line 69 of file CoolTime.h.
Referenced by config(), getNtpTime(), and saveTimeSync().
unsigned long CoolTime::timeSync =0 [private]
Definition at line 67 of file CoolTime.h.
Referenced by config(), getLastSyncTime(), saveTimeSync(), and update().
tmElements_t CoolTime::tmSet [private]
Definition at line 77 of file CoolTime.h.
Referenced by update().
WiFiUDP CoolTime::Udp [private]
Definition at line 71 of file CoolTime.h.
Referenced by begin(), getNtpTime(), and sendNTPpacket().
Author
Generated automatically by Doxygen for CoolAPI from the source code.