.TH "/home/ashiroji/Arduino/libraries/CoolBoard/CoolBoardSensors.cpp" 3 "Fri Aug 4 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/CoolBoardSensors.cpp \- \fBCoolBoardSensors\fP Source File\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'FS\&.h'\fP
.br
\fC#include 'Arduino\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include 'Wire\&.h'\fP
.br
\fC#include 'ArduinoJson\&.h'\fP
.br
\fC#include 'CoolBoardSensors\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP   1"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCoolBoardSensors\fP Source File\&. 


.PP
\fBAuthor:\fP
.RS 4
Mehdi Zemzem 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
27/06/2017 
.RE
.PP

.PP
Definition in file \fBCoolBoardSensors\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBUG   1"

.PP
Definition at line 18 of file CoolBoardSensors\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
