CoolBoardLed
NAME
CoolBoardLed - This class handles the led in the Sensor Board.
SYNOPSIS
#include <CoolBoardLed.h>
Public Member Functions
void begin ()
void write (int R, int G, int B)
void end ()
bool config ()
void printConf ()
void fade (int R, int G, int B, float T)
void blink (int R, int G, int B, float T)
void fadeIn (int R, int G, int B, float T)
void fadeOut (int R, int G, int B, float T)
void strobe (int R, int G, int B, float T)
Private Attributes
NeoPixelBus< NeoGrbFeature, Neo800KbpsMethod > * neoPixelLed = NULL
byte ledActive =0
Detailed Description
This class handles the led in the Sensor Board.
Definition at line 20 of file CoolBoardLed.h.
Member Function Documentation
void CoolBoardLed::begin ()
CoolBoardLed::begin(): This method is provided to start the Led Object by setting the correct pin and creating a dynamic neoPixelBus
Definition at line 232 of file CoolBoardLed.cpp.
References ledActive, and neoPixelLed.
Referenced by CoolBoard::config().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardLed.begin() ") );
#endif
    yield();
    if(this->ledActive == 1 )
    {
        pinMode(5,OUTPUT);
        digitalWrite(5,HIGH);
        neoPixelLed = new NeoPixelBus<NeoGrbFeature, Neo800KbpsMethod>(1,2);
        neoPixelLed->Begin();
        neoPixelLed->Show();
    }
}
void CoolBoardLed::blink (int R, int G, int B, float T)
CoolBoardLed::blink( Red , Green , Blue , Time in seconds ): Blink animation: Led On for T seconds Led off
Definition at line 74 of file CoolBoardLed.cpp.
References ledActive, and neoPixelLed.
Referenced by CoolBoard::begin(), CoolBoard::config(), CoolBoard::connect(), CoolBoard::offLineMode(), and CoolBoard::onLineMode().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardLed.blink()"));
    Serial.println();
    Serial.print( F("R : "));
    Serial.println(R);
    Serial.print( F("G : ") );
    Serial.println(G);
    Serial.print( F("B : ") );
    Serial.println(B);
    Serial.print( F("Time :") );
    Serial.println(T);
    Serial.println();
#endif
    if(this->ledActive == 1 )
    {
        neoPixelLed->SetPixelColor(0, RgbColor(R, G, B));
        neoPixelLed->Show();
        delay(T);
        neoPixelLed->SetPixelColor(0, RgbColor(0, 0, 0));
        neoPixelLed->Show();
    }
}
bool CoolBoardLed::config ()
CoolBoardLed::config(): This method is provided to configure the Led Object : -ledActive=0 : deactivated -ledActive=1 : activated
Returns:
true if the configuration done, false otherwise
Definition at line 291 of file CoolBoardLed.cpp.
References ledActive.
Referenced by CoolBoard::config().
{
#if DEBUG == 1
        
    Serial.println( F("Entering CoolBoardLed.config()") );
    Serial.println();
#endif
    
    File coolBoardLedConfig = SPIFFS.open("/coolBoardLedConfig.json", "r");
    if (!coolBoardLedConfig)
    {
    
    #if DEBUG == 1
        Serial.println( F("failed to read /coolBoardLedConfig.json") );
        Serial.println();
    #endif
        return(false);
    }
    else
    {
        size_t size = coolBoardLedConfig.size();
        // Allocate a buffer to store contents of the file.
        std::unique_ptr<char[]> buf(new char[size]);
        coolBoardLedConfig.readBytes(buf.get(), size);
        DynamicJsonBuffer jsonBuffer;
        JsonObject& json = jsonBuffer.parseObject(buf.get());
        if (!json.success())
        {
        
        #if DEBUG == 1
            Serial.println( F("failed to parse json") );
            Serial.println();
        
        #endif
            return(false);
        }
        else
        {
        
        #if DEBUG == 1
    
            Serial.println( F("read configuration file : ") );
            json.printTo(Serial);
            Serial.println();
            
            Serial.print(F("jsonBuffer size :"));
            Serial.println(jsonBuffer.size());
            Serial.println();
        #endif
  
            if(json["ledActive"].success() )
            {
                this->ledActive = json["ledActive"];
            }
            else
            {
                this->ledActive=this->ledActive;
            }
            
            json["ledActive"]=this->ledActive;
            coolBoardLedConfig.close();
            
            coolBoardLedConfig = SPIFFS.open("/coolBoardLedConfig.json", "w");
            if(!coolBoardLedConfig)
            {
            
            #if DEBUG == 1
                Serial.println( F("failed to write to /coolBoardLedConfig.json") );
                Serial.println();
            #endif
                return(false);
            }
            json.printTo(coolBoardLedConfig);
            coolBoardLedConfig.close();
        #if DEBUG == 1
    
            Serial.println( F("saved Led Config is : ") );
            json.printTo(Serial);
            Serial.println();
        #endif
            return(true);
        }
    }
}
void CoolBoardLed::end ()
CoolBoardLed::end() : this method is provided to delete the dynamically created neoPixelLed
Definition at line 213 of file CoolBoardLed.cpp.
References neoPixelLed.
{
#if DEBUG == 1
    
    Serial.println( F("Entering CoolBoardLed.end()") );
#endif
    delete neoPixelLed;
}
void CoolBoardLed::fade (int R, int G, int B, float T)
CoolBoardLed::fade ( Red , Green , Blue, Time in seconds ): fade animation: Fade In over T(seconds) Fade Out over T(seconds)
Definition at line 33 of file CoolBoardLed.cpp.
References ledActive, and neoPixelLed.
Referenced by CoolBoard::offLineMode(), and CoolBoard::onLineMode().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardLed.fade()") );
    Serial.println();
    Serial.print( F("R : ") );
    Serial.println(R);
    Serial.print( F("G : ") );
    Serial.println(G);
    Serial.print( F("B : ") );
    Serial.println(B);
    Serial.print( F("Time : ") );
    Serial.println(T);
    Serial.println();
#endif
    if(this->ledActive == 1 )
    {
        for (int k = 0; k < 1000; k++)
        {
            neoPixelLed->SetPixelColor(0, RgbColor(k * R / 1000, k * G / 1000, k * B / 1000));
            neoPixelLed->Show();
            delay(T);
        }
        
        for (int k = 1000; k >= 0; k--)
        {
            neoPixelLed->SetPixelColor(0, RgbColor(k * R / 1000, k * G / 1000, k * B / 1000));
            neoPixelLed->Show();
            delay(T);
        }
    }
}
void CoolBoardLed::fadeIn (int R, int G, int B, float T)
CoolBoardLed::fadeIn(Red , Green , Blue , Time in seconds) Fade In animation: gradual increase over T(seconds)
Definition at line 107 of file CoolBoardLed.cpp.
References ledActive, and neoPixelLed.
Referenced by CoolBoard::config(), CoolBoard::offLineMode(), CoolBoard::onLineMode(), CoolBoard::readSensors(), and CoolBoard::update().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardLed.fadeIn()") );
    Serial.println();
    Serial.print( F("R : ") );
    Serial.println(R);
    Serial.print( F("G : ") );
    Serial.println(G);
    Serial.print( F("B : ") );
    Serial.println(B);
    Serial.print( F("Time :") );
    Serial.println(T);
    Serial.println();
#endif
    
    if(this->ledActive == 1 )
    {
        for (int k = 0; k < 1000; k++)
        {
            neoPixelLed->SetPixelColor(0, RgbColor(k * R / 1000, k * G / 1000, k * B / 1000));
            neoPixelLed->Show();
            delay(T);
        }
    }
}
void CoolBoardLed::fadeOut (int R, int G, int B, float T)
CoolBoardLed::fadeOut( Red , Green , Blue , Time in seconds) Fade Out animation: gradual decrease over T(seconds)
Definition at line 142 of file CoolBoardLed.cpp.
References ledActive, and neoPixelLed.
Referenced by CoolBoard::begin(), CoolBoard::config(), CoolBoard::offLineMode(), CoolBoard::onLineMode(), CoolBoard::readSensors(), and CoolBoard::update().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardLed.fadeOut()" ) );
    Serial.println();
    Serial.print( F("R : ") );
    Serial.println(R);
    Serial.print( F("G : ") );
    Serial.println(G);
    Serial.print( F("B : ") );
    Serial.println(B);
    Serial.print( F("Time :") );
    Serial.println(T);
    Serial.println();
#endif
    if(this->ledActive == 1 )
    {
        for (int k = 1000; k >= 0; k--)
        {
            neoPixelLed->SetPixelColor(0, RgbColor(k * R / 1000, k * G / 1000, k * B / 1000));
            neoPixelLed->Show();
            delay(T);
        }
    }
}
void CoolBoardLed::printConf ()
CoolBoardLed::printConf(): This method is provided to print the Led Object Configuration to the Serial Monitor
Definition at line 400 of file CoolBoardLed.cpp.
References ledActive.
Referenced by CoolBoard::begin().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardLed.printConf()") );
    Serial.println();
#endif
    Serial.println("Led Configuration");
    Serial.print("ledActive : ");
    Serial.println(ledActive);
    Serial.println();
}
void CoolBoardLed::strobe (int R, int G, int B, float T)
CoolBoardLed::strobe(Red , Green , Blue , Time in seconds) Strobe animation: blinks over T(seconds)
Definition at line 176 of file CoolBoardLed.cpp.
References ledActive, and neoPixelLed.
Referenced by CoolBoard::config(), CoolBoard::onLineMode(), CoolBoard::readSensors(), and CoolBoard::update().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardLed.strobe()") );
    Serial.println();
    Serial.print( F("R : ") );
    Serial.println(R);
    Serial.print( F("G: ") );
    Serial.println(G);
    Serial.print( F("B : ") );
    Serial.println(B);
    Serial.print( F("Time :") );
    Serial.println(T);
    Serial.println();
#endif
    if(this->ledActive == 1 )
    {
        for (int k = 1000; k >= 0; k--)
        {
            neoPixelLed->SetPixelColor(0, RgbColor(R, G, B));
            neoPixelLed->Show();
            delay(T);
            neoPixelLed->SetPixelColor(0, RgbColor(0, 0, 0));
            neoPixelLed->Show();
            delay(T);
        }
    }
}
void CoolBoardLed::write (int R, int G, int B)
CoolBoardLed::write(Red,Green,Blue): This method is provided to set the Color of the Led
Definition at line 258 of file CoolBoardLed.cpp.
References ledActive, and neoPixelLed.
Referenced by CoolBoard::begin(), and CoolBoard::connect().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardLed.write()") );
    Serial.println();
    Serial.print( F("R : ") );
    Serial.println(R);
    Serial.print( F("G : ") );
    Serial.println(G);
    Serial.print( F("B : ") );
    Serial.println(B);
    Serial.println();
#endif
    if(this->ledActive == 1 )
    {
        neoPixelLed->SetPixelColor(0, RgbColor(R, G, B));
        neoPixelLed->Show();
    }
}
Member Data Documentation
byte CoolBoardLed::ledActive =0 [private]
Definition at line 55 of file CoolBoardLed.h.
Referenced by begin(), blink(), config(), fade(), fadeIn(), fadeOut(), printConf(), strobe(), and write().
NeoPixelBus<NeoGrbFeature, Neo800KbpsMethod>* CoolBoardLed::neoPixelLed = NULL [private]
Definition at line 53 of file CoolBoardLed.h.
Referenced by begin(), blink(), end(), fade(), fadeIn(), fadeOut(), strobe(), and write().
Author
Generated automatically by Doxygen for CoolAPI from the source code.