.TH "CoolBoardSensors::lightActive" 3 "Wed Jun 28 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoolBoardSensors::lightActive
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "byte \fBir\fP"
.br
.ti -1c
.RI "byte \fBuv\fP"
.br
.ti -1c
.RI "byte \fBvisible\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file CoolBoardSensors\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "byte CoolBoardSensors::lightActive::ir"

.PP
Definition at line 84 of file CoolBoardSensors\&.h\&.
.PP
Referenced by CoolBoardSensors::allActive(), CoolBoardSensors::config(), CoolBoardSensors::printConf(), and CoolBoardSensors::read()\&.
.SS "byte CoolBoardSensors::lightActive::uv"

.PP
Definition at line 85 of file CoolBoardSensors\&.h\&.
.PP
Referenced by CoolBoardSensors::allActive(), CoolBoardSensors::config(), CoolBoardSensors::printConf(), and CoolBoardSensors::read()\&.
.SS "byte CoolBoardSensors::lightActive::visible"

.PP
Definition at line 83 of file CoolBoardSensors\&.h\&.
.PP
Referenced by CoolBoardSensors::allActive(), CoolBoardSensors::config(), CoolBoardSensors::printConf(), and CoolBoardSensors::read()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
