.TH "/home/ashiroji/Arduino/libraries/CoolBoard/CoolBoardLed.cpp" 3 "Wed Aug 2 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/CoolBoardLed.cpp \- \fBCoolBoardLed\fP Source File\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'FS\&.h'\fP
.br
\fC#include 'Arduino\&.h'\fP
.br
\fC#include <NeoPixelBus\&.h>\fP
.br
\fC#include 'CoolBoardLed\&.h'\fP
.br
\fC#include 'ArduinoJson\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP   1"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCoolBoardLed\fP Source File\&. 


.PP
\fBAuthor:\fP
.RS 4
Mehdi Zemzem 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBCoolBoardLed\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBUG   1"

.PP
Definition at line 18 of file CoolBoardLed\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
