.TH "/home/ashiroji/Arduino/libraries/CoolBoard/CoolFileSystem.h" 3 "Tue Jun 27 2017" "COOLAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/CoolFileSystem.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCoolFileSystem\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for COOLAPI from the source code\&.
