CoolBoardSensors
NAME
CoolBoardSensors - This class handles the On-Board Sensors.
SYNOPSIS
#include <CoolBoardSensors.h>
Classes
struct airActive
struct lightActive
Public Member Functions
CoolBoardSensors ()
void begin ()
String read ()
int getJsonSize ()
void setJsonSize (int jsonSize)
void allActive ()
void initReadI2C ()
void stopReadI2C ()
void end ()
bool config ()
void printConf ()
void setEnvSensorSettings (uint8_t commInterface=I2C_MODE, uint8_t I2CAddress=0x76, uint8_t runMode=3, uint8_t tStandby=0, uint8_t filter=0, uint8_t tempOverSample=1, uint8_t pressOverSample=1, uint8_t humidOverSample=1)
float readVBat ()
float readMoisture ()
Public Attributes
SI114X lightSensor = SI114X()
BME280 envSensor
Private Attributes
struct CoolBoardSensors::lightActive lightDataActive
struct CoolBoardSensors::airActive airDataActive
const int EnMoisture = 13
const int AnMplex = 12
const int EnI2C = 5
byte vbatActive =0
byte soilMoistureActive =0
int jsonSize =500
Detailed Description
This class handles the On-Board Sensors.
Definition at line 24 of file CoolBoardSensors.h.
Constructor & Destructor Documentation
CoolBoardSensors::CoolBoardSensors ()
CoolBoardSensors::CoolBoardSensors(): This Constructor is provided to start the I2C interface and Init the different used pins
Definition at line 35 of file CoolBoardSensors.cpp.
References AnMplex, EnI2C, and EnMoisture.
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardSensors Constructor") );
    Serial.println();
#endif
    
    Wire.begin(2, 14); //I2C init Maybe change this to the CoolBoard?
    pinMode(AnMplex, OUTPUT); //Declare Analog Multiplexer OUTPUT
    pinMode(EnMoisture, OUTPUT); //Declare Moisture enable Pin
    pinMode(EnI2C, OUTPUT); //Declare I2C Enable pin
}
Member Function Documentation
void CoolBoardSensors::allActive ()
CoolBoardSensors::allActive(): This method is provided to allow activation of all the sensor board sensors without passing by the configuration file/method
Definition at line 110 of file CoolBoardSensors.cpp.
References airDataActive, CoolBoardSensors::airActive::humidity, CoolBoardSensors::lightActive::ir, lightDataActive, CoolBoardSensors::airActive::pressure, soilMoistureActive, CoolBoardSensors::airActive::temperature, CoolBoardSensors::lightActive::uv, vbatActive, and CoolBoardSensors::lightActive::visible.
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardSensors.allActive()") );
    Serial.println();
#endif
    
    this->lightDataActive.visible=1;
    this->lightDataActive.ir=1;
    this->lightDataActive.uv=1;
    this->airDataActive.temperature=1;
    this->airDataActive.humidity=1;
    this->airDataActive.pressure=1;
    this->vbatActive=1;
    this->soilMoistureActive=1;
    
}
void CoolBoardSensors::begin ()
CoolBoardSensors::begin(): This method is provided to start the sensors that are on the sensor board
Definition at line 143 of file CoolBoardSensors.cpp.
References envSensor, initReadI2C(), lightSensor, and setEnvSensorSettings().
Referenced by CoolBoard::begin().
{
#if DEBUG == 1
     
    Serial.println( F("Entering CoolBoardSensors.begin()") );
    Serial.println();
#endif
    initReadI2C();
    while (!lightSensor.Begin())
    {
    
    #if DEBUG == 1
        Serial.println( F("Si1145 is not ready! 1 second") );
    #endif
        delay(1000);
    }
     
    this->setEnvSensorSettings();
    delay(10); //Make sure sensor had enough time to turn on. BME280 requires 2ms to start up.
    this->envSensor.begin();
    delay(10); //Make sure sensor had enough time to turn on. BME280 requires 2ms to start up.
#if DEBUG == 1
    
    Serial.print( F("BME280 begin answer is :") );
    Serial.println(envSensor.begin(), HEX);
    Serial.println();
#endif
}
bool CoolBoardSensors::config ()
CoolBoardSensors::config(): This method is provided to configure the sensor board : -activate 1 -deactivate 0
Returns:
true if configuration is successful, false otherwise
Definition at line 334 of file CoolBoardSensors.cpp.
References airDataActive, CoolBoardSensors::airActive::humidity, CoolBoardSensors::lightActive::ir, jsonSize, lightDataActive, CoolBoardSensors::airActive::pressure, soilMoistureActive, CoolBoardSensors::airActive::temperature, CoolBoardSensors::lightActive::uv, vbatActive, and CoolBoardSensors::lightActive::visible.
Referenced by CoolBoard::begin(), and CoolBoard::update().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardSensors.config()") );
    Serial.println();
#endif
    //read config file
    //update data
    File coolBoardSensorsConfig = SPIFFS.open("/coolBoardSensorsConfig.json", "r");
    if (!coolBoardSensorsConfig)
    {
    
    #if DEBUG == 1
        Serial.println( F("failed to read /coolBoardSensorsConfig.json") );
        Serial.println();
    
    #endif
        return(false);
    }
    else
    {
        size_t size = coolBoardSensorsConfig.size();
        // Allocate a buffer to store contents of the file.
        std::unique_ptr<char[]> buf(new char[size]);
        coolBoardSensorsConfig.readBytes(buf.get(), size);
        DynamicJsonBuffer jsonBuffer;
        JsonObject& json = jsonBuffer.parseObject(buf.get());
        if (!json.success())
        {
        
        #if DEBUG == 1
            Serial.println( F("failed to parse coolBoardSensorsConfig json") );
            Serial.println();
        
        #endif
    
            return(false);
        }
        else
        {
        #if DEBUG == 1
            Serial.println( F("Configuration Json is :") );
            json.printTo(Serial);
            Serial.println();
        
        #endif
      
            if(json["jsonSize"].success() )
            {
                this->jsonSize = json["jsonSize"];
            }
            else
            {
                this->jsonSize=this->jsonSize;
            }
            json["jsonSize"]=this->jsonSize;
            
            if(json["BME280"]["temperature"].success() )
            {
                this->airDataActive.temperature=json["BME280"]["temperature"];
            }
            else
            {
                this->airDataActive.temperature=this->airDataActive.temperature;
            }
            json["BME280"]["temperature"]=this->airDataActive.temperature;
            
            
            if(json["BME280"]["humidity"].success() )
            {
            
                this->airDataActive.humidity=json["BME280"]["humidity"];
            }
            else
            {
                this->airDataActive.humidity=this->airDataActive.humidity;
            }
            json["BME280"]["humidity"]=this->airDataActive.humidity;
            
            
            if(json["BME280"]["pressure"].success() )
            {
                this->airDataActive.pressure=json["BME280"]["pressure"];
            }
            else
            {
                this->airDataActive.pressure=this->airDataActive.pressure;
            }
            json["BME280"]["pressure"]=this->airDataActive.pressure;
            
            if(json["SI114X"]["visible"].success() )
            {
                this->lightDataActive.visible=json["SI114X"]["visible"];
            }
            else
            {
                this->lightDataActive.visible=this->lightDataActive.visible;
            }
            json["SI114X"]["visible"]=this->lightDataActive.visible;
            
            
            if(json["SI114X"]["ir"].success() )
            {
                this->lightDataActive.ir=json["SI114X"]["ir"];
            }
            else
            {
                this->lightDataActive.ir=this->lightDataActive.ir;
            }
            json["SI114X"]["ir"]=this->lightDataActive.ir;
            
            if(json["SI114X"]["uv"].success() )
            {
                this->lightDataActive.uv=json["SI114X"]["uv"];
            }
            else
            {
                this->lightDataActive.uv=this->lightDataActive.uv;
            }
            json["SI114X"]["uv"]=this->lightDataActive.uv;
            if(json["vbat"].success() )
            {
                this->vbatActive=json["vbat"];
            }
            else
            {
                this->vbatActive=this->vbatActive;
            }
            json["vbat"]=this->vbatActive;
            
            if(json["soilMoisture"].success() )
            {
                this->soilMoistureActive= json["soilMoisture"];
            }
            else
            {
                this->soilMoistureActive=this->soilMoistureActive;
            }
            json["soilMoisture"]=this->soilMoistureActive;
            coolBoardSensorsConfig.close();
            coolBoardSensorsConfig = SPIFFS.open("/coolBoardSensorsConfig.json", "w");
            if(!coolBoardSensorsConfig)
            {
            
            #if DEBUG == 1
                Serial.println( F("failed to write to /coolBoardSensorsConfig.json") );
                Serial.println();
            
            #endif
                return(false);
            }
            json.printTo(coolBoardSensorsConfig);
            coolBoardSensorsConfig.close();
            
        #if DEBUG == 1
            Serial.println( F("Saved Configuration Json is : ") );
            json.printTo(Serial);
            Serial.println();
        
        #endif
            return(true);
        }
    }
}
void CoolBoardSensors::end ()
CoolBoardSensors::end(): This method is provided to end the sensors on the sensor board
Definition at line 187 of file CoolBoardSensors.cpp.
References lightSensor.
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardSensors.end()") );
    Serial.println();
#endif
    lightSensor.DeInit();
}
int CoolBoardSensors::getJsonSize ()
CoolBoardSensors::getJsonSize(): This method is provided to get the sensor board answer size
Returns:
json data size
Definition at line 61 of file CoolBoardSensors.cpp.
References jsonSize.
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardSensors.getJsonSize()") );
    Serial.println();
    Serial.print( F("json size is : ") );
    Serial.println(this->jsonSize);
    Serial.println();
#endif
    return(this->jsonSize );
}
void CoolBoardSensors::initReadI2C ()
CoolBoardSensors::initReadI2C(): This method is provided to enable the I2C Interface on the sensor board.
Definition at line 291 of file CoolBoardSensors.cpp.
References EnI2C.
Referenced by begin(), and read().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardSensors.initReadI2C()") );
    Serial.println();
#endif
 
    digitalWrite(EnI2C,HIGH);//HIGH= I2C Enable
}
void CoolBoardSensors::printConf ()
CoolBoardSensors::printConf(): This method is provided to print the configuration to the Serial Monitor
Definition at line 529 of file CoolBoardSensors.cpp.
References airDataActive, CoolBoardSensors::airActive::humidity, CoolBoardSensors::lightActive::ir, jsonSize, lightDataActive, CoolBoardSensors::airActive::pressure, soilMoistureActive, CoolBoardSensors::airActive::temperature, CoolBoardSensors::lightActive::uv, vbatActive, and CoolBoardSensors::lightActive::visible.
Referenced by CoolBoard::begin().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardSensors.printConf()") );
    Serial.println();
#endif
    Serial.println("Sensors Configuration : ");
    
    Serial.print("json size : ");
    Serial.println(this->jsonSize);
    Serial.print("airDataActive.temperature : ");
    Serial.println(this->airDataActive.temperature);
    Serial.print("airDataActive.humidity : ");
    Serial.println(airDataActive.humidity);
    Serial.print("airDataActive.pressure : ");
    Serial.println(airDataActive.pressure);
    Serial.print("lightDataActive.visible : ");
    Serial.println(lightDataActive.visible);
    Serial.print("lightDataActive.ir : ");
    Serial.println(lightDataActive.ir);
    Serial.print("lightDataActive.uv : ");
    Serial.println(lightDataActive.uv);
    
    Serial.print("vbatActive : ");
    Serial.println(vbatActive);
    Serial.print("soilMoitureActive : ");
    Serial.println(soilMoistureActive);
    Serial.println();
}
String CoolBoardSensors::read ()
CoolBoardSensors::read(): This method is provided to return the data read by the sensor board
Returns:
a json string containing the sensors data
Definition at line 208 of file CoolBoardSensors.cpp.
References airDataActive, envSensor, CoolBoardSensors::airActive::humidity, initReadI2C(), CoolBoardSensors::lightActive::ir, jsonSize, lightDataActive, lightSensor, CoolBoardSensors::airActive::pressure, readMoisture(), readVBat(), soilMoistureActive, CoolBoardSensors::airActive::temperature, CoolBoardSensors::lightActive::uv, vbatActive, and CoolBoardSensors::lightActive::visible.
Referenced by CoolBoard::readSensors().
{
#if DEBUG == 1
    
    Serial.println( F("Entering CoolBoardSensors.read()") );
    Serial.println();
#endif
    String data;
    DynamicJsonBuffer jsonBuffer(jsonSize) ;
    JsonObject& root = jsonBuffer.createObject();
    
    initReadI2C();
    delay(100);
    //light data
    if(lightDataActive.visible)
    {
        root["visibleLight"] =lightSensor.ReadVisible() ;
    }
    
    if(lightDataActive.ir)
    {
        root["infraRed"] = lightSensor.ReadIR();
    }
    if(lightDataActive.uv)
    {
        float tempUV = (float)lightSensor.ReadUV()/100 ;
        root["ultraViolet"] = tempUV;
    }
    
    //BME280 data
    if(airDataActive.pressure)
    {
        root["Pressure"] =envSensor.readFloatPressure();
    }
    
        
    if(airDataActive.humidity)
    {
        root["Humidity"] =envSensor.readFloatHumidity() ;
    }
    
    if(airDataActive.temperature)
    {
        root["Temperature"]=envSensor.readTempC();
    }
    
    //Vbat
    if(vbatActive)
    {
        root["Vbat"]=this->readVBat();
    }
    
    //earth Moisture
    if(soilMoistureActive)
    {
        root["soilMoisture"]=this->readMoisture();
    }
    
    
    root.printTo(data);
#if DEBUG == 1
    Serial.println( F("CoolBoardSensors data is :") );
    root.printTo(Serial);
    Serial.println();
#endif
    return(data);
    
}
float CoolBoardSensors::readMoisture ()
CoolBoardSensors::readMoisture(): This method is provided to red the Soil Moisture
Returns:
a float represnting the soil moisture
Definition at line 655 of file CoolBoardSensors.cpp.
References AnMplex, and EnMoisture.
Referenced by read().
{
#if DEBUG == 1
    
    Serial.println( F("Entering CoolBoardSensors.readMoisture()") );
    Serial.println();
    
#endif
    digitalWrite(EnMoisture, LOW); //enable moisture sensor and waith a bit
    digitalWrite(AnMplex, HIGH); //enable analog Switch to get the moisture
    delay(2000);
    int val = analogRead(A0); //read the value form the moisture sensor
    float result = (float)map(val, 0, 890, 0, 100);
    digitalWrite(EnMoisture, HIGH); //disable moisture sensor for minimum wear
    
#if DEBUG == 1
    Serial.println( F("Soil Moisture is : ") );
    Serial.println(result);
    Serial.println();
#endif
    return (result);
}
float CoolBoardSensors::readVBat ()
CoolBoardSensors::readVBat(): This method is provided to read the Battery Voltage.
Returns:
a float representing the battery voltage
Definition at line 618 of file CoolBoardSensors.cpp.
References AnMplex.
Referenced by read().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardSensors.readVBat()") );
    Serial.println();
#endif
    digitalWrite(this->AnMplex, LOW); //Enable Analog Switch to get the batterie tension
    
    delay(200);
    
    int raw = analogRead(A0); //read in batterie tension
    
    float val = 6.04 / 1024 * raw; //convert it apprimatly right tension in volts
    
#if DEBUG == 1
    Serial.println( F("Vbat is : ") );
    Serial.println(val);
    Serial.println();
#endif
    return (val);
}
void CoolBoardSensors::setEnvSensorSettings (uint8_t commInterface = I2C_MODE, uint8_t I2CAddress = 0x76, uint8_t runMode = 3, uint8_t tStandby = 0, uint8_t filter = 0, uint8_t tempOverSample = 1, uint8_t pressOverSample = 1, uint8_t humidOverSample = 1)
CoolBoardSensors::setEnvSensorSetting(): This method is provided to set the enviornment sensor settings , if argument is ommitted , default value will be assigned
Definition at line 578 of file CoolBoardSensors.cpp.
References envSensor.
Referenced by begin().
{
#if DEBUG == 1
    
    Serial.println( F("Entering CoolBoardSensors.setEnvSensorSettings()") );
    Serial.println();
#endif
  
    this->envSensor.settings.commInterface = commInterface;
    this->envSensor.settings.I2CAddress = I2CAddress;
    this->envSensor.settings.runMode = runMode;
    this->envSensor.settings.tStandby = tStandby;
    this->envSensor.settings.filter = filter;
    this->envSensor.settings.tempOverSample = tempOverSample;
    this->envSensor.settings.pressOverSample = pressOverSample;
    this->envSensor.settings.humidOverSample = humidOverSample;
}
void CoolBoardSensors::setJsonSize (int jsonSize)
CoolBoardSensors::setJsonSize( JSON size): This method is provided to set the sensor board answer size
Definition at line 82 of file CoolBoardSensors.cpp.
References jsonSize.
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardSensors.setJsonSize()") );
    Serial.println();
    Serial.print( F("old json Size is : ") );
    Serial.println(this->jsonSize);
#endif
        
    this->jsonSize=jsonSize;
#if DEBUG == 1
    
    Serial.print( F("new json Size is : ") );
    Serial.println(this->jsonSize);
#endif
    
}
void CoolBoardSensors::stopReadI2C ()
CoolBoardSensors::stopReadI2C(): This method is provided to disable the I2C Interface on the sensor board
Definition at line 310 of file CoolBoardSensors.cpp.
References EnI2C.
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoardSensors.stopReadI2C()") );
    Serial.println();
#endif
    digitalWrite(EnI2C,LOW);//HIGH= I2C Enable
}
Member Data Documentation
struct CoolBoardSensors::airActive CoolBoardSensors::airDataActive [private]
Referenced by allActive(), config(), printConf(), and read().
const int CoolBoardSensors::AnMplex = 12 [private]
Definition at line 98 of file CoolBoardSensors.h.
Referenced by CoolBoardSensors(), readMoisture(), and readVBat().
const int CoolBoardSensors::EnI2C = 5 [private]
Definition at line 99 of file CoolBoardSensors.h.
Referenced by CoolBoardSensors(), initReadI2C(), and stopReadI2C().
const int CoolBoardSensors::EnMoisture = 13 [private]
Definition at line 97 of file CoolBoardSensors.h.
Referenced by CoolBoardSensors(), and readMoisture().
BME280 CoolBoardSensors::envSensor
Definition at line 77 of file CoolBoardSensors.h.
Referenced by begin(), read(), and setEnvSensorSettings().
int CoolBoardSensors::jsonSize =500 [private]
Definition at line 104 of file CoolBoardSensors.h.
Referenced by config(), getJsonSize(), printConf(), read(), and setJsonSize().
struct CoolBoardSensors::lightActive CoolBoardSensors::lightDataActive [private]
Referenced by allActive(), config(), printConf(), and read().
SI114X CoolBoardSensors::lightSensor = SI114X()
Definition at line 75 of file CoolBoardSensors.h.
Referenced by begin(), end(), and read().
byte CoolBoardSensors::soilMoistureActive =0 [private]
Definition at line 102 of file CoolBoardSensors.h.
Referenced by allActive(), config(), printConf(), and read().
byte CoolBoardSensors::vbatActive =0 [private]
Definition at line 101 of file CoolBoardSensors.h.
Referenced by allActive(), config(), printConf(), and read().
Author
Generated automatically by Doxygen for CoolAPI from the source code.