CoolBoard
NAME
CoolBoard - This class manages the CoolBoard and all of Its functions.
SYNOPSIS
#include <CoolBoard.h>
Public Member Functions
CoolBoard ()
void begin ()
bool config ()
void update (const char *answer)
void offLineMode ()
void onLineMode ()
int connect ()
int isConnected ()
unsigned long getLogInterval ()
void printConf ()
void sleep (unsigned long interval)
String readSensors ()
void initReadI2C ()
void stopReadI2C ()
String userData ()
Private Attributes
CoolFileSystem fileSystem
CoolBoardSensors coolBoardSensors
CoolBoardLed coolBoardLed
CoolTime rtc
CoolWifi wifiManager
CoolMQTT mqtt
Jetpack jetPack
Irene3000 irene3000
ExternalSensors externalSensors
bool userActive =0
bool ireneActive =0
bool jetpackActive =0
bool externalSensorsActive =0
bool sleepActive =0
unsigned long logInterval =1
int serverTimeOut =180
String data =''
String answer =''
const int EnI2C = 5
Detailed Description
This class manages the CoolBoard and all of Its functions.
Definition at line 33 of file CoolBoard.h.
Constructor & Destructor Documentation
CoolBoard::CoolBoard ()
CoolBoard::CoolBoard(): This Constructor is provided to start the I2C interface and Init the different used pins
Definition at line 34 of file CoolBoard.cpp.
References EnI2C.
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoard Constructor") );
    Serial.println();
#endif
    
    Wire.begin(2, 14); //I2C init
    pinMode(EnI2C, OUTPUT); //Declare I2C Enable pin
}
Member Function Documentation
void CoolBoard::begin ()
CoolBoard::begin(): This method is provided to configure and start the used CoolKit Parts. It also starts the first connection try If Serial is enabled,it prints the configuration of the used parts.
Definition at line 59 of file CoolBoard.cpp.
References Jetpack::begin(), CoolMQTT::begin(), ExternalSensors::begin(), CoolBoardSensors::begin(), CoolWifi::begin(), CoolTime::begin(), Irene3000::begin(), CoolBoardLed::blink(), Jetpack::config(), ExternalSensors::config(), CoolWifi::config(), CoolMQTT::config(), CoolTime::config(), Irene3000::config(), CoolBoardSensors::config(), connect(), coolBoardLed, coolBoardSensors, externalSensors, externalSensorsActive, CoolBoardLed::fadeOut(), initReadI2C(), irene3000, ireneActive, jetPack, jetpackActive, mqtt, CoolBoardLed::printConf(), Jetpack::printConf(), ExternalSensors::printConf(), Irene3000::printConf(), CoolMQTT::printConf(), CoolTime::printConf(), CoolBoardSensors::printConf(), CoolWifi::printConf(), rtc, wifiManager, and CoolBoardLed::write().
{
#if DEBUG == 1
    Serial.println( F("Starting the CoolBoard ") );
    Serial.println( F("Entering CoolBoard.begin() ") );
    Serial.println();
#endif
    coolBoardLed.printConf();
    delay(100);
    
    coolBoardLed.write(255,128,0);//orange
    this->initReadI2C();
    coolBoardSensors.config();
    coolBoardSensors.begin();
    coolBoardSensors.printConf();
    delay(100);
    
    wifiManager.config();
    wifiManager.begin();
    wifiManager.printConf();
    delay(100);
    mqtt.config();
    mqtt.begin();
    mqtt.printConf();
    delay(100);
    if (jetpackActive)
    {
        jetPack.config();
        jetPack.begin();
        jetPack.printConf();
        delay(100);
    }
    if (ireneActive)
    {
        irene3000.config();
        irene3000.begin();
        irene3000.printConf();
        delay(100);
    }
    if (externalSensorsActive)
    {
        externalSensors.config();
        externalSensors.begin();
        externalSensors.printConf();
        delay(100);
    }
    
    coolBoardLed.fadeOut(255,128,0,0.5);//orange
    this->connect();
    delay(100);
    rtc.config();
    rtc.begin();
    rtc.printConf();
    delay(100);
    
    coolBoardLed.blink(0,255,0,0.5);//green
}
bool CoolBoard::config ()
CoolBoard::config(): This method is provided to configure the CoolBoard : -log interval -irene3000 activated/deactivated -jetpack activated/deactivated -external Sensors activated/deactivated -mqtt server timeout
Returns:
true if configuration is done, false otherwise
Definition at line 619 of file CoolBoard.cpp.
References CoolBoardLed::begin(), CoolFileSystem::begin(), CoolBoardLed::blink(), CoolBoardLed::config(), coolBoardLed, externalSensorsActive, CoolBoardLed::fadeIn(), CoolBoardLed::fadeOut(), fileSystem, ireneActive, jetpackActive, logInterval, serverTimeOut, sleepActive, CoolBoardLed::strobe(), and userActive.
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoard.config() ") );
    Serial.println();
#endif
    //open file system
    fileSystem.begin();
    
    //start the led
    coolBoardLed.config();
    coolBoardLed.begin();
    coolBoardLed.fadeIn(243,171,46,0.5);//shade of orange
    
    //open configuration file
    File configFile = SPIFFS.open("/coolBoardConfig.json", "r");
    
    if (!configFile)
    {
    
    #if DEBUG == 1
        Serial.println( F("failed to read /coolBoardConfig.json ") );
    #endif
        coolBoardLed.blink(255,0,0,0.5);//shade of red
        return(false);
    }
    else
    {
        size_t size = configFile.size();
        // Allocate a buffer to store contents of the file.
        std::unique_ptr < char[] > buf(new char[size]);
        configFile.readBytes(buf.get(), size);
        DynamicJsonBuffer jsonBuffer;
        JsonObject & json = jsonBuffer.parseObject(buf.get());
        if (!json.success())
        {
        
        #if DEBUG == 1
            Serial.println( F("failed to parse CoolBoard Config json object ") );
    
        #endif
            coolBoardLed.blink(255,0,0,0.5);//shade of red
            return(false);
        }
        else
        {
        
        #if DEBUG == 1
            
            Serial.println( F("configuration json : ") );
            json.printTo(Serial);
            Serial.println();
            
            Serial.print(F("jsonBuffer size : "));
            Serial.print(jsonBuffer.size());
            Serial.println();
        #endif
            
            //parsing userActive Key
            if (json["userActive"].success())
            {
                this -> userActive = json["userActive"];
            }
            else
            {
                this -> userActive = this -> userActive;
            }
            json["userActive"] = this -> userActive;
            //parsing logInterval key
            if (json["logInterval"].success())
            {
                this -> logInterval = json["logInterval"];
            }
            else
            {
                this -> logInterval = this -> logInterval;
            }
            json["logInterval"] = this -> logInterval;
            
            //parsing ireneActive key
            if (json["ireneActive"].success())
            {
                this -> ireneActive = json["ireneActive"];
            }
            else
            {
                this -> ireneActive = this -> ireneActive;
            }
            json["ireneActive"] = this -> ireneActive;
            
            //parsing jetpackActive key
            if (json["jetpackActive"].success())
            {
                this -> jetpackActive = json["jetpackActive"];
            }
            else
            {
                this -> jetpackActive = this -> jetpackActive;
            }
            json["jetpackActive"] = this -> jetpackActive;
            //parsing externalSensorsActive key
            if (json["externalSensorsActive"].success())
            {
                this -> externalSensorsActive = json["externalSensorsActive"];
            }
            else
            {
                this -> externalSensorsActive = this -> externalSensorsActive;
            }
            json["externalSensorsActive"] = this -> externalSensorsActive;
            //parsing serverTimeOut key
            if (json["serverTimeOut"].success())
            {
                this -> serverTimeOut = json["serverTimeOut"];
            }
            else
            {
                this -> serverTimeOut = this -> serverTimeOut;
            }
            json["serverTimeOut"] = this -> serverTimeOut;
            
            //parsing sleepActive key
            if (json["sleepActive"].success())
            {
                this -> sleepActive = json["sleepActive"];
            }
            else
            {
                this -> sleepActive = this -> sleepActive;
            }
            json["sleepActive"] = this -> sleepActive;
            //saving the current/correct configuration
            configFile.close();
            configFile = SPIFFS.open("/coolBoardConfig.json", "w");
            if (!configFile)
            {
            
            #if DEBUG == 1
                Serial.println( F("failed to write to /coolBoardConfig.json") );
                Serial.println();
            
            #endif
                coolBoardLed.blink(255,0,0,0.5);//shade of red
                return(false);
            }
            json.printTo(configFile);
            configFile.close();
            return(true);
        }
    }
    coolBoardLed.strobe(243,171,46,0.5);//shade of orange
    
    coolBoardLed.fadeOut(243,171,46,0.5);//shade of orange
}
int CoolBoard::connect ()
CoolBoard::connect(): This method is provided to manage the network connection and the mqtt connection.
Returns:
mqtt client state
Definition at line 188 of file CoolBoard.cpp.
References CoolBoardLed::blink(), CoolMQTT::connect(), CoolWifi::connect(), coolBoardLed, getLogInterval(), mqtt, CoolWifi::state(), CoolMQTT::state(), wifiManager, and CoolBoardLed::write().
Referenced by begin(), and offLineMode().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoard.connect ") );
    Serial.println();
    Serial.println( F("Connecting the CoolBoard ") );
    delay(100);
#endif
    coolBoardLed.write(0,0,255);//blue
    
            
    
#if DEBUG == 1
    Serial.println( F("Launching CoolWifi") );
    Serial.println();
#endif
    wifiManager.connect();
    delay(100);
    //only attempt MQTT connection when Wifi is Connected
    if (wifiManager.state() == WL_CONNECTED)
    {
    #if DEBUG == 1
    
        Serial.println( F("Launching mqtt.connect()") );
        Serial.println();
    
    #endif
        //logInterval in seconds
        mqtt.connect(this -> getLogInterval());
        delay(100);
    }
    
        
    
    
#if DEBUG == 1
    Serial.println( F("mqtt state is :") );
    Serial.println(mqtt.state());
    Serial.println();
    delay(100);
#endif
    coolBoardLed.blink(0,0,255,0.5);//blue
    return(mqtt.state());
}
unsigned long CoolBoard::getLogInterval ()
CoolBoard::getLogInterval(): This method is provided to get the log interval
Returns:
interval value in s
Definition at line 964 of file CoolBoard.cpp.
References logInterval.
Referenced by connect(), and onLineMode().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoard.getLogInterval() ") );
    Serial.println();
    Serial.println( F("log Interval is :") );
    Serial.println(logInterval);
    Serial.println();
#endif
    return(this -> logInterval);
}
void CoolBoard::initReadI2C ()
CoolBoard::initReadI2C(): This method is provided to enable the I2C Interface.
Definition at line 1057 of file CoolBoard.cpp.
References EnI2C.
Referenced by begin(), and readSensors().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoard.initReadI2C()") );
    Serial.println();
#endif
 
    digitalWrite(EnI2C,HIGH);//HIGH= I2C Enable
}
int CoolBoard::isConnected ()
CoolBoard::isConnected()
This method is provided to check if the card is connected to Wifi and MQTT
Returns:
0 : connected -1: Wifi Not Connected -2: MQTT Not Connected
Definition at line 139 of file CoolBoard.cpp.
References mqtt, CoolMQTT::state(), CoolWifi::state(), and wifiManager.
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoard.isConnected ") );
    Serial.println();
#endif
    if (wifiManager.state() != WL_CONNECTED)
    {
    #if DEBUG == 1
    
        Serial.println(F("Wifi Not Connected"));
        Serial.println(F("Wifi State is "));
        Serial.println(wifiManager.state());
        
    #endif
        return(-1);
    }
    
    if(mqtt.state() != 0)
    {
    
    #if DEBUG==1
        
        Serial.println( F("MQTT not Connected"));
        Serial.println( F("mqtt state is :") );
        Serial.println(mqtt.state());
    
    #endif
    }
    
    return(0);
}
void CoolBoard::offLineMode ()
CoolBoard::offlineMode(): This method is provided to manage the offLine mode: -read sensors -do actions -save data in the file system -if there is WiFi but no Internet : make data available over AP -if there is no connection : retry to connect
Definition at line 482 of file CoolBoard.cpp.
References CoolBoardLed::blink(), connect(), CoolWifi::connectAP(), coolBoardLed, data, Jetpack::doAction(), CoolBoardLed::fade(), CoolBoardLed::fadeIn(), CoolBoardLed::fadeOut(), fileSystem, jetPack, jetpackActive, mqtt, readSensors(), CoolFileSystem::saveSensorData(), CoolWifi::state(), CoolMQTT::state(), userActive, userData(), and wifiManager.
{
    coolBoardLed.fade(51,100,50,0.5);//dark shade of green
#if DEBUG == 1
    
    Serial.println( F("Entering off line mode ") );
    
#endif
    //read user data if user is active
    if(userActive)
    {
        coolBoardLed.fadeIn(245,237,27,0.5);//shade of yellow
    #if DEBUG == 1
        
        Serial.println( F("User is Active") );
        Serial.println( F("Collecting User's data ( mac,username,timeStamp )") );
        Serial.println();
    #endif
        coolBoardLed.blink(245,237,27,0.5);//shade of yellow
        //reading user data
        data=this->userData();//{"":"","":"","",""}
        //formatting json
        data.setCharAt( data.lastIndexOf('}') , ',');//{"":"","":"","","",
        
                
        //read sensors data
    #if DEBUG == 1
        Serial.println( F("Collecting sensors data ") );
        Serial.println();
    #endif
        data+=this->readSensors();//{"":"","":"","","",{.......}
        
        //formatting json correctly
        data.remove(data.lastIndexOf('{'), 1);//{"":"","":"","","",.......}
        coolBoardLed.fadeOut(245,237,27,0.5);//shade of yellow
                
    }
    else
    {
        //read sensors data
    #if DEBUG == 1
        Serial.println( F("Collecting sensors data ") );
        Serial.println();
    #endif
        coolBoardLed.fade(190,100,150,0.5);//shade of violet
        data=this->readSensors();//{..,..,..}
    }
    coolBoardLed.fade(51,100,50,0.5);//dark shade of green
    //do action
    if (jetpackActive)
    {
    #if DEBUG == 1
        Serial.println( F("jetpack is Active ") );
        Serial.println( F("jetpack doing action ") );
        Serial.println();
    
    #endif
        coolBoardLed.fade(100,100,150,0.5);//dark shade of blue
    
        jetPack.doAction( data.c_str() );
    }
    
    coolBoardLed.fade(51,100,50,0.5);//dark shade of green
    
    //saving data in the file system
    
    fileSystem.saveSensorData( data.c_str() );
    coolBoardLed.fadeOut(51,100,50,0.5);//dark shade of green
    //case we have wifi but no internet
    if( (wifiManager.state() == WL_CONNECTED) && ( mqtt.state()!=0 ) )
    {
    
    #if DEBUG == 1
        
        Serial.println(F("there is Wifi but no Internet"));
        Serial.println(F("lunching AP to check saved files"));
        Serial.println(F("and Add new WiFi if needed"));
    
    #endif
        
        wifiManager.connectAP();
        
    }
    
    //case we have no connection at all
    if( wifiManager.state() != WL_CONNECTED )
    {
    
    #if DEBUG == 1
        
        Serial.println(F("there is No Wifi "));
        Serial.println(F("retrying to connect"));
    
    #endif
        
        this->connect();//nomad case : just run wifiMulti
                //normal case : run wifiMulti+AP
        
    }
}
void CoolBoard::onLineMode ()
CoolBoard::onLineMode(): This method is provided to manage the online mode: -update clock -read sensor -do actions -publish data -read answer -update config
Definition at line 256 of file CoolBoard.cpp.
References answer, CoolBoardLed::blink(), coolBoardLed, data, Jetpack::doAction(), CoolBoardLed::fade(), CoolBoardLed::fadeIn(), CoolBoardLed::fadeOut(), fileSystem, getLogInterval(), CoolFileSystem::getSensorSavedData(), CoolFileSystem::isDataSaved(), jetPack, jetpackActive, mqtt, CoolMQTT::mqttLoop(), CoolMQTT::publish(), CoolMQTT::read(), readSensors(), rtc, sleep(), sleepActive, CoolBoardLed::strobe(), CoolTime::update(), update(), userActive, and userData().
{
    coolBoardLed.fadeIn(128,255,50,0.5);//shade of green
#if DEBUG == 1
    Serial.println( F("Entering CoolBoard.onLineMode() ") );
    Serial.println();
#endif
    data="";
    answer="";
    //send saved data if any
    if(fileSystem.isDataSaved())
    {
        coolBoardLed.fadeIn(128,128,255,0.5);//shade of blue
    #if DEBUG == 1
        Serial.println( F("There is data saved on the File System") );
        Serial.println( F("Sending saved data over MQTT ") );
        Serial.println();
    
    #endif
        coolBoardLed.strobe(128,128,255,0.5);//shade of blue
        mqtt.publish("sending saved data");
        mqtt.mqttLoop();
        
        int size=0;
        std::unique_ptr<String[]> savedData(std::move(fileSystem.getSensorSavedData(size)));//{..,..,..}
        int i=0;
        //loop through the array
        while(i<size)
        {
            //formatting data:
        
            String jsonData = "{\"state\":{\"reported\":";
            jsonData += savedData[i]; // {"state":{"reported":{..,..,..,..,..,..,..,..}
            jsonData += " } }"; // {"state":{"reported":{..,..,..,..,..,..,..,..} } }
        #if DEBUG == 1
            Serial.println(F("Size is : "));
            Serial.println(size);
            Serial.print(F("sending line N°"));
            Serial.println(i);
            Serial.println(jsonData);
            Serial.println();
        #endif
            coolBoardLed.strobe(128,128,255,0.5);//shade of blue
        
            mqtt.publish( jsonData.c_str() );
            mqtt.mqttLoop();
        
            coolBoardLed.fadeOut(128,128,255,0.5);//shade of blue
            
            i++;
            yield();
        }
    #if DEBUG == 1
        Serial.println( F("Saved data sent ") );
        Serial.println();
    
    #endif
    }
    coolBoardLed.blink(128,255,50,0.5);//shade of green
    //clock update
    rtc.update();
    //read user data if user is active
    if(userActive)
    {
        coolBoardLed.fadeIn(245,237,27,0.5);//shade of yellow
    
    #if DEBUG == 1
        Serial.println( F("User is Active") );
        Serial.println( F("Collecting User's data ( mac,username,timeStamp )") );
        Serial.println();
    
    #endif
        coolBoardLed.blink(245,237,27,0.5);//shade of yellow
        //reading user data
        data=this->userData();//{"":"","":"","",""}
        //formatting json
        data.setCharAt( data.lastIndexOf('}') , ',');//{"":"","":"","","",
                
        //read sensors data
    #if DEBUG == 1
        Serial.println( F("Collecting sensors data ") );
        Serial.println();
    
    #endif
        data+=this->readSensors();//{"":"","":"","","",{.......}
        //formatting json correctly
        data.remove(data.lastIndexOf('{'), 1);//{"":"","":"","","",.......}
        
        coolBoardLed.fadeOut(245,237,27,0.5);//shade of yellow
                
    }
    else
    {
        //read sensors data
    #if DEBUG == 1
        Serial.println( F("Collecting sensors data ") );
        Serial.println();
    
    #endif
        coolBoardLed.fade(190,100,150,0.5);//shade of violet
        data=this->readSensors();//{..,..,..}
    }
    
    //do action
    if (jetpackActive)
    {
    
    #if DEBUG ==1
        Serial.println( F("jetpack is Active ") );
        Serial.println( F("jetpack doing action ") );
        Serial.println();
    #endif
        coolBoardLed.fade(100,100,150,0.5);//dark shade of blue
        jetPack.doAction(data.c_str());
    }
    
    coolBoardLed.fadeIn(128,255,50,0.5);//shade of green
    //formatting data:
    String jsonData = "{\"state\":{\"reported\":";
    jsonData += data; // {"state":{"reported":{..,..,..,..,..,..,..,..}
    jsonData += " } }"; // {"state":{"reported":{..,..,..,..,..,..,..,..} } }
    
    //mqtt client loop to allow data handling
    mqtt.mqttLoop();
    coolBoardLed.blink(128,255,50,0.5);//shade of green
    //read mqtt answer
    answer = mqtt.read();
#if DEBUG == 1
    Serial.println( F("checking if there's an MQTT message ") );
    Serial.println( F("answer is : ") );
    Serial.println(answer);
    Serial.println();
#endif
    coolBoardLed.fadeOut(128,255,50,0.5);//shade of green
    //check if the configuration needs update
    //and update it if needed
    this -> update(answer.c_str());
    
    coolBoardLed.fadeIn(128,255,50,0.5);//shade of green
    //publishing data
    if( this->sleepActive==0 )
    {
        coolBoardLed.strobe(255,0,230,0.5);//shade of pink
        
        //logInterval in seconds
        mqtt.publish( jsonData.c_str(), this->getLogInterval() );
        mqtt.mqttLoop();
    
    }
    else
    {
        coolBoardLed.strobe(230,255,0,0.5);//shade of yellow
        mqtt.publish(jsonData.c_str());
        mqtt.mqttLoop();
        answer = mqtt.read();
        this ->update(answer.c_str());
        //logInterval in seconds
        this->sleep( this->getLogInterval() ) ;
    }
    coolBoardLed.fadeOut(128,255,50,0.5);//shade of green
    mqtt.mqttLoop();
    //read mqtt answer
    answer = mqtt.read();
    this -> update(answer.c_str());
    coolBoardLed.blink(128,255,50,0.5);//shade of green
}
void CoolBoard::printConf ()
CoolBoard::printConf(): This method is provided to print the configuration to the Serial Monitor.
Definition at line 806 of file CoolBoard.cpp.
References externalSensorsActive, ireneActive, jetpackActive, logInterval, serverTimeOut, sleepActive, and userActive.
{
#if DEBUG == 1
    
    Serial.println( F("Entering CoolBoard.printConf() ") );
    Serial.println();
#endif
    Serial.println("Printing Cool Board Configuration ");
    Serial.print("log interval : ");
    Serial.println(this->logInterval);
    Serial.print("irene active : ");
    Serial.println(this->ireneActive);
    Serial.print("jetpack active : ");
    Serial.println(this->jetpackActive);
    Serial.print("external sensors active : ");
    Serial.println(this->externalSensorsActive);
    Serial.print("access point timeOut : ");
    Serial.println(this->serverTimeOut);
    Serial.print("sleept active : ");
    Serial.println(this->sleepActive);
    Serial.print("user active : ");
    Serial.println(this->userActive);
    Serial.println();
}
String CoolBoard::readSensors ()
CoolBoard::readSensors(): This method is provided to read and format all the sensors data in a single json.
Returns:
json string of all the sensors read.
Definition at line 988 of file CoolBoard.cpp.
References coolBoardLed, coolBoardSensors, externalSensors, externalSensorsActive, CoolBoardLed::fadeIn(), CoolBoardLed::fadeOut(), CoolTime::getTimeDate(), initReadI2C(), irene3000, ireneActive, ExternalSensors::read(), CoolBoardSensors::read(), Irene3000::read(), rtc, and CoolBoardLed::strobe().
Referenced by offLineMode(), and onLineMode().
{
    coolBoardLed.fadeIn(128,255,0,0.5);//light shade of green
                
#if DEBUG == 1
    Serial.println( F("Entering CoolBoard.readSensors()") );
    Serial.println();
#endif
    coolBoardLed.strobe(128,255,0,0.5);//light shade of green
    String sensorsData;
    
    this->initReadI2C();
    sensorsData = coolBoardSensors.read(); // {..,..,..}
    
    if (externalSensorsActive)
    {
        sensorsData += externalSensors.read(); // {..,..,..}{..,..}
        sensorsData.setCharAt(sensorsData.lastIndexOf('}'), ','); // {..,..,..}{..,..,
        sensorsData.setCharAt(sensorsData.lastIndexOf('{'), ','); // {..,..,..},..,..,
        sensorsData.remove(sensorsData.lastIndexOf('}'), 1); // {..,..,..,..,..,
        sensorsData.setCharAt(sensorsData.lastIndexOf(','), '}'); // {..,..,..,..,..}
    }
    if (ireneActive)
    {
        sensorsData += irene3000.read(); // {..,..,..,..,..}{..,..,..}
        sensorsData.setCharAt(sensorsData.lastIndexOf('}'), ','); // {..,..,..,..,..}{..,..,..,
        sensorsData.setCharAt(sensorsData.lastIndexOf('{'), ','); // {..,..,..,..,..},..,..,..,
        sensorsData.remove(sensorsData.lastIndexOf('}'), 1); // {..,..,..,..,..,..,..,..,
        sensorsData.setCharAt(sensorsData.lastIndexOf(','), '}'); // {..,..,..,..,..,..,..,..}
        
        
    }
    //getting Hour:
    tmElements_t tm;
    tm=rtc.getTimeDate();
    
    //adding Hour
    sensorsData.remove(sensorsData.lastIndexOf('}'), 1); // {..,..,..,..,..,..,..,..,
    sensorsData+=",\"hour\":";
    sensorsData+=tm.Hour;
    sensorsData+="}";
    
#if DEBUG == 1
    Serial.println();
    Serial.println( F("sensors data is ") );
    Serial.println(sensorsData);
    Serial.println();
#endif
    coolBoardLed.fadeOut(128,255,0,0.5);//light shade of green
    return(sensorsData);
}
void CoolBoard::sleep (unsigned long interval)
CoolBoard::sleep(int interval): This method is provided to allow the board to enter deepSleep mode for a period of time equal to interval in s
Definition at line 1144 of file CoolBoard.cpp.
Referenced by onLineMode().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoard.sleep() ") );
    Serial.print( F("going to sleep for ") );
    Serial.print(interval);
    Serial.println(F("s") );
    Serial.println();
#endif
    //interval is in seconds , interval*1000*1000 in µS
    ESP.deepSleep ( ( interval * 1000 * 1000 ), WAKE_RF_DEFAULT) ;
}
void CoolBoard::stopReadI2C ()
CoolBoard::stopReadI2C(): This method is provided to disable the I2C Interface.
Definition at line 1076 of file CoolBoard.cpp.
References EnI2C.
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoard.stopReadI2C()") );
    Serial.println();
#endif
    digitalWrite(EnI2C,LOW);//LOW= I2C Disable
}
void CoolBoard::update (const char * answer)
CoolBoard::update(mqtt answer): This method is provided to handle the configuration update of the different parts
Definition at line 850 of file CoolBoard.cpp.
References coolBoardLed, CoolBoardLed::fadeIn(), CoolBoardLed::fadeOut(), fileSystem, mqtt, CoolMQTT::mqttLoop(), CoolMQTT::publish(), CoolBoardLed::strobe(), and CoolFileSystem::updateConfigFiles().
Referenced by onLineMode().
{
    coolBoardLed.fadeIn(153,76,0,0.5);//shade of brown
#if DEBUG == 1
    Serial.println( F("Entering CoolBoard.update() ") );
    Serial.println();
    Serial.println( F("message is : ") );
    Serial.println(answer);
    Serial.println();
#endif
    DynamicJsonBuffer jsonBuffer;
    JsonObject & root = jsonBuffer.parseObject(answer);
    JsonObject & stateDesired = root["state"];
#if DEBUG == 1
    Serial.println( F("root json : ") );
    root.printTo(Serial);
    Serial.println();
    Serial.println(F("stateDesired json : "));
    stateDesired.printTo(Serial);
    Serial.println();
    
    Serial.print(F("jsonBuffer size : "));
    Serial.println(jsonBuffer.size());
#endif
    if (stateDesired.success())
    {
    
    #if DEBUG == 1
        Serial.println( F("update message parsing : success") );
        Serial.println();
    
    #endif
            String answerDesired;
        
            stateDesired.printTo(answerDesired);
            
        #if DEBUG == 1
        
            Serial.println( F("update is ok ") );
            Serial.println( F("desired update is : ") );
            Serial.println(answerDesired);
            Serial.println("json size is : ");
            Serial.println(jsonBuffer.size() ) ;
            Serial.println();
        
        #endif
            //saving the new configuration
            fileSystem.updateConfigFiles(answerDesired);
                //answering the update msg:
            //reported = received configuration
            //desired=null
        
            String updateAnswer;
            String tempString;
            
            stateDesired.printTo(tempString);
            updateAnswer="{\"state\":{\"reported\":";
            updateAnswer+=tempString;
            updateAnswer+=",\"desired\":null}}";
        #if DEBUG == 1
            Serial.println( F("preparing answer message ") );
            Serial.println();
            Serial.println( F("updateAnswer : ") );
            Serial.println(updateAnswer);
        
        #endif
            mqtt.publish(updateAnswer.c_str());
            
            mqtt.mqttLoop();
            delay(10);
            
            //restart the esp to apply the config
            ESP.restart();
    }
    else
    {
    
    #if DEBUG == 1
        Serial.println( F("Failed to parse update message( OR no message received )") );
        Serial.println();
    
    #endif
    
    }
    coolBoardLed.strobe(153,76,0,0.5);//shade of brown
    coolBoardLed.fadeOut(153,76,0,0.5);//shade of brown
}
String CoolBoard::userData ()
CoolBoard::userData(): This method is provided to return the user's data.
Returns:
json string of the user's data
Definition at line 1097 of file CoolBoard.cpp.
References CoolTime::getESDate(), CoolMQTT::getUser(), mqtt, and rtc.
Referenced by offLineMode(), and onLineMode().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolBoard.userData() ") );
    Serial.println();
#endif
    String tempMAC = WiFi.macAddress();
    tempMAC.replace(":", "");
    String userJson = "{\"user\":\"";
    userJson += mqtt.getUser();
    userJson += "\",\"timestamp\":\"";
    userJson += rtc.getESDate(); // "timestamp":"20yy-mm-ddThh:mm:ssZ"
    userJson += "\",\"mac\":\"";
    userJson += tempMAC;
    userJson += "\"}";
#if DEBUG == 1
    Serial.println( F("userData is : ") );
    Serial.println(userJson);
    Serial.println();
#endif
    
    return(userJson);
    
}
Member Data Documentation
String CoolBoard::answer ='' [private]
Definition at line 105 of file CoolBoard.h.
Referenced by onLineMode().
CoolBoardLed CoolBoard::coolBoardLed [private]
Definition at line 75 of file CoolBoard.h.
Referenced by begin(), config(), connect(), offLineMode(), onLineMode(), readSensors(), and update().
CoolBoardSensors CoolBoard::coolBoardSensors [private]
Definition at line 73 of file CoolBoard.h.
Referenced by begin(), and readSensors().
String CoolBoard::data ='' [private]
Definition at line 103 of file CoolBoard.h.
Referenced by offLineMode(), and onLineMode().
const int CoolBoard::EnI2C = 5 [private]
Definition at line 107 of file CoolBoard.h.
Referenced by CoolBoard(), initReadI2C(), and stopReadI2C().
ExternalSensors CoolBoard::externalSensors [private]
Definition at line 87 of file CoolBoard.h.
Referenced by begin(), and readSensors().
bool CoolBoard::externalSensorsActive =0 [private]
Definition at line 95 of file CoolBoard.h.
Referenced by begin(), config(), printConf(), and readSensors().
CoolFileSystem CoolBoard::fileSystem [private]
Definition at line 71 of file CoolBoard.h.
Referenced by config(), offLineMode(), onLineMode(), and update().
Irene3000 CoolBoard::irene3000 [private]
Definition at line 85 of file CoolBoard.h.
Referenced by begin(), and readSensors().
bool CoolBoard::ireneActive =0 [private]
Definition at line 91 of file CoolBoard.h.
Referenced by begin(), config(), printConf(), and readSensors().
Jetpack CoolBoard::jetPack [private]
Definition at line 83 of file CoolBoard.h.
Referenced by begin(), offLineMode(), and onLineMode().
bool CoolBoard::jetpackActive =0 [private]
Definition at line 93 of file CoolBoard.h.
Referenced by begin(), config(), offLineMode(), onLineMode(), and printConf().
unsigned long CoolBoard::logInterval =1 [private]
Definition at line 99 of file CoolBoard.h.
Referenced by config(), getLogInterval(), and printConf().
CoolMQTT CoolBoard::mqtt [private]
Definition at line 81 of file CoolBoard.h.
Referenced by begin(), connect(), isConnected(), offLineMode(), onLineMode(), update(), and userData().
CoolTime CoolBoard::rtc [private]
Definition at line 77 of file CoolBoard.h.
Referenced by begin(), onLineMode(), readSensors(), and userData().
int CoolBoard::serverTimeOut =180 [private]
Definition at line 101 of file CoolBoard.h.
Referenced by config(), and printConf().
bool CoolBoard::sleepActive =0 [private]
Definition at line 97 of file CoolBoard.h.
Referenced by config(), onLineMode(), and printConf().
bool CoolBoard::userActive =0 [private]
Definition at line 89 of file CoolBoard.h.
Referenced by config(), offLineMode(), onLineMode(), and printConf().
CoolWifi CoolBoard::wifiManager [private]
Definition at line 79 of file CoolBoard.h.
Referenced by begin(), connect(), isConnected(), and offLineMode().
Author
Generated automatically by Doxygen for CoolAPI from the source code.