.TH "CoolBoardLed.cpp" 3 "Wed Jun 28 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoolBoardLed.cpp \- \fBCoolBoardLed\fP Source File\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'FS\&.h'\fP
.br
\fC#include 'Arduino\&.h'\fP
.br
\fC#include <NeoPixelBus\&.h>\fP
.br
\fC#include 'CoolBoardLed\&.h'\fP
.br
\fC#include 'ArduinoJson\&.h'\fP
.br

.SH "Detailed Description"
.PP 
\fBCoolBoardLed\fP Source File\&. 


.PP
\fBAuthor:\fP
.RS 4
Mehdi Zemzem 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBCoolBoardLed\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
