.TH "/home/ashiroji/Arduino/libraries/CoolBoard/CoolBoard.cpp" 3 "Mon Jul 10 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/CoolBoard.cpp \- \fBCoolBoard\fP Source file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'FS\&.h'\fP
.br
\fC#include 'Arduino\&.h'\fP
.br
\fC#include 'CoolBoard\&.h'\fP
.br
\fC#include 'ArduinoJson\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP   1"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCoolBoard\fP Source file\&. 


.PP
\fBAuthor:\fP
.RS 4
Mehdi Zemzem 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
27/06/2017 
.RE
.PP

.PP
Definition in file \fBCoolBoard\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBUG   1"

.PP
Definition at line 18 of file CoolBoard\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
