CoolWifi
NAME
CoolWifi - This class manages the WiFi connection .
SYNOPSIS
#include <CoolWifi.h>
Public Member Functions
void begin ()
bool config ()
bool config (String ssid[], String pass[], int wifiNumber, int APTimeOut, bool nomad)
wl_status_t connect ()
wl_status_t connectWifiMulti ()
wl_status_t connectAP ()
wl_status_t state ()
void printConf ()
bool addWifi (String ssid, String pass='')
Private Attributes
ESP8266WiFiMulti wifiMulti
int wifiCount =0
String ssid [50] ={'0'}
String pass [50] ={'0'}
int timeOut =0
bool nomad =0
Detailed Description
This class manages the WiFi connection .
Definition at line 29 of file CoolWifi.h.
Member Function Documentation
bool CoolWifi::addWifi (String ssid, String pass = '')
CoolWifi::addWifi(ssid,pass) This method is provided to add new WiFi detected by the WiFiManager to the jsonConfig(if used )
Returns:
true if successfull , false otherwise
Definition at line 576 of file CoolWifi.cpp.
References pass, ssid, timeOut, and wifiCount.
Referenced by connectAP().
{
#if DEBUG == 1
    
    Serial.println("Entering CoolWifi.addWifi() ") ;
#endif
    
    this->wifiCount++;
    if( this->wifiCount >=50)
    {
    
    #if DEBUG == 1
        Serial.println("You have reached the limit of 50");
        return(false);
    
    #endif
    }
    this->ssid[this->wifiCount-1]=ssid;
    this->pass[this->wifiCount-1]=pass;
    
    //read config file
    //update data
    File configFile = SPIFFS.open("/wifiConfig.json", "r");
    if (!configFile)
    {
    
    #if DEBUG == 1
        Serial.println( F("failed to read /wifiConfig.json") );
        Serial.println();
    #endif
    }
    else
    {
        size_t size = configFile.size();
        // Allocate a buffer to store contents of the file.
        std::unique_ptr<char[]> buf(new char[size]);
        configFile.readBytes(buf.get(), size);
        DynamicJsonBuffer jsonBuffer;
        JsonObject& json = jsonBuffer.parseObject(buf.get());
        if (!json.success())
        {
        
        #if DEBUG == 1
            Serial.println( F("failed to parse json ") );
            Serial.println();
        
        #endif
        }
        else
        {
        
        #if DEBUG == 1
        
            Serial.println( F("configuration json is ") );
            json.printTo(Serial);
            Serial.println();
            Serial.print(F("jsonBuffer size: "));
            Serial.println(jsonBuffer.size());
            Serial.println();
        #endif
            //wifiCount
            if(json["wifiCount"].success() )
            {
                json["wifiCount"]=this->wifiCount;
            }
            else
            {
                this->wifiCount=this->wifiCount;
            }
            json["wifiCount"]=this->wifiCount;
            
            //AP timeOut
            if(json["timeOut"].success() )
            {
                this->timeOut=json["timeOut"];
            }
            else
            {
                this->timeOut=this->timeOut;
            }
            json["timeOut"]=this->timeOut;
            
            
            //new Wifi SSID and PASS
            JsonObject& newWifi = json.createNestedObject( "Wifi"+String( this->wifiCount-1 ) );
            
            newWifi["ssid"] =this->ssid[this->wifiCount-1];
            newWifi["pass"] = this->pass[this->wifiCount-1];
            
            configFile.close();
            configFile = SPIFFS.open("/wifiConfig.json", "w");
            if(!configFile)
            {
            
            #if DEBUG == 1
                Serial.println( F("failed to write to /wifiConfig.json") );
            
            #endif
            }
            
            json.printTo(configFile);
            configFile.close();
        #if DEBUG == 1
            Serial.println( F("saved configuration is :") );
            json.printTo(Serial);
            Serial.println();
        
        #endif
            return(true);
        }
    }
    
    return(true);
    
}
void CoolWifi::begin ()
CoolWifi::begin(): This method is provided to set the wifiMulti Access points and the wifiManager time out
Definition at line 37 of file CoolWifi.cpp.
References pass, ssid, wifiCount, and wifiMulti.
Referenced by CoolBoard::begin().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolWifi.begin()") );
    Serial.println();
#endif
    for(int i =0;i<this->wifiCount;i++)
    {
         this->wifiMulti.addAP(this->ssid[i].c_str() , this->pass[i].c_str() );
    }
    
}
bool CoolWifi::config ()
CoolWifi::config(): This method is provided to set the wifi parameters : -ssid -pass -AP timeOut -wifiCount
Returns:
true if successful,false otherwise
Definition at line 298 of file CoolWifi.cpp.
References nomad, pass, ssid, timeOut, and wifiCount.
Referenced by CoolBoard::begin().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolWifi.config()") );
    Serial.println();
#endif
    //read config file
    //update data
    File configFile = SPIFFS.open("/wifiConfig.json", "r");
    if (!configFile)
    {
    
    #if DEBUG == 1
        Serial.println( F("failed to read /wifiConfig.json") );
        Serial.println();
    #endif
        return(false);
    }
    else
    {
        size_t size = configFile.size();
        // Allocate a buffer to store contents of the file.
        std::unique_ptr<char[]> buf(new char[size]);
        configFile.readBytes(buf.get(), size);
        DynamicJsonBuffer jsonBuffer;
        JsonObject& json = jsonBuffer.parseObject(buf.get());
        if (!json.success())
        {
        
        #if DEBUG == 1
            Serial.println( F("failed to parse json ") );
            Serial.println();
        
        #endif
            
            return(false);
        }
        else
        {
        
        #if DEBUG == 1
        
            Serial.println( F("configuration json is ") );
            json.printTo(Serial);
            Serial.println();
            Serial.print(F("jsonBuffer size: "));
            Serial.println(jsonBuffer.size());
            Serial.println();
        #endif
            //wifiCount
            if(json["wifiCount"].success() )
            {
                this->wifiCount=json["wifiCount"];
            }
            else
            {
                this->wifiCount=this->wifiCount;
            }
            json["wifiCount"]=this->wifiCount;
            
            //AP timeOut
            if(json["timeOut"].success() )
            {
                this->timeOut=json["timeOut"];
            }
            else
            {
                this->timeOut=this->timeOut;
            }
            json["timeOut"]=this->timeOut;
            //nomad
            if(json["nomad"].success() )
            {
                this->nomad=json["nomad"];
            }
            else
            {
                this->nomad=this->nomad;
            }
            json["nomad"]=this->nomad;
            
            
            //Wifis SSID and PASS
            for(int i =0; i<this->wifiCount ;i++)
            {
                if ( json["Wifi"+String(i)].success() )
                {
                    
                    if( json["Wifi"+String(i)]["ssid"].success() )
                    {
                        const char* tempSsid=json["Wifi"+String(i)]["ssid"];
                        this->ssid[i]=tempSsid;
                    }
                    else
                    {
                        this->ssid[i]=this->ssid[i];
                    }
                    json["Wifi"+String(i)]["ssid"]=this->ssid[i].c_str();
                    
                    
                    if( json["Wifi"+String(i)]["pass"].success() )
                    {
                        const char* tempPass =json["Wifi"+String(i)]["pass"];
                        this->pass[i]=tempPass ;
                    }
                    else
                    {
                        this->pass[i]=this->pass[i];
                    }
                    json["Wifi"+String(i)]["pass"]=this->pass[i].c_str();
                
                }
                else
                {
                    
                    this->ssid[i]=this->ssid[i];
                    this->pass[i]=this->pass[i];
                    
                }
                json["Wifi"+String(i)]["ssid"]=this->ssid[i].c_str();
                json["Wifi"+String(i)]["pass"]=this->pass[i].c_str();
                        
            }
            configFile.close();
            configFile = SPIFFS.open("/wifiConfig.json", "w");
            if(!configFile)
            {
            
            #if DEBUG == 1
                Serial.println( F("failed to write to /wifiConfig.json") );
            
            #endif
                return(false);
            }
            
            json.printTo(configFile);
            configFile.close();
        #if DEBUG == 1
            Serial.println( F("saved configuration is :") );
            json.printTo(Serial);
            Serial.println();
        
        #endif
            return(true);
        }
    }
    
}
bool CoolWifi::config (String ssid[], String pass[], int wifiNumber, int APTimeOut, bool nomad)
CoolWifi::config(ssid array, pass array, number of wifis, AP timeout ); This method is provided to configure the Wifi without SPIFFS
Returns:
true if successfull, false otherwise
Definition at line 478 of file CoolWifi.cpp.
References nomad, timeOut, and wifiCount.
{
#if DEBUG == 1
    
    Serial.println("Entering CoolWifi.config(), no SPIFFS variant ") ;
    
#endif
    
    if(wifiNumber>50)
    {
    
    #if DEBUG == 1
        
        Serial.println("the limit of WiFis is 50 " );
        
    #endif
        return(false);
    }
    this->wifiCount=wifiNumber;
    this->timeOut=APTimeOut;
    this->nomad=nomad;
    
    for(int i=0;i<wifiNumber;i++)
    {
        this->ssid[i]=ssid[i];
        
        this->pass[i]=pass[i];
    }
        
    return(true);
}
wl_status_t CoolWifi::connect ()
CoolWifi::connect( ): This method is provided to connect to the strongest WiFi in the provided list of wiFis. If none are found , it starts the AP mode.
Returns:
wifi state
Definition at line 90 of file CoolWifi.cpp.
References connectAP(), connectWifiMulti(), nomad, and wifiCount.
Referenced by CoolBoard::connect().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolWifi.connect()") );
    Serial.println( F("Wifi connecting...") );
#endif
    //if WifiCount > 0 , lunch wifiMulti
    //else no need to , skip this part
    // to wifiManager
    if(this->wifiCount !=0)
    {
    
        this->connectWifiMulti();
        
        //if nomad is true, only check wifi list
        if(this->nomad == true)
        {
    
        #if DEBUG == 1
    
            Serial.print(F("nomad mode :"));
            Serial.println(this->nomad);
        
            Serial.print(F("Wifi status: "));
            Serial.println(WiFi.status());
        
        #endif
            return(WiFi.status());
        }
    }
    //Wifi Manager
    if( WiFi.status() != WL_CONNECTED )
    {
    #if DEBUG == 1
    
        Serial.println(F("No matching wifi Found ") );
        Serial.println( F("Starting Access Point ") );
        Serial.println();
    #endif
        
        this->connectAP();
        
    }
    else
    {
    #if DEBUG == 1
        Serial.println(F("connected to "));
        Serial.println( WiFi.SSID() );
        //Serial.println( WiFi.psk() ) ;
                
    #endif
    
    }
    
    return( WiFi.status() ) ;
}
wl_status_t CoolWifi::connectAP ()
CoolWifi::connectAP() This function is provided to run the WifiManager part of the Wifi connection process
Returns:
wifi state
Definition at line 220 of file CoolWifi.cpp.
References addWifi(), and timeOut.
Referenced by connect(), and CoolBoard::offLineMode().
{
#if DEBUG == 1
    
    Serial.println( F("Entering CoolWifi.connectAP()") );
    Serial.println();
#endif
    WiFiManager wifiManager;
    
    wifiManager.setRemoveDuplicateAPs(true);
    wifiManager.setTimeout(this->timeOut);
    
    String tempMAC = WiFi.macAddress();
    tempMAC.replace(":","");
    String name="CoolBoardAP"+tempMAC;
    if(!wifiManager.autoConnect(name.c_str()))
    {
    
    #if DEBUG == 1
        Serial.println( F("failed to connect and hit timeout") );
    
    #endif
        delay(30);
    }
    //if you get here you have connected to the WiFi
    if(WiFi.status()==WL_CONNECTED)
            Serial.println( F("connected...yeey :)" ));
            Serial.println("connected to ");
            Serial.println( WiFi.SSID() );
            //Serial.println( WiFi.psk() ) ;
            
        #endif
            this->addWifi( WiFi.SSID() , WiFi.psk() );
        
    }
wl_status_t CoolWifi::connectWifiMulti ()
CoolWifi::connectWifiMulti() This function is provided to run the WifiMulti part of the Wifi connection process
Returns:
wifi state
Definition at line 169 of file CoolWifi.cpp.
References wifiMulti.
Referenced by connect().
{
    int i=0;
#if DEBUG == 1
    Serial.println(F("Entering CoolWifi.connectWifiMulti()"));
    Serial.println();
    
    Serial.println( F("entry time to multi : ") );
    Serial.println(millis() ) ;
#endif
    
    //Wifi MULTI
    while( (this->wifiMulti.run() != WL_CONNECTED) && (i<500) )
    {
    #if DEBUG == 1
        Serial.print(F("."));
        i++;
        delay(5);
    #endif
        }
#if DEBUG == 1
    Serial.println();
    Serial.println(F("exit point from multi : "));
    Serial.println(millis() );
    
    Serial.print(F("Wifi Status :"));
    Serial.println(WiFi.status());
#endif
    return(WiFi.status());
}
void CoolWifi::printConf ()
CoolWifi::printConf(): This method is provided to print the configuration to the Serial Monitor
Definition at line 521 of file CoolWifi.cpp.
References nomad, ssid, timeOut, and wifiCount.
Referenced by CoolBoard::begin().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolWifi.printConf()") );
    Serial.println();
#endif
    
    Serial.println(F("Wifi configuration "));
    
    Serial.println(F("wifiCount : "));
    Serial.println(this->wifiCount);
    
    for(int i=0;i<this->wifiCount;i++)
    {
        Serial.print(F("SSID"));
        Serial.print(i);
        Serial.println(F(" : "));
        Serial.println(this->ssid[i]);
                
        //Serial.print("PASS");
        //Serial.print(i);
        //Serial.println(" : ");
        //Serial.print(F("PASS"));
        //Serial.print(i);
        //Serial.println(F(" : "));
        //Serial.println(this->pass[i]);
        
    }
    
    Serial.println(F("timeOut : "));
    Serial.println(this->timeOut);
    Serial.println(F("nomad : "));
    Serial.println(this->nomad);
    Serial.println();
}
wl_status_t CoolWifi::state ()
CoolWifi::state(): This method is provided to return the Wifi client's state.
Returns:
wifi client state: WL_NO_SHIELD = 255, WL_IDLE_STATUS = 0, WL_NO_SSID_AVAIL = 1, WL_SCAN_COMPLETED = 2, WL_CONNECTED = 3, WL_CONNECT_FAILED = 4, WL_CONNECTION_LOST = 5, WL_DISCONNECTED = 6
Definition at line 67 of file CoolWifi.cpp.
Referenced by CoolBoard::connect(), CoolBoard::isConnected(), and CoolBoard::offLineMode().
{
#if DEBUG == 1
    Serial.println( F("Entering CoolWifi.state()") );
    Serial.println();
    Serial.print( F("state : ") );
    Serial.println( WiFi.status() );
#endif
    
    return( WiFi.status() ) ;
}
Member Data Documentation
bool CoolWifi::nomad =0 [private]
Definition at line 63 of file CoolWifi.h.
Referenced by config(), connect(), and printConf().
String CoolWifi::pass[50] ={'0'} [private]
Definition at line 59 of file CoolWifi.h.
Referenced by addWifi(), begin(), and config().
String CoolWifi::ssid[50] ={'0'} [private]
Definition at line 57 of file CoolWifi.h.
Referenced by addWifi(), begin(), config(), and printConf().
int CoolWifi::timeOut =0 [private]
Definition at line 61 of file CoolWifi.h.
Referenced by addWifi(), config(), connectAP(), and printConf().
int CoolWifi::wifiCount =0 [private]
Definition at line 55 of file CoolWifi.h.
Referenced by addWifi(), begin(), config(), connect(), and printConf().
ESP8266WiFiMulti CoolWifi::wifiMulti [private]
Definition at line 53 of file CoolWifi.h.
Referenced by begin(), and connectWifiMulti().
Author
Generated automatically by Doxygen for CoolAPI from the source code.