.TH "CoolBoardSensors::airActive" 3 "Wed Jul 12 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoolBoardSensors::airActive
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "byte \fBtemperature\fP =0"
.br
.ti -1c
.RI "byte \fBhumidity\fP =0"
.br
.ti -1c
.RI "byte \fBpressure\fP =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 90 of file CoolBoardSensors\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "byte CoolBoardSensors::airActive::humidity =0"

.PP
Definition at line 93 of file CoolBoardSensors\&.h\&.
.PP
Referenced by CoolBoardSensors::allActive(), CoolBoardSensors::config(), CoolBoardSensors::printConf(), and CoolBoardSensors::read()\&.
.SS "byte CoolBoardSensors::airActive::pressure =0"

.PP
Definition at line 94 of file CoolBoardSensors\&.h\&.
.PP
Referenced by CoolBoardSensors::allActive(), CoolBoardSensors::config(), CoolBoardSensors::printConf(), and CoolBoardSensors::read()\&.
.SS "byte CoolBoardSensors::airActive::temperature =0"

.PP
Definition at line 92 of file CoolBoardSensors\&.h\&.
.PP
Referenced by CoolBoardSensors::allActive(), CoolBoardSensors::config(), CoolBoardSensors::printConf(), and CoolBoardSensors::read()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
