.TH "ExternalSensor.h" 3 "Wed Jun 28 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExternalSensor.h \- \fBExternalSensor\fP Header File\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <NDIR_I2C\&.h>\fP
.br
\fC#include <DallasTemperature\&.h>\fP
.br
\fC#include 'Arduino\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseExternalSensor\fP"
.br
.RI "This class is a generic external Sensor it is a way to access real external sensor methods through run Time polymorphism\&. "
.ti -1c
.RI "class \fBExternalSensor< T >\fP"
.br
.RI "template<class SensorClass> class External Sensor: Derived class from \fBBaseExternalSensor\fP\&. "
.ti -1c
.RI "class \fBExternalSensor< DallasTemperature >\fP"
.br
.RI "DallasTemperature Specialization Class This is the template specialization for the Dallas Temperature sensor\&. "
.ti -1c
.RI "class \fBExternalSensor< NDIR_I2C >\fP"
.br
.RI "NDIR_I2C Specialization Class This is the template specialization for the NDIR_I2C CO2 sensor\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBExternalSensor\fP Header File\&. 


.PP
\fBAuthor:\fP
.RS 4
Mehdi Zemzem 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
27/06/2017 
.RE
.PP

.PP
Definition in file \fBExternalSensor\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
