.TH "ExternalSensors.cpp" 3 "Wed Jun 28 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExternalSensors.cpp \- \fBExternalSensors\fP Source File\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'FS\&.h'\fP
.br
\fC#include 'Arduino\&.h'\fP
.br
\fC#include 'Wire\&.h'\fP
.br
\fC#include 'OneWire\&.h'\fP
.br
\fC#include 'ExternalSensors\&.h'\fP
.br
\fC#include 'ArduinoJson\&.h'\fP
.br
\fC#include 'ExternalSensor\&.h'\fP
.br

.SH "Detailed Description"
.PP 
\fBExternalSensors\fP Source File\&. 


.PP
\fBAuthor:\fP
.RS 4
Mehdi Zemzem 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
27/06/2017 
.RE
.PP

.PP
Definition in file \fBExternalSensors\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
