.TH "/home/ashiroji/Arduino/libraries/CoolBoard/ExternalSensor.h" 3 "Tue Jun 27 2017" "COOLAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/ExternalSensor.h
.SH SYNOPSIS
.br
.PP
\fC#include <NDIR_I2C\&.h>\fP
.br
\fC#include <DallasTemperature\&.h>\fP
.br
\fC#include 'Arduino\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseExternalSensor\fP"
.br
.ti -1c
.RI "class \fBExternalSensor< T >\fP"
.br
.ti -1c
.RI "class \fBExternalSensor< NDIR_I2C >\fP"
.br
.ti -1c
.RI "class \fBExternalSensor< DallasTemperature >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for COOLAPI from the source code\&.
