.TH "/home/ashiroji/Arduino/libraries/CoolBoard/ExternalSensors.h" 3 "Tue Aug 8 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/ExternalSensors.h \- \fBExternalSensors\fP Header File\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include 'Wire\&.h'\fP
.br
\fC#include 'OneWire\&.h'\fP
.br
\fC#include 'ExternalSensor\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExternalSensors\fP"
.br
.RI "This class handles the external sensors run time defintion , configuartion and actions\&. "
.ti -1c
.RI "struct \fBExternalSensors::sensor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBExternalSensors\fP Header File\&. 


.PP
\fBAuthor:\fP
.RS 4
Mehdi Zemzem 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
27/06/2017 
.RE
.PP

.PP
Definition in file \fBExternalSensors\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
