.TH "/home/ashiroji/Arduino/libraries/CoolBoard/ExternalSensors.cpp" 3 "Tue Jun 27 2017" "COOLAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/ExternalSensors.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'FS\&.h'\fP
.br
\fC#include 'Arduino\&.h'\fP
.br
\fC#include 'Wire\&.h'\fP
.br
\fC#include 'OneWire\&.h'\fP
.br
\fC#include 'ExternalSensors\&.h'\fP
.br
\fC#include 'ArduinoJson\&.h'\fP
.br
\fC#include 'ExternalSensor\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for COOLAPI from the source code\&.
