.TH "ExternalSensors::sensor" 3 "Wed Jun 28 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExternalSensors::sensor
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBaddress\fP"
.br
.ti -1c
.RI "String \fBconnection\fP"
.br
.ti -1c
.RI "int \fBdataSize\fP"
.br
.ti -1c
.RI "\fBBaseExternalSensor\fP * \fBexSensor\fP =NULL"
.br
.ti -1c
.RI "String \fBreference\fP"
.br
.ti -1c
.RI "String \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file ExternalSensors\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t ExternalSensors::sensor::address"

.PP
Definition at line 47 of file ExternalSensors\&.h\&.
.PP
Referenced by ExternalSensors::config()\&.
.SS "String ExternalSensors::sensor::connection"

.PP
Definition at line 45 of file ExternalSensors\&.h\&.
.PP
Referenced by ExternalSensors::config()\&.
.SS "int ExternalSensors::sensor::dataSize"

.PP
Definition at line 46 of file ExternalSensors\&.h\&.
.PP
Referenced by ExternalSensors::config()\&.
.SS "\fBBaseExternalSensor\fP* ExternalSensors::sensor::exSensor =NULL"

.PP
Definition at line 48 of file ExternalSensors\&.h\&.
.PP
Referenced by ExternalSensors::begin()\&.
.SS "String ExternalSensors::sensor::reference"

.PP
Definition at line 43 of file ExternalSensors\&.h\&.
.PP
Referenced by ExternalSensors::config()\&.
.SS "String ExternalSensors::sensor::type"

.PP
Definition at line 44 of file ExternalSensors\&.h\&.
.PP
Referenced by ExternalSensors::config(), and ExternalSensors::read()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
