.TH "ExternalSensor< NDIR_I2C >" 3 "Tue Jun 27 2017" "COOLAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExternalSensor< NDIR_I2C >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExternalSensor\&.h>\fP
.PP
Inherits \fBBaseExternalSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExternalSensor\fP (uint8_t i2c_addr)"
.br
.ti -1c
.RI "virtual uint8_t \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual int \fBread\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
class ExternalSensor< NDIR_I2C >"
NDIR_I2C Specialization Class This is the template specialization for the NDIR_I2C CO2 sensor 
.PP
Definition at line 120 of file ExternalSensor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBExternalSensor\fP< NDIR_I2C >::\fBExternalSensor\fP (uint8_t i2c_addr)\fC [inline]\fP"
\fBExternalSensor(I2C address)\fP: NDIR_I2C specific constructor 
.PP
Definition at line 128 of file ExternalSensor\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual uint8_t \fBExternalSensor\fP< NDIR_I2C >::begin (void)\fC [inline]\fP, \fC [virtual]\fP"
\fBbegin()\fP: NDIR_I2C specific begin method 
.PP
Reimplemented from \fBBaseExternalSensor\fP\&.
.PP
Definition at line 137 of file ExternalSensor\&.h\&.
.SS "virtual int \fBExternalSensor\fP< NDIR_I2C >::read (void)\fC [inline]\fP, \fC [virtual]\fP"
\fBread()\fP: NDIR_I2C specific read method 
.PP
Reimplemented from \fBBaseExternalSensor\fP\&.
.PP
Definition at line 156 of file ExternalSensor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COOLAPI from the source code\&.
