ExternalSensors
NAME
ExternalSensors - This class handles the external sensors run time defintion , configuartion and actions.
SYNOPSIS
#include <ExternalSensors.h>
Classes
struct sensor
Public Member Functions
void begin ()
String read ()
bool config ()
int getJsonSize ()
void printConf ()
Private Attributes
struct ExternalSensors::sensor sensors [50]
int sensorsNumber =0
int jsonSize =100
Detailed Description
This class handles the external sensors run time defintion , configuartion and actions.
Definition at line 26 of file ExternalSensors.h.
Member Function Documentation
void ExternalSensors::begin (void)
ExternalSensors::begin(): This method is provided to initialise the external sensors.
Definition at line 43 of file ExternalSensors.cpp.
References BaseExternalSensor::begin(), ExternalSensors::sensor::exSensor, sensors, and sensorsNumber.
Referenced by CoolBoard::begin().
{
#if DEBUG == 1
    Serial.println( F("Enter ExternalSensors.begin()") );
    Serial.println();
#endif
    for(int i=0;i< this->sensorsNumber ; i++)
    {
        if( (sensors[i].reference) == "NDIR_I2C" )
        {
            std::unique_ptr< ExternalSensor<NDIR_I2C> > sensorCO2(new ExternalSensor<NDIR_I2C> (77));
            sensors[i].exSensor= sensorCO2.release(); // using std::move;
            sensors[i].exSensor->begin();
        }
        if( (sensors[i].reference) == "DallasTemperature")
        {
            OneWire oneWire(0);
            std::unique_ptr< ExternalSensor<DallasTemperature> > dallasTemp(new ExternalSensor<DallasTemperature> ());
             ;
            sensors[i].exSensor=dallasTemp.release();
            sensors[i].exSensor->begin();
            
        }
        
        
    }
}
bool ExternalSensors::config ()
ExternalSensors::config(): This method is provided to configure the externalSensors through a configuration file
Returns:
true if successful,false otherwise
Definition at line 170 of file ExternalSensors.cpp.
References ExternalSensors::sensor::address, ExternalSensors::sensor::connection, ExternalSensors::sensor::dataSize, jsonSize, ExternalSensors::sensor::reference, sensors, sensorsNumber, and ExternalSensors::sensor::type.
Referenced by CoolBoard::begin(), and CoolBoard::update().
{
    //read config file
    //update data
    File externalSensorsConfig = SPIFFS.open("/externalSensorsConfig.json", "r");
    if (!externalSensorsConfig)
    {
    
    #if DEBUG == 1
        
        Serial.println( F("failed to read /externalSensorsConfig.json") );
        Serial.println();
    
    #endif
        
        return(false);
    }
    else
    {
        size_t size = externalSensorsConfig.size();
        // Allocate a buffer to store contents of the file.
        std::unique_ptr<char[]> buf(new char[size]);
        externalSensorsConfig.readBytes(buf.get(), size);
        DynamicJsonBuffer jsonBuffer;
        JsonObject& json = jsonBuffer.parseObject(buf.get());
        if (!json.success())
        {
        
        #if DEBUG == 1
            Serial.println( F("failed to parse json") );
            Serial.println();
        
        #endif
            return(false);
        }
        else
        {
        
        #if DEBUG == 1
    
            Serial.println( F("read configuration json : ") );
            json.printTo(Serial);
            Serial.println();
        
        #endif
            if(json["jsonSize"]!=NULL )
            {
                this->jsonSize=json["jsonSize"];
            }
            else
            {
                this->jsonSize=this->jsonSize;
            }
            json["jsonSize"]=this->jsonSize;
            
            if(json["sensorsNumber"]!=NULL)
            {
                this->sensorsNumber = json["sensorsNumber"];
                
                
                for(int i=0;i<sensorsNumber;i++)
                { String name="sensor"+String(i);
                    
                    if(json[name].success())
                    {
                        JsonObject& sensorJson=json[name];
                        
                        if(sensorJson["reference"].success() )
                        {
                            this->sensors[i].reference =sensorJson["reference"].as<String>();
                        }
                        else
                        {
                            this->sensors[i].reference=this->sensors[i].reference;
                            Serial.println("Not Found Name " );
                        }
                        sensorJson["reference"]=this->sensors[i].reference;
                    
                        if(sensorJson["type"].success() )
                        {
                            this->sensors[i].type=sensorJson["type"].as<String>();
                        }
                        else
                        {
                            this->sensors[i].type=this->sensors[i].type;
                            Serial.println("Not Found Name " ) ;
                        }
                        sensorJson["type"]=this->sensors[i].type;
                    
                    
                        if(sensorJson["connection"].success() )
                        {
                            this->sensors[i].connection=sensorJson["connection"].as<String>();
                        }
                        else
                        {
                            this->sensors[i].connection=this->sensors[i].connection;
                            Serial.println("Not Found Name " ) ;
                        }
                        sensorJson["connection"]=this->sensors[i].connection;
                    
                        if(sensorJson["dataSize"].success() )
                        {
                            this->sensors[i].dataSize=sensorJson["dataSize"];
                        }
                        else
                        {
                            this->sensors[i].dataSize=this->sensors[i].dataSize;
                            Serial.println("Not Found Name " ) ;
                        }
                        sensorJson["dataSize"]=this->sensors[i].dataSize;
                    
                        if(sensorJson["address"].success() )
                        {
                            this->sensors[i].address=sensorJson["address"];
                        }
                        else
                        {
                            this->sensors[i].address=this->sensors[i].address;
                            Serial.println("Not Found Name " ) ;
                        }
                        sensorJson["address"]=this->sensors[i].address;
                    
    
                    }
                    else
                    {
                        this->sensors[i]=this->sensors[i];
                    }
                                            
                    json[name]["reference"]=this->sensors[i].reference;
                    json[name]["type"]=this->sensors[i].type;
                    json[name]["connection"]=this->sensors[i].connection;
                    json[name]["dataSize"]=this->sensors[i].dataSize;
                    json[name]["address"]=this->sensors[i].address;
                }
 
            }
            else
            {
                this->sensorsNumber=this->sensorsNumber;
            }
            json["sensorsNumber"]=this->sensorsNumber;
            externalSensorsConfig.close();
            externalSensorsConfig = SPIFFS.open("/externalSensorsConfig.json", "w");
            if(!externalSensorsConfig)
            {
            
            #if DEBUG == 1
                Serial.println( F("failed to write to /externalSensorsConfig.json") );
                Serial.println();
            
            #endif
                return(false);
            }
            
            json.printTo(externalSensorsConfig);
            externalSensorsConfig.close();
            
        #if DEBUG == 1
            Serial.println( F("saved configuration is : ") );
            json.printTo(Serial);
            Serial.println();
        
        #endif
            return(true);
        }
    }
    
}
int ExternalSensors::getJsonSize ()
ExternalSensors::getJsonSize(): This method is provided to return the size of the json data as a way to control memory usage
Returns:
the json data size
Definition at line 145 of file ExternalSensors.cpp.
References jsonSize.
{
    
#if DEBUG == 1
    Serial.println( F("Enter ExternalSensors.getJsonSize") );
    Serial.println();
    
    Serial.print( F("jsonSize : ") );
    Serial.println(this->jsonSize);
    Serial.println();
#endif
    return(this->jsonSize );
}
void ExternalSensors::printConf ()
ExternalSensors::printConf(): This method is provided to print the configuration to the Serial Monitor
Definition at line 366 of file ExternalSensors.cpp.
References jsonSize, sensors, and sensorsNumber.
Referenced by CoolBoard::begin().
{
#if DEBUG == 1
    Serial.println( F("Entering ExternalSensors.printConf()") );
    Serial.println();
#endif
    Serial.println("External Sensors configuration ");
    Serial.print("sensorsNumber : ");
    Serial.println(sensorsNumber);
    Serial.println("jsonSize : ");
    Serial.println(jsonSize);
    for(int i=0;i<sensorsNumber;i++)
    {
        Serial.print("sensor ");
        Serial.print(i);
        Serial.print(" reference : ");
        Serial.println(this->sensors[i].reference);
        Serial.print("sensor ");
        Serial.print(i);
        Serial.print(" type : ");
        Serial.println(this->sensors[i].type);
        Serial.print("sensor ");
        Serial.print(i);
        Serial.print(" connection : ");
        Serial.println(this->sensors[i].connection);
        
        Serial.print("sensor ");
        Serial.print(i);
        Serial.print(" dataSize : ");
        Serial.println(this->sensors[i].dataSize);
        
        Serial.print("sensor ");
        Serial.print(i);
        Serial.print(" address : ");
        Serial.println(this->sensors[i].address);
    
    }
}
String ExternalSensors::read (void)
ExternalSensors::read(): This method is provided to read the data from the external sensors
Returns:
json string that contains the sensors data
Definition at line 86 of file ExternalSensors.cpp.
References jsonSize, sensors, sensorsNumber, and ExternalSensors::sensor::type.
Referenced by CoolBoard::readSensors().
{
#if DEBUG == 1
    Serial.println( F("Entering ExternalSensors.read()") );
    Serial.println();
#endif
    String data;
    DynamicJsonBuffer jsonBuffer(jsonSize) ;
    JsonObject& root = jsonBuffer.createObject();
    if(!root.success() )
    {
 
    #if DEBUG == 1
        Serial.println( F("failed to create json ") );
    
    #endif
        return("00");
    }
    else
    {
        if(sensorsNumber>0)
        {
            for(int i=0;i<sensorsNumber;i++)
            {
            
                root[sensors[i].type]=sensors[i].exSensor->read();
            }
        }
        
        root.printTo(data);
    
    #if DEBUG == 1
        Serial.println( F("sensors data :") );
        Serial.println(data);
        Serial.println();
    
    #endif
    
        return(data);
    }
}
Member Data Documentation
int ExternalSensors::jsonSize =100 [private]
Definition at line 52 of file ExternalSensors.h.
Referenced by config(), getJsonSize(), printConf(), and read().
struct ExternalSensors::sensor ExternalSensors::sensors[50] [private]
Referenced by begin(), config(), printConf(), and read().
int ExternalSensors::sensorsNumber =0 [private]
Definition at line 51 of file ExternalSensors.h.
Referenced by begin(), config(), printConf(), and read().
Author
Generated automatically by Doxygen for CoolAPI from the source code.