.TH "ExternalSensor< DallasTemperature >" 3 "Wed Jul 12 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExternalSensor< DallasTemperature > \- DallasTemperature Specialization Class This is the template specialization for the Dallas Temperature sensor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExternalSensor\&.h>\fP
.PP
Inherits \fBBaseExternalSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExternalSensor\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual float \fBread\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "DallasTemperature \fBsensor\fP =NULL"
.br
.ti -1c
.RI "DeviceAddress \fBdallasAddress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
class ExternalSensor< DallasTemperature >"
DallasTemperature Specialization Class This is the template specialization for the Dallas Temperature sensor\&. 
.PP
Definition at line 315 of file ExternalSensor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBExternalSensor\fP< DallasTemperature >::\fBExternalSensor\fP ()\fC [inline]\fP"
\fBExternalSensor()\fP: DallasTemperature specific constructor 
.PP
Definition at line 322 of file ExternalSensor\&.h\&.
.PP
References ExternalSensor< T >::sensor\&.
.PP
.nf
323     {
324         
325     #if DEBUG == 1 
326 
327         Serial\&.println( "ExternalSensor <DallasTemperature> constructor" );
328         Serial\&.println();
329     
330     #endif
331 
332         OneWire oneWire(0);
333         
334         sensor=DallasTemperature(&oneWire);
335     }
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual uint8_t \fBExternalSensor\fP< DallasTemperature >::begin (void)\fC [inline]\fP, \fC [virtual]\fP"
\fBbegin()\fP: DallasTemperature specific begin method
.PP
\fBReturns:\fP
.RS 4
true if successful 
.RE
.PP

.PP
Reimplemented from \fBBaseExternalSensor\fP\&.
.PP
Definition at line 343 of file ExternalSensor\&.h\&.
.PP
References ExternalSensor< T >::sensor\&.
.PP
.nf
344     {
345     
346     #if DEBUG == 1 
347 
348         Serial\&.println( "ExternalSensor <DallasTemperature> begin()" );
349         Serial\&.println();
350     
351     #endif
352     
353         sensor\&.begin(); 
354         delay(5);
355         sensor\&.getAddress(this->dallasAddress, 1);   
356         return(true);
357     }
.fi
.SS "virtual float \fBExternalSensor\fP< DallasTemperature >::read (void)\fC [inline]\fP, \fC [virtual]\fP"
\fBread()\fP: DallasTemperature specific read method
.PP
\fBReturns:\fP
.RS 4
the temperature in °C 
.RE
.PP

.PP
Reimplemented from \fBBaseExternalSensor\fP\&.
.PP
Definition at line 364 of file ExternalSensor\&.h\&.
.PP
References ExternalSensor< T >::sensor\&.
.PP
.nf
365     {
366     
367     #if DEBUG == 1 
368 
369         Serial\&.println( "ExternalSensor <DallasTemperature> read()" );
370         Serial\&.println();
371 
372         Serial\&.print( "temperature : ");
373         Serial\&.print( (float) sensor\&.getTempC(this->dallasAddress) );
374         Serial\&.print( "°C" );
375         Serial\&.println();
376     
377     #endif
378         
379         return( (float) sensor\&.getTempC(this->dallasAddress) );
380     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "DeviceAddress \fBExternalSensor\fP< DallasTemperature >::dallasAddress\fC [private]\fP"

.PP
Definition at line 385 of file ExternalSensor\&.h\&.
.SS "DallasTemperature \fBExternalSensor\fP< DallasTemperature >::sensor =NULL\fC [private]\fP"

.PP
Definition at line 384 of file ExternalSensor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
