.TH "ExternalSensor< NDIR_I2C >" 3 "Wed Jun 28 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExternalSensor< NDIR_I2C > \- NDIR_I2C Specialization Class This is the template specialization for the NDIR_I2C CO2 sensor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExternalSensor\&.h>\fP
.PP
Inherits \fBBaseExternalSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExternalSensor\fP (uint8_t i2c_addr)"
.br
.ti -1c
.RI "virtual uint8_t \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual int \fBread\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "NDIR_I2C \fBsensor\fP =NULL"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
class ExternalSensor< NDIR_I2C >"
NDIR_I2C Specialization Class This is the template specialization for the NDIR_I2C CO2 sensor\&. 
.PP
Definition at line 133 of file ExternalSensor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBExternalSensor\fP< NDIR_I2C >::\fBExternalSensor\fP (uint8_t i2c_addr)\fC [inline]\fP"
\fBExternalSensor(I2C address)\fP: NDIR_I2C specific constructor 
.PP
Definition at line 141 of file ExternalSensor\&.h\&.
.PP
References ExternalSensor< T >::sensor\&.
.PP
.nf
142     {
143         sensor=NDIR_I2C(i2c_addr);
144     }
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual uint8_t \fBExternalSensor\fP< NDIR_I2C >::begin (void)\fC [inline]\fP, \fC [virtual]\fP"
\fBbegin()\fP: NDIR_I2C specific begin method
.PP
\fBReturns:\fP
.RS 4
true if successful, false otherwise 
.RE
.PP

.PP
Reimplemented from \fBBaseExternalSensor\fP\&.
.PP
Definition at line 153 of file ExternalSensor\&.h\&.
.PP
References ExternalSensor< T >::sensor\&.
.PP
.nf
154     {
155 
156          if (sensor\&.begin()) 
157         {
158 
159             delay(10000);
160             return(true);
161             }
162          else 
163         {
164             return(false);
165         }   
166     }
.fi
.SS "virtual int \fBExternalSensor\fP< NDIR_I2C >::read (void)\fC [inline]\fP, \fC [virtual]\fP"
\fBread()\fP: NDIR_I2C specific read method
.PP
\fBReturns:\fP
.RS 4
the ppm value if successful, else return -42 
.RE
.PP

.PP
Reimplemented from \fBBaseExternalSensor\fP\&.
.PP
Definition at line 175 of file ExternalSensor\&.h\&.
.PP
References ExternalSensor< T >::sensor\&.
.PP
.nf
176     {
177 
178         if (sensor\&.measure())
179         {
180 
181 
182             return(sensor\&.ppm);
183             
184         }
185         
186         else
187         {
188 
189             return(-42);
190         }
191     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "NDIR_I2C \fBExternalSensor\fP< NDIR_I2C >::sensor =NULL\fC [private]\fP"

.PP
Definition at line 195 of file ExternalSensor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
