.TH "Irene3000::parameters_T" 3 "Mon Jul 3 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Irene3000::parameters_T
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBWriteCheck\fP"
.br
.ti -1c
.RI "int \fBpH7Cal\fP"
.br
.ti -1c
.RI "int \fBpH4Cal\fP"
.br
.ti -1c
.RI "float \fBpHStep\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 72 of file Irene3000\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int Irene3000::parameters_T::pH4Cal"

.PP
Definition at line 75 of file Irene3000\&.h\&.
.PP
Referenced by Irene3000::calcpHSlope(), Irene3000::calibratepH4(), and Irene3000::resetParams()\&.
.SS "int Irene3000::parameters_T::pH7Cal"

.PP
Definition at line 75 of file Irene3000\&.h\&.
.PP
Referenced by Irene3000::calcpHSlope(), Irene3000::calibratepH7(), Irene3000::readPh(), and Irene3000::resetParams()\&.
.SS "float Irene3000::parameters_T::pHStep"

.PP
Definition at line 76 of file Irene3000\&.h\&.
.PP
Referenced by Irene3000::calcpHSlope(), Irene3000::readPh(), and Irene3000::resetParams()\&.
.SS "unsigned int Irene3000::parameters_T::WriteCheck"

.PP
Definition at line 74 of file Irene3000\&.h\&.
.PP
Referenced by Irene3000::resetParams()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
