.TH "irene3000.cpp" 3 "Tue Jun 27 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irene3000.cpp \- \fBIrene3000\fP Source File\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'FS\&.h'\fP
.br
\fC#include <Adafruit_ADS1015\&.h>\fP
.br
\fC#include <Arduino\&.h>\fP
.br
\fC#include <Irene3000\&.h>\fP
.br
\fC#include 'ArduinoJson\&.h'\fP
.br

.SH "Detailed Description"
.PP 
\fBIrene3000\fP Source File\&. 


.PP
\fBAuthor:\fP
.RS 4
Mehdi Zemzem 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
27/06/2017 
.RE
.PP

.PP
Definition in file \fBirene3000\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
