.TH "/home/ashiroji/Arduino/libraries/CoolBoard/irene3000.cpp" 3 "Mon Jul 31 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/irene3000.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'FS\&.h'\fP
.br
\fC#include <Adafruit_ADS1015\&.h>\fP
.br
\fC#include <Arduino\&.h>\fP
.br
\fC#include 'ArduinoJson\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <Irene3000\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBUG   1"

.PP
Definition at line 21 of file irene3000\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
