.TH "Irene3000::h" 3 "Tue Jun 27 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Irene3000::h
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Irene3000\&.h>\fP
.SH "Detailed Description"
.PP 
This class is provided to manage the \fBIrene3000\fP Ph/Temperature Shield 

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
