.TH "/home/ashiroji/Arduino/libraries/CoolBoard/irene3000.cpp" 3 "Wed Jul 5 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/irene3000.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'FS\&.h'\fP
.br
\fC#include <Adafruit_ADS1015\&.h>\fP
.br
\fC#include <Arduino\&.h>\fP
.br
\fC#include <Irene3000\&.h>\fP
.br
\fC#include 'ArduinoJson\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
