.TH "/home/ashiroji/Arduino/libraries/CoolBoard/Irene3000.h" 3 "Tue Jun 27 2017" "COOLAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/Irene3000.h
.SH SYNOPSIS
.br
.PP
\fC#include <Adafruit_ADS1015\&.h>\fP
.br
\fC#include <Arduino\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIrene3000\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADC_MAXIMUM_VALUE\fP   32767"
.br
.ti -1c
.RI "#define \fBV_GAIN_2\fP   0\&.0625"
.br
.ti -1c
.RI "#define \fBV_GAIN_4\fP   0\&.03125"
.br
.ti -1c
.RI "#define \fBV_GAIN_8\fP   0\&.015625"
.br
.ti -1c
.RI "#define \fBWrite_Check\fP   0x1234"
.br
.ti -1c
.RI "#define \fBbutton\fP   0"
.br
.ti -1c
.RI "#define \fBtemp\fP   1"
.br
.ti -1c
.RI "#define \fBfreeAdc\fP   2"
.br
.ti -1c
.RI "#define \fBph\fP   3"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ADC_MAXIMUM_VALUE   32767"
\fBIrene3000\&.h\fP This class is provided to manage the \fBIrene3000\fP Ph/Temperature Shield 
.PP
Definition at line 15 of file Irene3000\&.h\&.
.SS "#define button   0"

.PP
Definition at line 21 of file Irene3000\&.h\&.
.SS "#define freeAdc   2"

.PP
Definition at line 23 of file Irene3000\&.h\&.
.SS "#define ph   3"

.PP
Definition at line 24 of file Irene3000\&.h\&.
.SS "#define temp   1"

.PP
Definition at line 22 of file Irene3000\&.h\&.
.SS "#define V_GAIN_2   0\&.0625"

.PP
Definition at line 16 of file Irene3000\&.h\&.
.SS "#define V_GAIN_4   0\&.03125"

.PP
Definition at line 17 of file Irene3000\&.h\&.
.SS "#define V_GAIN_8   0\&.015625"

.PP
Definition at line 18 of file Irene3000\&.h\&.
.SS "#define Write_Check   0x1234"

.PP
Definition at line 19 of file Irene3000\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COOLAPI from the source code\&.
