Irene3000
NAME
Irene3000 - This class is provided to manage the Irene3000 Ph/Temperature Shield.
SYNOPSIS
#include <Irene3000.h>
Classes
struct parameters_T
struct state
Public Member Functions
void begin ()
bool config ()
void printConf ()
String read ()
int readButton (adsGain_t gain)
void setGain (adsGain_t gain)
int readADSChannel2 (adsGain_t gain)
float readPh (adsGain_t gain)
double readTemp (adsGain_t gain)
void resetParams (void)
void calibratepH7 (adsGain_t gain)
void calibratepH4 (adsGain_t gain)
void calcpHSlope ()
adsGain_t gainConvert (uint16_t tempGain)
Private Attributes
Adafruit_ADS1115 ads
struct Irene3000::parameters_T params
struct Irene3000::state waterTemp
struct Irene3000::state phProbe
struct Irene3000::state adc2
int ireneJsonSize =100
const float vRef = 1.024
const float opampGain = 5.25
Detailed Description
This class is provided to manage the Irene3000 Ph/Temperature Shield.
Definition at line 35 of file Irene3000.h.
Member Function Documentation
void Irene3000::begin (void)
Irene3000::begin(): This method is provided to start the Irene3000 ADS chip
Definition at line 38 of file irene3000.cpp.
References ads.
Referenced by CoolBoard::begin().
{
#if DEBUG == 1
    Serial.println("Entering Irene3000.begin()");
    Serial.println();
#endif
    this->ads.begin();
}
void Irene3000::calcpHSlope ()
Irene3000::calcpHSlop(): This method is provided to calculate th PH slope
Definition at line 586 of file irene3000.cpp.
References opampGain, params, Irene3000::parameters_T::pH4Cal, Irene3000::parameters_T::pH7Cal, Irene3000::parameters_T::pHStep, and vRef.
Referenced by calibratepH4(), and calibratepH7().
{
#if DEBUG == 1
    Serial.println("Entering Irene3000.calcpHSlope()");
    Serial.println();
#endif
    params.pHStep = ((((vRef * (float)(params.pH7Cal - params.pH4Cal)) / 32767) * 1000) / opampGain) / 3;
 
}
void Irene3000::calibratepH4 (adsGain_t gain)
Irene3000::calibratepH4(gain): This method is provided to calibrate the PH probe to 4
Definition at line 561 of file irene3000.cpp.
References ads, calcpHSlope(), params, ph, Irene3000::parameters_T::pH4Cal, and setGain().
{
#if DEBUG == 1
    Serial.println("Entering Irene3000.calibraph4()");
    Serial.println();
#endif
    
    this->setGain(gain);
    this->params.pH4Cal = ads.readADC_SingleEnded(ph);
    this->calcpHSlope();
}
void Irene3000::calibratepH7 (adsGain_t gain)
Irene3000::calibratepH7(gain): This method is provided to calibrate the PH probe to 7
Definition at line 537 of file irene3000.cpp.
References ads, calcpHSlope(), params, ph, Irene3000::parameters_T::pH7Cal, and setGain().
{
#if DEBUG == 1
    Serial.println("Entering Irene3000.calibratepH7() ");
    Serial.println();
#endif
    this->setGain(gain);
        
    this->params.pH7Cal = ads.readADC_SingleEnded(ph);
 
    this->calcpHSlope();
}
bool Irene3000::config ()
Irene3000::config(): This method is provided to configure the Irene3000 shield through a configuration file
Returns:
true if successful,false otherwise
Definition at line 124 of file irene3000.cpp.
References Irene3000::state::active, adc2, Irene3000::state::gain, gainConvert(), ireneJsonSize, phProbe, Irene3000::state::type, and waterTemp.
Referenced by CoolBoard::begin(), and CoolBoard::update().
{
#if DEBUG == 1
    Serial.println("Entering Irene3000.config()");
    Serial.println();
#endif
    File irene3000Config = SPIFFS.open("/irene3000Config.json", "r");
    if (!irene3000Config)
    {
    
    #if DEBUG == 1
        Serial.println("failed to read /irene3000Config.json");
        Serial.println();
    
    #endif
        return(false);
    }
    else
    {
        size_t size = irene3000Config.size();
        // Allocate a buffer to store contents of the file.
        std::unique_ptr<char[]> buf(new char[size]);
            uint16_t tempGain;
        irene3000Config.readBytes(buf.get(), size);
        DynamicJsonBuffer jsonBuffer;
        JsonObject& json = jsonBuffer.parseObject(buf.get());
        if (!json.success())
        {
        
        #if DEBUG == 1
            Serial.println("failed to parse json ");
            Serial.println();
        
        #endif
            
            return(false);
        }
        else
        {
        
        #if DEBUG == 1
    
            Serial.println("read configuration file ");
            json.printTo(Serial);
            Serial.println();
        
        #endif
            
            if(json["ireneJsonSize"].success() )
            {
                this->ireneJsonSize=json["ireneJsonSize"];
            }
            else
            {
                this->ireneJsonSize=this->ireneJsonSize;
            }
            json["ireneJsonSize"]=this->ireneJsonSize;
            
            if(json["waterTemp"]["active"].success() )
            {
                this->waterTemp.active = json["waterTemp"]["active"];
            }
            else
            {
                this->waterTemp.active=this->waterTemp.active;
            }
            json["waterTemp"]["active"]=this->waterTemp.active;
            
            if(json["waterTemp"]["gain"].success() )
            {
                tempGain = json["waterTemp"]["gain"];
                this->waterTemp.gain=this->gainConvert(tempGain);
            }
            else
            {
                this->waterTemp.gain=this->waterTemp.gain;
            }
            json["waterTemp"]["gain"]=this->waterTemp.gain;
            
            if(json["phProbe"]["active"].success())
            {
                this->phProbe.active=json["phProbe"]["active"];
            }
            else
            {
                this->phProbe.active=this->phProbe.active;
            }
            json["phProbe"]["active"]=this->phProbe.active;
    
            
            if(json["phProbe"]["gain"].success() )
            {
                tempGain=json["phProbe"]["gain"];
                this->phProbe.gain=this->gainConvert(tempGain);
            }
            else
            {
                this->phProbe.gain=this->phProbe.gain;
            }
            json["phProbe"]["gain"]=this->phProbe.gain;
            
            if(json["adc2"]["active"].success() )
            {
                this->adc2.active=json["adc2"]["active"];
            }
            else
            {
                this->adc2.active=this->adc2.active;
            }
            json["adc2"]["active"]=this->adc2.active;
            
            if(json["adc2"]["gain"].success() )
            {
                tempGain=json["adc2"]["gain"];
                this->adc2.gain=this->gainConvert(tempGain);
            }
            else
            {
                this->adc2.gain=this->adc2.gain;
            }
            json["adc2"]["gain"]=this->adc2.gain;
            
            if(json["adc2"]["type"].success() )
            {
                this->adc2.type=json["adc2"]["type"].as<String>();
            }
            else
            {
                this->adc2.type=this->adc2.type;
            }
            json["adc2"]["type"]=this->adc2.type;
            irene3000Config.close();
            irene3000Config = SPIFFS.open("/irene3000Config.json", "w");
            if(!irene3000Config)
            {
            
            #if DEBUG == 1
                Serial.println("failed to write to /irene3000Config.json");
                Serial.println();
            
            #endif
                return(false);
            }
            json.printTo(irene3000Config);
            irene3000Config.close();
            
        #if DEBUG == 1
            Serial.println("saved configuration file :" );
            json.printTo(Serial);
            Serial.println();
        
        #endif
            return(true);
        }
    }
}
adsGain_t Irene3000::gainConvert (uint16_t tempGain)
Irene3000::gainConvert( gain : { 2/3,1,2,4,8,16 } ) This method is provided to convert the gain to Internal Constants
Returns:
internal representation of the ADS gain
Definition at line 633 of file irene3000.cpp.
Referenced by config().
{
#if DEBUG == 1
    Serial.println("Entering Irene3000.gainConvert()");
    Serial.println();
#endif
    
    switch(tempGain)
    {
        case(2/3): return(GAIN_TWOTHIRDS);
        case(1): return (GAIN_ONE);
        case(2) : return(GAIN_TWO);
        case(4): return(GAIN_FOUR) ;
        case(8):return(GAIN_EIGHT) ;
        case(16):return(GAIN_SIXTEEN);
    }
}
void Irene3000::printConf ()
Irene3000::printConf(): This method is provided to print the configuration to the Serial Monitor
Definition at line 308 of file irene3000.cpp.
References Irene3000::state::active, adc2, Irene3000::state::gain, phProbe, Irene3000::state::type, and waterTemp.
Referenced by CoolBoard::begin().
{
#if DEBUG == 1
    Serial.println("Entering Irene3000.printConf()");
    Serial.println();
#endif
    Serial.println("Irene Configuration ");
    Serial.print("waterTemp.active : ");
    Serial.println(waterTemp.active);
    Serial.print("waterTemp.gain : ");
    Serial.println(waterTemp.gain,HEX);
    Serial.print("phProbe.active : ");
    Serial.println(phProbe.active);
    Serial.print("phProbe.gain : ");
    Serial.println(phProbe.gain,HEX);
    
    Serial.print("adc2.active : ");
    Serial.println(adc2.active);
    Serial.print("adc2.gain : ");
    Serial.println(adc2.gain,HEX);
    Serial.print("adc2.type : ");
    Serial.println(adc2.type);
    Serial.println();
}
String Irene3000::read (void)
Irene3000:read(): This method is provided to read the Irene3000 sensors data
Returns:
json string of the sensors data
Definition at line 59 of file irene3000.cpp.
References Irene3000::state::active, adc2, Irene3000::state::gain, ireneJsonSize, phProbe, readADSChannel2(), readPh(), readTemp(), Irene3000::state::type, and waterTemp.
Referenced by CoolBoard::readSensors().
{
#if DEBUG == 1
    
    Serial.println("Entering Irene3000.read()");
    Serial.println();
#endif
    String data;
    DynamicJsonBuffer jsonBuffer(ireneJsonSize);
    JsonObject& root = jsonBuffer.createObject();
    if( !( root.success()) )
    {
    
    #if DEBUG == 1
        Serial.println("failed to create json");
    
    #endif
        return("");
    }
        
    if(waterTemp.active)
    {
        root["waterTemp"] = this->readTemp(waterTemp.gain);
        if(phProbe.active)
        {
            root["ph"] =this->readPh(phProbe.gain) ;
        }
    }
    if(adc2.active)
    {
        root[adc2.type] =this->readADSChannel2(adc2.gain);
    }
    
    root.printTo(data);
    
#if DEBUG == 1
    Serial.println("Irene data : ");
    Serial.println(data);
    Serial.println();
#endif
    
    return(data);
    
    
}
int Irene3000::readADSChannel2 (adsGain_t gain)
Irene3000::readADSChannel2(gain): This method is provided to read from the ADS channel 2 . ADS Channel 2 is free and the user can connect another analog sensor to it.
Returns:
the ADS Channel 2 value
Definition at line 401 of file irene3000.cpp.
References ads, freeAdc, and setGain().
Referenced by read().
{
#if DEBUG == 1
    
    Serial.println("Entering Irene3000.readADSChannel2()");
    Serial.println();
#endif
    this->setGain(gain);
#if DEBUG == 1
    
    Serial.println("adc2 value : ");
    Serial.println(this->ads.readADC_SingleEnded(freeAdc) );
    Serial.println();
#endif
    return( this->ads.readADC_SingleEnded(freeAdc) ) ;
}
int Irene3000::readButton (adsGain_t gain)
Irene3000::readButton(gain): This method is provided to read the Irene3000 button
Returns:
the button value
Definition at line 351 of file irene3000.cpp.
References ads, button, and setGain().
{
#if DEBUG == 1
    Serial.println("Entering Irene3000.readButton()");
    Serial.println();
#endif
    this->setGain(gain);
#if DEBUG == 1
    
    Serial.println("button value : ");
    Serial.println(this->ads.readADC_SingleEnded(button) );
#endif
    return( this->ads.readADC_SingleEnded(button) );
    
}
float Irene3000::readPh (adsGain_t gain)
Irene3000::readPh(gain): This method is provided to read the PH probe note that for the best results, PH must be correlated to Temperature.
Returns:
the PH probe value
Definition at line 432 of file irene3000.cpp.
References ADC_MAXIMUM_VALUE, ads, opampGain, params, ph, Irene3000::parameters_T::pH7Cal, Irene3000::parameters_T::pHStep, setGain(), and vRef.
Referenced by read().
{
#if DEBUG == 1
    Serial.println("Entering Irene3000.readPh()");
    Serial.println();
#endif
    this->setGain(gain);
    double Voltage = gain * ( ads.readADC_SingleEnded(ph) ) / ADC_MAXIMUM_VALUE;
    float miliVolts = Voltage * 1000;
    float temporary = ((((vRef * (float)params.pH7Cal) / 32767) * 1000) - miliVolts) / opampGain;
#if DEBUG == 1
    Serial.println("ph is : ");
    Serial.println( 7 - (temporary / params.pHStep) ) ;
#endif
    return( 7 - (temporary / params.pHStep) );
}
double Irene3000::readTemp (adsGain_t gain)
Irene3000::readTemp(gain): This method is provided to read the Temeperature probe
Returns:
the Temperature probe value
Definition at line 467 of file irene3000.cpp.
References ads, setGain(), temp, and V_GAIN_8.
Referenced by read().
{
#if DEBUG == 1
    Serial.println("Entering Irene3000.readTemp()");
    Serial.println();
#endif
    const double A = 3.9083E-3;
    const double B = -5.775E-7;
    double T;
    this->setGain(gain);
    double adc0 = ads.readADC_SingleEnded(temp);
    double R = ( ( adc0 * V_GAIN_8 ) / 0.095 ) / 1000 ;
    T = 0.0 - A;
    T += sqrt((A * A) - 4.0 * B * (1.0 - R));
    T /= (2.0 * B);
    if (T > 0 && T < 200)
    {
    #if DEBUG == 1
        Serial.print(" temperature : ");
        Serial.println(T);
        Serial.println();
    
    #endif
        if(isnan(T))
        {
            return(-300);
        }
        return T;
    }
    else
    {
        T = 0.0 - A;
        T -= sqrt((A * A) - 4.0 * B * (1.0 - R));
        T /= (2.0 * B);
    
    #if DEBUG == 1
    
        Serial.println("temperature : ");
        Serial.println(T);
        Serial.println();
    
    #endif
        if(isnan(T))
        {
            return(-400);
        }
        return T;
    }
}
void Irene3000::resetParams (void)
Irene3000::resetParams(): This method is provided to reset the PH configuration, assuming Ideal configuration
Definition at line 607 of file irene3000.cpp.
References params, Irene3000::parameters_T::pH4Cal, Irene3000::parameters_T::pH7Cal, Irene3000::parameters_T::pHStep, Write_Check, and Irene3000::parameters_T::WriteCheck.
{
#if DEBUG == 1
    Serial.println("Entering Irene3000.resetParams()");
    Serial.println();
#endif
    //Restore to default set of parameters!
    params.WriteCheck = Write_Check;
    params.pH7Cal = 16384; //assume ideal probe and amp conditions 1/2 of 4096
    params.pH4Cal = 8192; //using ideal probe slope we end up this many 12bit units away on the 4 scale
    params.pHStep = 59.16;//ideal probe slope
}
void Irene3000::setGain (adsGain_t gain)
Irene3000::setGain(gain): This method is provided to set the ADS chip gain
Definition at line 379 of file irene3000.cpp.
References ads.
Referenced by calibratepH4(), calibratepH7(), readADSChannel2(), readButton(), readPh(), and readTemp().
{
#if DEBUG == 1
    Serial.println("Entering Irene3000.setGain()");
    Serial.println();
#endif
    this->ads.setGain(gain);
}
Member Data Documentation
struct Irene3000::state Irene3000::adc2 [private]
Referenced by config(), printConf(), and read().
Adafruit_ADS1115 Irene3000::ads [private]
Definition at line 69 of file Irene3000.h.
Referenced by begin(), calibratepH4(), calibratepH7(), readADSChannel2(), readButton(), readPh(), readTemp(), and setGain().
int Irene3000::ireneJsonSize =100 [private]
Definition at line 86 of file Irene3000.h.
Referenced by config(), and read().
const float Irene3000::opampGain = 5.25 [private]
Definition at line 90 of file Irene3000.h.
Referenced by calcpHSlope(), and readPh().
struct Irene3000::parameters_T Irene3000::params [private]
Referenced by calcpHSlope(), calibratepH4(), calibratepH7(), readPh(), and resetParams().
struct Irene3000::state Irene3000::phProbe [private]
Referenced by config(), printConf(), and read().
const float Irene3000::vRef = 1.024 [private]
Definition at line 88 of file Irene3000.h.
Referenced by calcpHSlope(), and readPh().
struct Irene3000::state Irene3000::waterTemp [private]
Referenced by config(), printConf(), and read().
Author
Generated automatically by Doxygen for CoolAPI from the source code.