.TH "Jetpack::h" 3 "Tue Jun 27 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Jetpack::h
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Jetpack\&.h>\fP
.SH "Detailed Description"
.PP 
This class manages the \fBJetpack\fP shield 

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
