.TH "/home/ashiroji/Arduino/libraries/CoolBoard/Jetpack.cpp" 3 "Wed Jul 5 2017" "CoolAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/Jetpack.cpp \- \fBJetpack\fP Source File\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'FS\&.h'\fP
.br
\fC#include 'Arduino\&.h'\fP
.br
\fC#include 'ArduinoJson\&.h'\fP
.br
\fC#include 'Jetpack\&.h'\fP
.br

.SH "Detailed Description"
.PP 
\fBJetpack\fP Source File\&. 


.PP
\fBAuthor:\fP
.RS 4
Mehdi Zemzem 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
27/06/2017 
.RE
.PP

.PP
Definition in file \fBJetpack\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolAPI from the source code\&.
