.TH "Adafruit_ADS1015" 3 "Mon Sep 4 2017" "CoolBoard API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Adafruit_ADS1015
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CoolAdafruit_ADS1015\&.h>\fP
.PP
Inherited by \fBAdafruit_ADS1115\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdafruit_ADS1015\fP (uint8_t i2cAddress=\fBADS1015_ADDRESS\fP)"
.br
.RI "Instantiates a new ADS1015 class w/appropriate properties\&. "
.ti -1c
.RI "void \fBbegin\fP (void)"
.br
.RI "Sets up the HW (reads coefficients values, etc\&.) "
.ti -1c
.RI "uint16_t \fBreadADC_SingleEnded\fP (uint8_t channel)"
.br
.RI "Gets a single-ended ADC reading from the specified channel\&. "
.ti -1c
.RI "int16_t \fBreadADC_Differential_0_1\fP (void)"
.br
.RI "Reads the conversion results, measuring the voltage difference between the P (AIN0) and N (AIN1) input\&. Generates a signed value since the difference can be either positive or negative\&. "
.ti -1c
.RI "int16_t \fBreadADC_Differential_2_3\fP (void)"
.br
.RI "Reads the conversion results, measuring the voltage difference between the P (AIN2) and N (AIN3) input\&. Generates a signed value since the difference can be either positive or negative\&. "
.ti -1c
.RI "void \fBstartComparator_SingleEnded\fP (uint8_t channel, int16_t threshold)"
.br
.RI "Sets up the comparator to operate in basic mode, causing the ALERT/RDY pin to assert (go from high to low) when the ADC value exceeds the specified threshold\&. "
.ti -1c
.RI "int16_t \fBgetLastConversionResults\fP ()"
.br
.RI "In order to clear the comparator, we need to read the conversion results\&. This function reads the last conversion results without changing the config value\&. "
.ti -1c
.RI "void \fBsetGain\fP (\fBadsGain_t\fP gain)"
.br
.RI "Sets the gain and input voltage range\&. "
.ti -1c
.RI "\fBadsGain_t\fP \fBgetGain\fP (void)"
.br
.RI "Gets a gain and input voltage range\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBm_i2cAddress\fP"
.br
.ti -1c
.RI "uint8_t \fBm_conversionDelay\fP"
.br
.ti -1c
.RI "uint8_t \fBm_bitShift\fP"
.br
.ti -1c
.RI "\fBadsGain_t\fP \fBm_gain\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 119 of file CoolAdafruit_ADS1015\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Adafruit_ADS1015::Adafruit_ADS1015 (uint8_t i2cAddress = \fC\fBADS1015_ADDRESS\fP\fP)"

.PP
Instantiates a new ADS1015 class w/appropriate properties\&. 
.PP
Definition at line 88 of file CoolAdafruit_ADS1015\&.cpp\&.
.PP
References ADS1015_CONVERSIONDELAY, GAIN_TWOTHIRDS, m_bitShift, m_conversionDelay, m_gain, and m_i2cAddress\&.
.SH "Member Function Documentation"
.PP 
.SS "void Adafruit_ADS1015::begin (void)"

.PP
Sets up the HW (reads coefficients values, etc\&.) 
.PP
Definition at line 114 of file CoolAdafruit_ADS1015\&.cpp\&.
.PP
Referenced by Irene3000::begin()\&.
.SS "uint16_t Adafruit_ADS1015::readADC_SingleEnded (uint8_t channel)"

.PP
Gets a single-ended ADC reading from the specified channel\&. 
.PP
Definition at line 143 of file CoolAdafruit_ADS1015\&.cpp\&.
.PP
References ADS1015_REG_CONFIG_CLAT_NONLAT, ADS1015_REG_CONFIG_CMODE_TRAD, ADS1015_REG_CONFIG_CPOL_ACTVLOW, ADS1015_REG_CONFIG_CQUE_NONE, ADS1015_REG_CONFIG_DR_1600SPS, ADS1015_REG_CONFIG_MODE_SINGLE, ADS1015_REG_CONFIG_MUX_SINGLE_0, ADS1015_REG_CONFIG_MUX_SINGLE_1, ADS1015_REG_CONFIG_MUX_SINGLE_2, ADS1015_REG_CONFIG_MUX_SINGLE_3, ADS1015_REG_CONFIG_OS_SINGLE, ADS1015_REG_POINTER_CONFIG, ADS1015_REG_POINTER_CONVERT, m_bitShift, m_conversionDelay, m_gain, m_i2cAddress, readRegister(), and writeRegister()\&.
.PP
Referenced by Irene3000::calibratepH4(), Irene3000::calibratepH7(), Irene3000::readADSChannel2(), Irene3000::readButton(), Irene3000::readPh(), and Irene3000::readTemp()\&.
.SS "int16_t Adafruit_ADS1015::readADC_Differential_0_1 (void)"

.PP
Reads the conversion results, measuring the voltage difference between the P (AIN0) and N (AIN1) input\&. Generates a signed value since the difference can be either positive or negative\&. 
.PP
Definition at line 199 of file CoolAdafruit_ADS1015\&.cpp\&.
.PP
References ADS1015_REG_CONFIG_CLAT_NONLAT, ADS1015_REG_CONFIG_CMODE_TRAD, ADS1015_REG_CONFIG_CPOL_ACTVLOW, ADS1015_REG_CONFIG_CQUE_NONE, ADS1015_REG_CONFIG_DR_1600SPS, ADS1015_REG_CONFIG_MODE_SINGLE, ADS1015_REG_CONFIG_MUX_DIFF_0_1, ADS1015_REG_CONFIG_OS_SINGLE, ADS1015_REG_POINTER_CONFIG, ADS1015_REG_POINTER_CONVERT, m_bitShift, m_conversionDelay, m_gain, m_i2cAddress, readRegister(), and writeRegister()\&.
.SS "int16_t Adafruit_ADS1015::readADC_Differential_2_3 (void)"

.PP
Reads the conversion results, measuring the voltage difference between the P (AIN2) and N (AIN3) input\&. Generates a signed value since the difference can be either positive or negative\&. 
.PP
Definition at line 250 of file CoolAdafruit_ADS1015\&.cpp\&.
.PP
References ADS1015_REG_CONFIG_CLAT_NONLAT, ADS1015_REG_CONFIG_CMODE_TRAD, ADS1015_REG_CONFIG_CPOL_ACTVLOW, ADS1015_REG_CONFIG_CQUE_NONE, ADS1015_REG_CONFIG_DR_1600SPS, ADS1015_REG_CONFIG_MODE_SINGLE, ADS1015_REG_CONFIG_MUX_DIFF_2_3, ADS1015_REG_CONFIG_OS_SINGLE, ADS1015_REG_POINTER_CONFIG, ADS1015_REG_POINTER_CONVERT, m_bitShift, m_conversionDelay, m_gain, m_i2cAddress, readRegister(), and writeRegister()\&.
.SS "void Adafruit_ADS1015::startComparator_SingleEnded (uint8_t channel, int16_t threshold)"

.PP
Sets up the comparator to operate in basic mode, causing the ALERT/RDY pin to assert (go from high to low) when the ADC value exceeds the specified threshold\&. This will also set the ADC in continuous conversion mode\&. 
.PP
Definition at line 302 of file CoolAdafruit_ADS1015\&.cpp\&.
.PP
References ADS1015_REG_CONFIG_CLAT_LATCH, ADS1015_REG_CONFIG_CMODE_TRAD, ADS1015_REG_CONFIG_CPOL_ACTVLOW, ADS1015_REG_CONFIG_CQUE_1CONV, ADS1015_REG_CONFIG_DR_1600SPS, ADS1015_REG_CONFIG_MODE_CONTIN, ADS1015_REG_CONFIG_MUX_SINGLE_0, ADS1015_REG_CONFIG_MUX_SINGLE_1, ADS1015_REG_CONFIG_MUX_SINGLE_2, ADS1015_REG_CONFIG_MUX_SINGLE_3, ADS1015_REG_POINTER_CONFIG, ADS1015_REG_POINTER_HITHRESH, m_bitShift, m_gain, m_i2cAddress, and writeRegister()\&.
.SS "int16_t Adafruit_ADS1015::getLastConversionResults ()"

.PP
In order to clear the comparator, we need to read the conversion results\&. This function reads the last conversion results without changing the config value\&. 
.PP
Definition at line 348 of file CoolAdafruit_ADS1015\&.cpp\&.
.PP
References ADS1015_REG_POINTER_CONVERT, m_bitShift, m_conversionDelay, m_i2cAddress, and readRegister()\&.
.SS "void Adafruit_ADS1015::setGain (\fBadsGain_t\fP gain)"

.PP
Sets the gain and input voltage range\&. 
.PP
Definition at line 123 of file CoolAdafruit_ADS1015\&.cpp\&.
.PP
References m_gain\&.
.PP
Referenced by Irene3000::setGain()\&.
.SS "\fBadsGain_t\fP Adafruit_ADS1015::getGain (void)"

.PP
Gets a gain and input voltage range\&. 
.PP
Definition at line 133 of file CoolAdafruit_ADS1015\&.cpp\&.
.PP
References m_gain\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t Adafruit_ADS1015::m_i2cAddress\fC [protected]\fP"

.PP
Definition at line 123 of file CoolAdafruit_ADS1015\&.h\&.
.PP
Referenced by Adafruit_ADS1015(), Adafruit_ADS1115::Adafruit_ADS1115(), getLastConversionResults(), readADC_Differential_0_1(), readADC_Differential_2_3(), readADC_SingleEnded(), and startComparator_SingleEnded()\&.
.SS "uint8_t Adafruit_ADS1015::m_conversionDelay\fC [protected]\fP"

.PP
Definition at line 124 of file CoolAdafruit_ADS1015\&.h\&.
.PP
Referenced by Adafruit_ADS1015(), Adafruit_ADS1115::Adafruit_ADS1115(), getLastConversionResults(), readADC_Differential_0_1(), readADC_Differential_2_3(), and readADC_SingleEnded()\&.
.SS "uint8_t Adafruit_ADS1015::m_bitShift\fC [protected]\fP"

.PP
Definition at line 125 of file CoolAdafruit_ADS1015\&.h\&.
.PP
Referenced by Adafruit_ADS1015(), Adafruit_ADS1115::Adafruit_ADS1115(), getLastConversionResults(), readADC_Differential_0_1(), readADC_Differential_2_3(), readADC_SingleEnded(), and startComparator_SingleEnded()\&.
.SS "\fBadsGain_t\fP Adafruit_ADS1015::m_gain\fC [protected]\fP"

.PP
Definition at line 126 of file CoolAdafruit_ADS1015\&.h\&.
.PP
Referenced by Adafruit_ADS1015(), Adafruit_ADS1115::Adafruit_ADS1115(), getGain(), readADC_Differential_0_1(), readADC_Differential_2_3(), readADC_SingleEnded(), setGain(), and startComparator_SingleEnded()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoard API from the source code\&.
