BaseExternalSensor
NAME
BaseExternalSensor - This class is a generic external Sensor it is a way to access real external sensor methods through run Time polymorphism.
SYNOPSIS
#include <ExternalSensor.h>
Inherited by ExternalSensor< T >, ExternalSensor< Adafruit_TCS34725 >, ExternalSensor< DallasTemperature >, and ExternalSensor< NDIR_I2C >.
Public Member Functions
BaseExternalSensor ()
virtual uint8_t begin ()
virtual float read ()
virtual float read (uint16_t *r, uint16_t *g, uint16_t *b, uint16_t *c, uint16_t *colorTemp, uint16_t *lux)
Detailed Description
This class is a generic external Sensor it is a way to access real external sensor methods through run Time polymorphism.
Definition at line 51 of file ExternalSensor.h.
Constructor & Destructor Documentation
BaseExternalSensor::BaseExternalSensor () [inline]
BaseExternalSensor(): Base class generic Constructor
Definition at line 59 of file ExternalSensor.h.
Member Function Documentation
virtual uint8_t BaseExternalSensor::begin () [inline], [virtual]
begin(): Base class virtual generic begin method
Returns:
generic value as it's not supposed to be used
Reimplemented in ExternalSensor< Adafruit_TCS34725 >, ExternalSensor< DallasTemperature >, ExternalSensor< NDIR_I2C >, and ExternalSensor< T >.
Definition at line 79 of file ExternalSensor.h.
Referenced by ExternalSensors::begin().
virtual float BaseExternalSensor::read () [inline], [virtual]
read(): Base class virtual generic read method
Returns:
generic value as it is not supposed to be used
Reimplemented in ExternalSensor< DallasTemperature >, ExternalSensor< NDIR_I2C >, and ExternalSensor< T >.
Definition at line 101 of file ExternalSensor.h.
Referenced by ExternalSensors::begin(), and ExternalSensors::read().
virtual float BaseExternalSensor::read (uint16_t * r, uint16_t * g, uint16_t * b, uint16_t * c, uint16_t * colorTemp, uint16_t * lux) [inline], [virtual]
read(): Base class virtual generic read method
Returns:
generic value as it is not supposed to be used
Reimplemented in ExternalSensor< Adafruit_TCS34725 >.
Definition at line 122 of file ExternalSensor.h.
Author
Generated automatically by Doxygen for CoolBoard API from the source code.