.TH "BaseExternalSensor" 3 "Thu Aug 24 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseExternalSensor \- This class is a generic external Sensor it is a way to access real external sensor methods through run Time polymorphism\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExternalSensor\&.h>\fP
.PP
Inherited by \fBExternalSensor< T >\fP, \fBExternalSensor< DallasTemperature >\fP, and \fBExternalSensor< NDIR_I2C >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseExternalSensor\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual float \fBread\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is a generic external Sensor it is a way to access real external sensor methods through run Time polymorphism\&. 
.PP
Definition at line 48 of file ExternalSensor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BaseExternalSensor::BaseExternalSensor ()\fC [inline]\fP"
\fBBaseExternalSensor()\fP: Base class generic Constructor 
.PP
Definition at line 56 of file ExternalSensor\&.h\&.
.PP
.nf
57     {
58 
59     #if DEBUGExternal == 1 
60 
61         Serial\&.println( "BaseExternalSensor Constructor" );
62         Serial\&.println();
63     
64     #endif
65 
66     }
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual uint8_t BaseExternalSensor::begin ()\fC [inline]\fP, \fC [virtual]\fP"
\fBbegin()\fP: Base class virtual generic begin method
.PP
\fBReturns:\fP
.RS 4
generic value as it's not supposed to be used 
.RE
.PP

.PP
Reimplemented in \fBExternalSensor< DallasTemperature >\fP, \fBExternalSensor< NDIR_I2C >\fP, and \fBExternalSensor< T >\fP\&.
.PP
Definition at line 76 of file ExternalSensor\&.h\&.
.PP
.nf
77     {
78     
79     #if DEBUGExternal == 1 
80     
81         Serial\&.println( "BaseExternalSensor\&.begin()" );
82         Serial\&.println();
83     
84     #endif
85 
86         return(-2);
87     }
.fi
.SS "virtual float BaseExternalSensor::read ()\fC [inline]\fP, \fC [virtual]\fP"
\fBread()\fP: Base class virtual generic read method
.PP
\fBReturns:\fP
.RS 4
generic value as it is not supposed to be used 
.RE
.PP

.PP
Reimplemented in \fBExternalSensor< DallasTemperature >\fP, \fBExternalSensor< NDIR_I2C >\fP, and \fBExternalSensor< T >\fP\&.
.PP
Definition at line 98 of file ExternalSensor\&.h\&.
.PP
.nf
99     {
100     
101     #if DEBUGExternal == 1 
102 
103         Serial\&.println( "BaseExternalSensor\&.read()" );
104         Serial\&.println();
105     
106     #endif      
107         
108         return(-2);
109     }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
