.TH "BaseExternalSensor" 3 "Wed Aug 30 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseExternalSensor \- This class is a generic external Sensor it is a way to access real external sensor methods through run Time polymorphism\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExternalSensor\&.h>\fP
.PP
Inherited by \fBExternalSensor< T >\fP, \fBExternalSensor< DallasTemperature >\fP, and \fBExternalSensor< NDIR_I2C >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseExternalSensor\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual float \fBread\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is a generic external Sensor it is a way to access real external sensor methods through run Time polymorphism\&. 
.PP
Definition at line 49 of file ExternalSensor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BaseExternalSensor::BaseExternalSensor ()\fC [inline]\fP"
\fBBaseExternalSensor()\fP: Base class generic Constructor 
.PP
Definition at line 57 of file ExternalSensor\&.h\&.
.PP
.nf
58     {
59 
60     #if DEBUGExternal == 1 
61 
62         Serial\&.println( "BaseExternalSensor Constructor" );
63         Serial\&.println();
64     
65     #endif
66 
67     }
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual uint8_t BaseExternalSensor::begin ()\fC [inline]\fP, \fC [virtual]\fP"
\fBbegin()\fP: Base class virtual generic begin method
.PP
\fBReturns:\fP
.RS 4
generic value as it's not supposed to be used 
.RE
.PP

.PP
Reimplemented in \fBExternalSensor< DallasTemperature >\fP, \fBExternalSensor< NDIR_I2C >\fP, and \fBExternalSensor< T >\fP\&.
.PP
Definition at line 77 of file ExternalSensor\&.h\&.
.PP
.nf
78     {
79     
80     #if DEBUGExternal == 1 
81     
82         Serial\&.println( "BaseExternalSensor\&.begin()" );
83         Serial\&.println();
84     
85     #endif
86 
87         return(-2);
88     }
.fi
.SS "virtual float BaseExternalSensor::read ()\fC [inline]\fP, \fC [virtual]\fP"
\fBread()\fP: Base class virtual generic read method
.PP
\fBReturns:\fP
.RS 4
generic value as it is not supposed to be used 
.RE
.PP

.PP
Reimplemented in \fBExternalSensor< DallasTemperature >\fP, \fBExternalSensor< NDIR_I2C >\fP, and \fBExternalSensor< T >\fP\&.
.PP
Definition at line 99 of file ExternalSensor\&.h\&.
.PP
.nf
100     {
101     
102     #if DEBUGExternal == 1 
103 
104         Serial\&.println( "BaseExternalSensor\&.read()" );
105         Serial\&.println();
106     
107     #endif      
108         
109         return(-2);
110     }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
