.TH "BaseExternalSensor" 3 "Tue Aug 22 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseExternalSensor \- This class is a generic external Sensor it is a way to access real external sensor methods through run Time polymorphism\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExternalSensor\&.h>\fP
.PP
Inherited by \fBExternalSensor< T >\fP, \fBExternalSensor< DallasTemperature >\fP, and \fBExternalSensor< NDIR_I2C >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseExternalSensor\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual float \fBread\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is a generic external Sensor it is a way to access real external sensor methods through run Time polymorphism\&. 
.PP
Definition at line 26 of file ExternalSensor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BaseExternalSensor::BaseExternalSensor ()\fC [inline]\fP"
\fBBaseExternalSensor()\fP: Base class generic Constructor 
.PP
Definition at line 34 of file ExternalSensor\&.h\&.
.PP
.nf
35     {
36 
37     #if DEBUGExternal == 1 
38 
39         Serial\&.println( "BaseExternalSensor Constructor" );
40         Serial\&.println();
41     
42     #endif
43 
44     }
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual uint8_t BaseExternalSensor::begin ()\fC [inline]\fP, \fC [virtual]\fP"
\fBbegin()\fP: Base class virtual generic begin method
.PP
\fBReturns:\fP
.RS 4
generic value as it's not supposed to be used 
.RE
.PP

.PP
Reimplemented in \fBExternalSensor< DallasTemperature >\fP, \fBExternalSensor< NDIR_I2C >\fP, and \fBExternalSensor< T >\fP\&.
.PP
Definition at line 54 of file ExternalSensor\&.h\&.
.PP
.nf
55     {
56     
57     #if DEBUGExternal == 1 
58     
59         Serial\&.println( "BaseExternalSensor\&.begin()" );
60         Serial\&.println();
61     
62     #endif
63 
64         return(-2);
65     }
.fi
.SS "virtual float BaseExternalSensor::read ()\fC [inline]\fP, \fC [virtual]\fP"
\fBread()\fP: Base class virtual generic read method
.PP
\fBReturns:\fP
.RS 4
generic value as it is not supposed to be used 
.RE
.PP

.PP
Reimplemented in \fBExternalSensor< DallasTemperature >\fP, \fBExternalSensor< NDIR_I2C >\fP, and \fBExternalSensor< T >\fP\&.
.PP
Definition at line 76 of file ExternalSensor\&.h\&.
.PP
.nf
77     {
78     
79     #if DEBUGExternal == 1 
80 
81         Serial\&.println( "BaseExternalSensor\&.read()" );
82         Serial\&.println();
83     
84     #endif      
85         
86         return(-2);
87     }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
