.TH "CoolPubSubClient.cpp" 3 "Mon Sep 11 2017" "CoolBoard API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoolPubSubClient.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CoolPubSubClient\&.h'\fP
.br
\fC#include 'Arduino\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMQTT_HEADER_VERSION_LENGTH\fP   7"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MQTT_HEADER_VERSION_LENGTH   7"

.PP
Referenced by CoolPubSubClient::connect()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoard API from the source code\&.
