CoolPubSubClient
NAME
CoolPubSubClient
SYNOPSIS
#include <CoolPubSubClient.h>
Public Member Functions
CoolPubSubClient ()
CoolPubSubClient (Client &client)
CoolPubSubClient (IPAddress, uint16_t, Client &client)
CoolPubSubClient (IPAddress, uint16_t, Client &client, Stream &)
CoolPubSubClient (IPAddress, uint16_t, MQTT_CALLBACK_SIGNATURE, Client &client)
CoolPubSubClient (IPAddress, uint16_t, MQTT_CALLBACK_SIGNATURE, Client &client, Stream &)
CoolPubSubClient (uint8_t *, uint16_t, Client &client)
CoolPubSubClient (uint8_t *, uint16_t, Client &client, Stream &)
CoolPubSubClient (uint8_t *, uint16_t, MQTT_CALLBACK_SIGNATURE, Client &client)
CoolPubSubClient (uint8_t *, uint16_t, MQTT_CALLBACK_SIGNATURE, Client &client, Stream &)
CoolPubSubClient (const char *, uint16_t, Client &client)
CoolPubSubClient (const char *, uint16_t, Client &client, Stream &)
CoolPubSubClient (const char *, uint16_t, MQTT_CALLBACK_SIGNATURE, Client &client)
CoolPubSubClient (const char *, uint16_t, MQTT_CALLBACK_SIGNATURE, Client &client, Stream &)
~CoolPubSubClient ()
CoolPubSubClient & setServer (IPAddress ip, uint16_t port)
CoolPubSubClient & setServer (uint8_t *ip, uint16_t port)
CoolPubSubClient & setServer (const char *domain, uint16_t port)
CoolPubSubClient & setCallback (MQTT_CALLBACK_SIGNATURE)
CoolPubSubClient & setClient (Client &client)
CoolPubSubClient & setStream (Stream &stream)
CoolPubSubClient & setTimeout (uint16_t socketTimeout)
boolean connect (const char *id, uint16_t keepAlive=MQTT_KEEPALIVE, uint16_t socketTimeout=MQTT_SOCKET_TIMEOUT)
boolean connect (const char *id, const char *user, const char *pass, uint16_t keepAlive=MQTT_KEEPALIVE, uint16_t socketTimeout=MQTT_SOCKET_TIMEOUT)
boolean connect (const char *id, const char *willTopic, uint8_t willQos, boolean willRetain, const char *willMessage, uint16_t keepAlive=MQTT_KEEPALIVE, uint16_t socketTimeout=MQTT_SOCKET_TIMEOUT)
boolean connect (const char *id, const char *user, const char *pass, const char *willTopic, uint8_t willQos, boolean willRetain, const char *willMessage, uint16_t keepAlive=MQTT_KEEPALIVE, uint16_t socketTimeout=MQTT_SOCKET_TIMEOUT)
void disconnect ()
boolean publish (const char *topic, const char *payload)
boolean publish (const char *topic, const char *payload, boolean retained)
boolean publish (const char *topic, const uint8_t *payload, unsigned int plength)
boolean publish (const char *topic, const uint8_t *payload, unsigned int plength, boolean retained)
boolean publish_P (const char *topic, const uint8_t *payload, unsigned int plength, boolean retained)
boolean subscribe (const char *topic)
boolean subscribe (const char *topic, uint8_t qos)
boolean unsubscribe (const char *topic)
boolean loop ()
boolean connected ()
int state ()
boolean setBufferSize (uint16_t size)
uint16_t getBufferSize ()
Private Member Functions
uint16_t readPacket (uint8_t *)
boolean readByte (uint8_t *result)
boolean readByte (uint8_t *result, uint16_t *index)
boolean write (uint8_t header, uint8_t *buf, uint16_t length)
uint16_t writeString (const char *string, uint8_t *buf, uint16_t pos)
Private Attributes
Client * _client
uint8_t * buffer
uint16_t buffer_size
uint16_t nextMsgId
unsigned long lastOutActivity
unsigned long lastInActivity
bool pingOutstanding
MQTT_CALLBACK_SIGNATURE
IPAddress ip
const char * domain
uint16_t port
Stream * stream
int _state
uint16_t keepAlive
uint16_t socketTimeout
Detailed Description
Definition at line 88 of file CoolPubSubClient.h.
Constructor & Destructor Documentation
CoolPubSubClient::CoolPubSubClient ()
Definition at line 14 of file CoolPubSubClient.cpp.
References _client, _state, buffer, buffer_size, MQTT_DISCONNECTED, MQTT_MAX_PACKET_SIZE, setCallback(), and stream.
CoolPubSubClient::CoolPubSubClient (Client & client)
Definition at line 23 of file CoolPubSubClient.cpp.
References _state, buffer, buffer_size, MQTT_DISCONNECTED, MQTT_MAX_PACKET_SIZE, setClient(), and stream.
CoolPubSubClient::CoolPubSubClient (IPAddress addr, uint16_t port, Client & client)
Definition at line 31 of file CoolPubSubClient.cpp.
References _state, buffer, buffer_size, MQTT_DISCONNECTED, MQTT_MAX_PACKET_SIZE, setClient(), setServer(), and stream.
CoolPubSubClient::CoolPubSubClient (IPAddress addr, uint16_t port, Client & client, Stream & stream)
Definition at line 39 of file CoolPubSubClient.cpp.
References _state, buffer, buffer_size, MQTT_DISCONNECTED, MQTT_MAX_PACKET_SIZE, setClient(), setServer(), and setStream().
CoolPubSubClient::CoolPubSubClient (IPAddress addr, uint16_t port, MQTT_CALLBACK_SIGNATURE, Client & client)
Definition at line 47 of file CoolPubSubClient.cpp.
References _state, buffer, buffer_size, MQTT_DISCONNECTED, MQTT_MAX_PACKET_SIZE, setCallback(), setClient(), setServer(), and stream.
CoolPubSubClient::CoolPubSubClient (IPAddress addr, uint16_t port, MQTT_CALLBACK_SIGNATURE, Client & client, Stream & stream)
Definition at line 56 of file CoolPubSubClient.cpp.
References _state, buffer, buffer_size, MQTT_DISCONNECTED, MQTT_MAX_PACKET_SIZE, setCallback(), setClient(), setServer(), and setStream().
CoolPubSubClient::CoolPubSubClient (uint8_t * ip, uint16_t port, Client & client)
Definition at line 66 of file CoolPubSubClient.cpp.
References _state, buffer, buffer_size, MQTT_DISCONNECTED, MQTT_MAX_PACKET_SIZE, setClient(), setServer(), and stream.
CoolPubSubClient::CoolPubSubClient (uint8_t * ip, uint16_t port, Client & client, Stream & stream)
Definition at line 74 of file CoolPubSubClient.cpp.
References _state, buffer, buffer_size, MQTT_DISCONNECTED, MQTT_MAX_PACKET_SIZE, setClient(), setServer(), and setStream().
CoolPubSubClient::CoolPubSubClient (uint8_t * ip, uint16_t port, MQTT_CALLBACK_SIGNATURE, Client & client)
Definition at line 82 of file CoolPubSubClient.cpp.
References _state, buffer, buffer_size, MQTT_DISCONNECTED, MQTT_MAX_PACKET_SIZE, setCallback(), setClient(), setServer(), and stream.
CoolPubSubClient::CoolPubSubClient (uint8_t * ip, uint16_t port, MQTT_CALLBACK_SIGNATURE, Client & client, Stream & stream)
Definition at line 91 of file CoolPubSubClient.cpp.
References _state, buffer, buffer_size, MQTT_DISCONNECTED, MQTT_MAX_PACKET_SIZE, setCallback(), setClient(), setServer(), and setStream().
CoolPubSubClient::CoolPubSubClient (const char * domain, uint16_t port, Client & client)
Definition at line 101 of file CoolPubSubClient.cpp.
References _state, buffer, buffer_size, MQTT_DISCONNECTED, MQTT_MAX_PACKET_SIZE, setClient(), setServer(), and stream.
CoolPubSubClient::CoolPubSubClient (const char * domain, uint16_t port, Client & client, Stream & stream)
Definition at line 109 of file CoolPubSubClient.cpp.
References _state, buffer, buffer_size, MQTT_DISCONNECTED, MQTT_MAX_PACKET_SIZE, setClient(), setServer(), and setStream().
CoolPubSubClient::CoolPubSubClient (const char * domain, uint16_t port, MQTT_CALLBACK_SIGNATURE, Client & client)
Definition at line 117 of file CoolPubSubClient.cpp.
References _state, buffer, buffer_size, MQTT_DISCONNECTED, MQTT_MAX_PACKET_SIZE, setCallback(), setClient(), setServer(), and stream.
CoolPubSubClient::CoolPubSubClient (const char * domain, uint16_t port, MQTT_CALLBACK_SIGNATURE, Client & client, Stream & stream)
Definition at line 126 of file CoolPubSubClient.cpp.
References _state, buffer, buffer_size, MQTT_DISCONNECTED, MQTT_MAX_PACKET_SIZE, setCallback(), setClient(), setServer(), and setStream().
CoolPubSubClient::~CoolPubSubClient ()
Definition at line 136 of file CoolPubSubClient.cpp.
References buffer.
Member Function Documentation
uint16_t CoolPubSubClient::readPacket (uint8_t * lengthLength) [private]
Definition at line 284 of file CoolPubSubClient.cpp.
References buffer, buffer_size, MQTTPUBLISH, MQTTQOS1, readByte(), and stream.
Referenced by connect(), and loop().
boolean CoolPubSubClient::readByte (uint8_t * result) [private]
Definition at line 259 of file CoolPubSubClient.cpp.
References _client, and socketTimeout.
Referenced by readByte(), and readPacket().
boolean CoolPubSubClient::readByte (uint8_t * result, uint16_t * index) [private]
Definition at line 274 of file CoolPubSubClient.cpp.
References readByte().
boolean CoolPubSubClient::write (uint8_t header, uint8_t * buf, uint16_t length) [private]
Definition at line 476 of file CoolPubSubClient.cpp.
References _client, and lastOutActivity.
Referenced by connect(), publish(), subscribe(), and unsubscribe().
uint16_t CoolPubSubClient::writeString (const char * string, uint8_t * buf, uint16_t pos) [private]
Definition at line 574 of file CoolPubSubClient.cpp.
Referenced by connect(), publish(), publish_P(), subscribe(), and unsubscribe().
CoolPubSubClient & CoolPubSubClient::setServer (IPAddress ip, uint16_t port)
Definition at line 610 of file CoolPubSubClient.cpp.
References domain, ip, and port.
Referenced by CoolMQTT::begin(), CoolPubSubClient(), and setServer().
CoolPubSubClient & CoolPubSubClient::setServer (uint8_t * ip, uint16_t port)
Definition at line 605 of file CoolPubSubClient.cpp.
References setServer().
CoolPubSubClient & CoolPubSubClient::setServer (const char * domain, uint16_t port)
Definition at line 617 of file CoolPubSubClient.cpp.
References domain, and port.
CoolPubSubClient & CoolPubSubClient::setCallback (MQTT_CALLBACK_SIGNATURE)
Definition at line 623 of file CoolPubSubClient.cpp.
Referenced by CoolMQTT::begin(), and CoolPubSubClient().
CoolPubSubClient & CoolPubSubClient::setClient (Client & client)
Definition at line 628 of file CoolPubSubClient.cpp.
References _client.
Referenced by CoolMQTT::begin(), and CoolPubSubClient().
CoolPubSubClient & CoolPubSubClient::setStream (Stream & stream)
Definition at line 633 of file CoolPubSubClient.cpp.
References stream.
Referenced by CoolPubSubClient().
CoolPubSubClient & CoolPubSubClient::setTimeout (uint16_t socketTimeout)
Definition at line 652 of file CoolPubSubClient.cpp.
References socketTimeout.
boolean CoolPubSubClient::connect (const char * id, uint16_t keepAlive = MQTT_KEEPALIVE, uint16_t socketTimeout = MQTT_SOCKET_TIMEOUT)
Definition at line 140 of file CoolPubSubClient.cpp.
Referenced by CoolMQTT::connect(), and connect().
boolean CoolPubSubClient::connect (const char * id, const char * user, const char * pass, uint16_t keepAlive = MQTT_KEEPALIVE, uint16_t socketTimeout = MQTT_SOCKET_TIMEOUT)
Definition at line 144 of file CoolPubSubClient.cpp.
References connect().
boolean CoolPubSubClient::connect (const char * id, const char * willTopic, uint8_t willQos, boolean willRetain, const char * willMessage, uint16_t keepAlive = MQTT_KEEPALIVE, uint16_t socketTimeout = MQTT_SOCKET_TIMEOUT)
Definition at line 148 of file CoolPubSubClient.cpp.
References connect().
boolean CoolPubSubClient::connect (const char * id, const char * user, const char * pass, const char * willTopic, uint8_t willQos, boolean willRetain, const char * willMessage, uint16_t keepAlive = MQTT_KEEPALIVE, uint16_t socketTimeout = MQTT_SOCKET_TIMEOUT)
Definition at line 152 of file CoolPubSubClient.cpp.
References _client, _state, buffer, connected(), domain, ip, keepAlive, lastInActivity, lastOutActivity, MQTT_CONNECT_FAILED, MQTT_CONNECTED, MQTT_CONNECTION_TIMEOUT, MQTT_HEADER_VERSION_LENGTH, MQTT_KEEPALIVE, MQTT_SOCKET_TIMEOUT, MQTT_VERSION, MQTTCONNECT, nextMsgId, pingOutstanding, port, readPacket(), socketTimeout, write(), and writeString().
void CoolPubSubClient::disconnect ()
Definition at line 565 of file CoolPubSubClient.cpp.
References _client, _state, buffer, lastInActivity, lastOutActivity, MQTT_DISCONNECTED, and MQTTDISCONNECT.
boolean CoolPubSubClient::publish (const char * topic, const char * payload)
Definition at line 397 of file CoolPubSubClient.cpp.
Referenced by CoolMQTT::publish(), and publish().
boolean CoolPubSubClient::publish (const char * topic, const char * payload, boolean retained)
Definition at line 401 of file CoolPubSubClient.cpp.
References publish().
boolean CoolPubSubClient::publish (const char * topic, const uint8_t * payload, unsigned int plength)
Definition at line 405 of file CoolPubSubClient.cpp.
References publish().
boolean CoolPubSubClient::publish (const char * topic, const uint8_t * payload, unsigned int plength, boolean retained)
Definition at line 409 of file CoolPubSubClient.cpp.
References buffer, buffer_size, connected(), MQTTPUBLISH, write(), and writeString().
boolean CoolPubSubClient::publish_P (const char * topic, const uint8_t * payload, unsigned int plength, boolean retained)
Definition at line 431 of file CoolPubSubClient.cpp.
References _client, buffer, connected(), lastOutActivity, MQTTPUBLISH, and writeString().
boolean CoolPubSubClient::subscribe (const char * topic)
Definition at line 518 of file CoolPubSubClient.cpp.
Referenced by CoolMQTT::connect().
boolean CoolPubSubClient::subscribe (const char * topic, uint8_t qos)
Definition at line 522 of file CoolPubSubClient.cpp.
References buffer, buffer_size, connected(), MQTTQOS1, MQTTSUBSCRIBE, nextMsgId, write(), and writeString().
boolean CoolPubSubClient::unsubscribe (const char * topic)
Definition at line 546 of file CoolPubSubClient.cpp.
References buffer, buffer_size, connected(), MQTTQOS1, MQTTUNSUBSCRIBE, nextMsgId, write(), and writeString().
boolean CoolPubSubClient::loop ()
Definition at line 334 of file CoolPubSubClient.cpp.
References _client, _state, buffer, connected(), keepAlive, lastInActivity, lastOutActivity, MQTT_CONNECTION_TIMEOUT, MQTTPINGREQ, MQTTPINGRESP, MQTTPUBACK, MQTTPUBLISH, MQTTQOS1, pingOutstanding, and readPacket().
Referenced by CoolMQTT::mqttLoop().
boolean CoolPubSubClient::connected ()
Definition at line 588 of file CoolPubSubClient.cpp.
References _client, _state, MQTT_CONNECTED, and MQTT_CONNECTION_LOST.
Referenced by CoolMQTT::connect(), connect(), loop(), publish(), publish_P(), subscribe(), and unsubscribe().
int CoolPubSubClient::state ()
Definition at line 638 of file CoolPubSubClient.cpp.
References _state.
Referenced by CoolMQTT::state().
boolean CoolPubSubClient::setBufferSize (uint16_t size)
Definition at line 642 of file CoolPubSubClient.cpp.
References buffer, and buffer_size.
Referenced by CoolMQTT::begin().
uint16_t CoolPubSubClient::getBufferSize ()
Definition at line 648 of file CoolPubSubClient.cpp.
References buffer_size.
Member Data Documentation
Client* CoolPubSubClient::_client [private]
Definition at line 90 of file CoolPubSubClient.h.
Referenced by connect(), connected(), CoolPubSubClient(), disconnect(), loop(), publish_P(), readByte(), setClient(), and write().
uint8_t* CoolPubSubClient::buffer [private]
Definition at line 91 of file CoolPubSubClient.h.
Referenced by connect(), CoolPubSubClient(), disconnect(), loop(), publish(), publish_P(), readPacket(), setBufferSize(), subscribe(), unsubscribe(), and ~CoolPubSubClient().
uint16_t CoolPubSubClient::buffer_size [private]
Definition at line 92 of file CoolPubSubClient.h.
Referenced by CoolPubSubClient(), getBufferSize(), publish(), readPacket(), setBufferSize(), subscribe(), and unsubscribe().
uint16_t CoolPubSubClient::nextMsgId [private]
Definition at line 93 of file CoolPubSubClient.h.
Referenced by connect(), subscribe(), and unsubscribe().
unsigned long CoolPubSubClient::lastOutActivity [private]
Definition at line 94 of file CoolPubSubClient.h.
Referenced by connect(), disconnect(), loop(), publish_P(), and write().
unsigned long CoolPubSubClient::lastInActivity [private]
Definition at line 95 of file CoolPubSubClient.h.
Referenced by connect(), disconnect(), and loop().
bool CoolPubSubClient::pingOutstanding [private]
Definition at line 96 of file CoolPubSubClient.h.
Referenced by connect(), and loop().
CoolPubSubClient::MQTT_CALLBACK_SIGNATURE [private]
Definition at line 97 of file CoolPubSubClient.h.
IPAddress CoolPubSubClient::ip [private]
Definition at line 103 of file CoolPubSubClient.h.
Referenced by connect(), and setServer().
const char* CoolPubSubClient::domain [private]
Definition at line 104 of file CoolPubSubClient.h.
Referenced by connect(), and setServer().
uint16_t CoolPubSubClient::port [private]
Definition at line 105 of file CoolPubSubClient.h.
Referenced by connect(), and setServer().
Stream* CoolPubSubClient::stream [private]
Definition at line 106 of file CoolPubSubClient.h.
Referenced by CoolPubSubClient(), readPacket(), and setStream().
int CoolPubSubClient::_state [private]
Definition at line 107 of file CoolPubSubClient.h.
Referenced by connect(), connected(), CoolPubSubClient(), disconnect(), loop(), and state().
uint16_t CoolPubSubClient::keepAlive [private]
Definition at line 108 of file CoolPubSubClient.h.
Referenced by connect(), and loop().
uint16_t CoolPubSubClient::socketTimeout [private]
Definition at line 109 of file CoolPubSubClient.h.
Referenced by connect(), readByte(), and setTimeout().
Author
Generated automatically by Doxygen for CoolBoard API from the source code.