.TH "/home/ashiroji/Arduino/libraries/CoolBoard/src/CoolBoardLed.h" 3 "Wed Aug 30 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/src/CoolBoardLed.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include <NeoPixelBus\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCoolBoardLed\fP"
.br
.RI "This class handles the led in the Sensor Board\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
