.TH "CoolBoardActor::state" 3 "Thu Aug 24 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoolBoardActor::state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBactif\fP =0"
.br
.ti -1c
.RI "bool \fBtemporal\fP =0"
.br
.ti -1c
.RI "bool \fBinverted\fP =0"
.br
.ti -1c
.RI "String \fBprimaryType\fP =''"
.br
.ti -1c
.RI "String \fBsecondaryType\fP =''"
.br
.ti -1c
.RI "int \fBrangeLow\fP =0"
.br
.ti -1c
.RI "unsigned long \fBtimeLow\fP =0"
.br
.ti -1c
.RI "int \fBhourLow\fP =0"
.br
.ti -1c
.RI "int \fBminuteLow\fP =0"
.br
.ti -1c
.RI "int \fBrangeHigh\fP =0"
.br
.ti -1c
.RI "unsigned long \fBtimeHigh\fP =0"
.br
.ti -1c
.RI "int \fBhourHigh\fP =0"
.br
.ti -1c
.RI "int \fBminuteHigh\fP =0"
.br
.ti -1c
.RI "unsigned long \fBactifTime\fP =0"
.br
.ti -1c
.RI "unsigned long \fBinactifTime\fP =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 82 of file CoolBoardActor\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CoolBoardActor::state::actif =0"

.PP
Definition at line 84 of file CoolBoardActor\&.h\&.
.SS "unsigned long CoolBoardActor::state::actifTime =0"

.PP
Definition at line 114 of file CoolBoardActor\&.h\&.
.SS "int CoolBoardActor::state::hourHigh =0"

.PP
Definition at line 110 of file CoolBoardActor\&.h\&.
.SS "int CoolBoardActor::state::hourLow =0"

.PP
Definition at line 100 of file CoolBoardActor\&.h\&.
.SS "unsigned long CoolBoardActor::state::inactifTime =0"

.PP
Definition at line 116 of file CoolBoardActor\&.h\&.
.SS "bool CoolBoardActor::state::inverted =0"

.PP
Definition at line 88 of file CoolBoardActor\&.h\&.
.SS "int CoolBoardActor::state::minuteHigh =0"

.PP
Definition at line 112 of file CoolBoardActor\&.h\&.
.SS "int CoolBoardActor::state::minuteLow =0"

.PP
Definition at line 102 of file CoolBoardActor\&.h\&.
.SS "String CoolBoardActor::state::primaryType =''"

.PP
Definition at line 91 of file CoolBoardActor\&.h\&.
.SS "int CoolBoardActor::state::rangeHigh =0"

.PP
Definition at line 106 of file CoolBoardActor\&.h\&.
.SS "int CoolBoardActor::state::rangeLow =0"

.PP
Definition at line 96 of file CoolBoardActor\&.h\&.
.SS "String CoolBoardActor::state::secondaryType =''"

.PP
Definition at line 93 of file CoolBoardActor\&.h\&.
.SS "bool CoolBoardActor::state::temporal =0"

.PP
Definition at line 86 of file CoolBoardActor\&.h\&.
.SS "unsigned long CoolBoardActor::state::timeHigh =0"

.PP
Definition at line 108 of file CoolBoardActor\&.h\&.
.SS "unsigned long CoolBoardActor::state::timeLow =0"

.PP
Definition at line 98 of file CoolBoardActor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
