.TH "CoolSparkFunBME280.cpp" 3 "Mon Sep 11 2017" "CoolBoard API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoolSparkFunBME280.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CoolSparkFunBME280\&.h'\fP
.br
\fC#include 'stdint\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'Wire\&.h'\fP
.br
\fC#include 'SPI\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoard API from the source code\&.
