.TH "CoolSI114X" 3 "Mon Sep 11 2017" "CoolBoard API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoolSI114X
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CoolSI114X\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBBegin\fP (void)"
.br
.ti -1c
.RI "void \fBReset\fP (void)"
.br
.ti -1c
.RI "void \fBDeInit\fP (void)"
.br
.ti -1c
.RI "uint8_t \fBReadParamData\fP (uint8_t Reg)"
.br
.ti -1c
.RI "uint8_t \fBWriteParamData\fP (uint8_t Reg, uint8_t Value)"
.br
.ti -1c
.RI "uint16_t \fBReadVisible\fP (void)"
.br
.ti -1c
.RI "uint16_t \fBReadIR\fP (void)"
.br
.ti -1c
.RI "uint16_t \fBReadProximity\fP (uint8_t PSn)"
.br
.ti -1c
.RI "uint16_t \fBReadUV\fP (void)"
.br
.ti -1c
.RI "uint8_t \fBReadResponseReg\fP (void)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBWriteByte\fP (uint8_t Reg, uint8_t Value)"
.br
.ti -1c
.RI "uint8_t \fBReadByte\fP (uint8_t Reg)"
.br
.ti -1c
.RI "uint16_t \fBReadHalfWord\fP (uint8_t Reg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 170 of file CoolSI114X\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CoolSI114X::Begin (void)"

.PP
Definition at line 91 of file CoolSI114X\&.cpp\&.
.PP
References CoolSI114X_PART_ID, DeInit(), ReadByte(), and Reset()\&.
.PP
Referenced by CoolBoardSensors::begin()\&.
.SS "void CoolSI114X::Reset (void)"

.PP
Definition at line 113 of file CoolSI114X\&.cpp\&.
.PP
References CoolSI114X_COMMAND, CoolSI114X_HW_KEY, CoolSI114X_INT_CFG, CoolSI114X_IRQ_ENABLE, CoolSI114X_IRQ_MODE1, CoolSI114X_IRQ_MODE2, CoolSI114X_IRQ_STATUS, CoolSI114X_MEAS_RATE0, CoolSI114X_MEAS_RATE1, CoolSI114X_RESET, and WriteByte()\&.
.PP
Referenced by Begin()\&.
.SS "void CoolSI114X::DeInit (void)"

.PP
Definition at line 41 of file CoolSI114X\&.cpp\&.
.PP
References CoolSI114X_ADC_COUNTER_511ADCCLK, CoolSI114X_ADC_GAIN_DIV1, CoolSI114X_ADC_MISC_ADC_RAWADC, CoolSI114X_ADC_MISC_HIGHRANGE, CoolSI114X_ADCMUX_LARGE_IR, CoolSI114X_ALS_IR_ADC_COUNTER, CoolSI114X_ALS_IR_ADC_GAIN, CoolSI114X_ALS_IR_ADC_MISC, CoolSI114X_ALS_VIS_ADC_COUNTER, CoolSI114X_ALS_VIS_ADC_GAIN, CoolSI114X_ALS_VIS_ADC_MISC, CoolSI114X_CHLIST, CoolSI114X_CHLIST_ENALSIR, CoolSI114X_CHLIST_ENALSVIS, CoolSI114X_CHLIST_ENPS1, CoolSI114X_CHLIST_ENUV, CoolSI114X_COMMAND, CoolSI114X_INT_CFG, CoolSI114X_INT_CFG_INTOE, CoolSI114X_IRQ_ENABLE, CoolSI114X_IRQEN_ALS, CoolSI114X_LED_CURRENT_22MA, CoolSI114X_MEAS_RATE0, CoolSI114X_PS1_ADCMUX, CoolSI114X_PS_ADC_COUNTER, CoolSI114X_PS_ADC_GAIN, CoolSI114X_PS_ADC_MISC, CoolSI114X_PS_LED21, CoolSI114X_PSALS_AUTO, CoolSI114X_PSLED12_SELECT, CoolSI114X_PSLED12_SELECT_PS1_LED1, CoolSI114X_UCOEFF0, CoolSI114X_UCOEFF1, CoolSI114X_UCOEFF2, CoolSI114X_UCOEFF3, WriteByte(), and WriteParamData()\&.
.PP
Referenced by Begin(), and CoolBoardSensors::end()\&.
.SS "uint8_t CoolSI114X::ReadParamData (uint8_t Reg)"

.PP
Definition at line 170 of file CoolSI114X\&.cpp\&.
.PP
References CoolSI114X_COMMAND, CoolSI114X_QUERY, CoolSI114X_RD, ReadByte(), and WriteByte()\&.
.SS "uint8_t CoolSI114X::WriteParamData (uint8_t Reg, uint8_t Value)"

.PP
Definition at line 179 of file CoolSI114X\&.cpp\&.
.PP
References CoolSI114X_COMMAND, CoolSI114X_RD, CoolSI114X_SET, CoolSI114X_WR, ReadByte(), and WriteByte()\&.
.PP
Referenced by DeInit(), and CoolBoardSensors::read()\&.
.SS "uint16_t CoolSI114X::ReadVisible (void)"

.PP
Definition at line 192 of file CoolSI114X\&.cpp\&.
.PP
References CoolSI114X_ALS_VIS_DATA0, and ReadHalfWord()\&.
.PP
Referenced by CoolBoardSensors::read()\&.
.SS "uint16_t CoolSI114X::ReadIR (void)"

.PP
Definition at line 200 of file CoolSI114X\&.cpp\&.
.PP
References CoolSI114X_ALS_IR_DATA0, and ReadHalfWord()\&.
.PP
Referenced by CoolBoardSensors::read()\&.
.SS "uint16_t CoolSI114X::ReadProximity (uint8_t PSn)"

.PP
Definition at line 208 of file CoolSI114X\&.cpp\&.
.PP
References ReadHalfWord()\&.
.SS "uint16_t CoolSI114X::ReadUV (void)"

.PP
Definition at line 217 of file CoolSI114X\&.cpp\&.
.PP
References CoolSI114X_AUX_DATA0_UVINDEX0, and ReadHalfWord()\&.
.PP
Referenced by CoolBoardSensors::read()\&.
.SS "uint8_t CoolSI114X::ReadResponseReg (void)"

.PP
Definition at line 226 of file CoolSI114X\&.cpp\&.
.PP
References CoolSI114X_RESPONSE, and ReadByte()\&.
.PP
Referenced by CoolBoardSensors::read()\&.
.SS "void CoolSI114X::WriteByte (uint8_t Reg, uint8_t Value)\fC [private]\fP"

.PP
Definition at line 132 of file CoolSI114X\&.cpp\&.
.PP
References CoolSI114X_ADDR\&.
.PP
Referenced by DeInit(), ReadParamData(), Reset(), and WriteParamData()\&.
.SS "uint8_t CoolSI114X::ReadByte (uint8_t Reg)\fC [private]\fP"

.PP
Definition at line 143 of file CoolSI114X\&.cpp\&.
.PP
References CoolSI114X_ADDR\&.
.PP
Referenced by Begin(), ReadParamData(), ReadResponseReg(), and WriteParamData()\&.
.SS "uint16_t CoolSI114X::ReadHalfWord (uint8_t Reg)\fC [private]\fP"

.PP
Definition at line 155 of file CoolSI114X\&.cpp\&.
.PP
References CoolSI114X_ADDR\&.
.PP
Referenced by ReadIR(), ReadProximity(), ReadUV(), and ReadVisible()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoard API from the source code\&.
