CoolAdafruit_ADS1015.cpp
NAME
CoolAdafruit_ADS1015.cpp
SYNOPSIS
#include 'Arduino.h'
#include 'CoolAdafruit_ADS1015.h'
#include <Wire.h>
Functions
static uint8_t i2cread (void)
Abstract away platform differences in Arduino wire library.
static void i2cwrite (uint8_t x)
Abstract away platform differences in Arduino wire library.
static void writeRegister (uint8_t i2cAddress, uint8_t reg, uint16_t value)
Writes 16-bits to the specified destination register.
static uint16_t readRegister (uint8_t i2cAddress, uint8_t reg)
Writes 16-bits to the specified destination register.
Function Documentation
static uint8_t i2cread (void) [static]
Abstract away platform differences in Arduino wire library.
Definition at line 36 of file CoolAdafruit_ADS1015.cpp.
Referenced by readRegister().
static void i2cwrite (uint8_t x) [static]
Abstract away platform differences in Arduino wire library.
Definition at line 49 of file CoolAdafruit_ADS1015.cpp.
Referenced by readRegister(), and writeRegister().
static void writeRegister (uint8_t i2cAddress, uint8_t reg, uint16_t value) [static]
Writes 16-bits to the specified destination register.
Definition at line 62 of file CoolAdafruit_ADS1015.cpp.
References i2cwrite().
Referenced by Adafruit_ADS1015::readADC_Differential_0_1(), Adafruit_ADS1015::readADC_Differential_2_3(), Adafruit_ADS1015::readADC_SingleEnded(), and Adafruit_ADS1015::startComparator_SingleEnded().
static uint16_t readRegister (uint8_t i2cAddress, uint8_t reg) [static]
Writes 16-bits to the specified destination register.
Definition at line 75 of file CoolAdafruit_ADS1015.cpp.
References ADS1015_REG_POINTER_CONVERT, i2cread(), and i2cwrite().
Referenced by Adafruit_ADS1015::getLastConversionResults(), Adafruit_ADS1015::readADC_Differential_0_1(), Adafruit_ADS1015::readADC_Differential_2_3(), and Adafruit_ADS1015::readADC_SingleEnded().
Author
Generated automatically by Doxygen for CoolBoard API from the source code.