.TH "CoolBoardSensors::lightActive" 3 "Tue Aug 22 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoolBoardSensors::lightActive
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBvisible\fP =0"
.br
.ti -1c
.RI "bool \fBir\fP =0"
.br
.ti -1c
.RI "bool \fBuv\fP =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 68 of file CoolBoardSensors\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CoolBoardSensors::lightActive::ir =0"

.PP
Definition at line 71 of file CoolBoardSensors\&.h\&.
.SS "bool CoolBoardSensors::lightActive::uv =0"

.PP
Definition at line 72 of file CoolBoardSensors\&.h\&.
.SS "bool CoolBoardSensors::lightActive::visible =0"

.PP
Definition at line 70 of file CoolBoardSensors\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
