.TH "/home/ashiroji/Arduino/libraries/CoolBoard/src/CoolBoardSensors.h" 3 "Wed Aug 30 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/src/CoolBoardSensors.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include 'internals/CoolSI114X\&.h'\fP
.br
\fC#include 'internals/CoolSparkFunBME280\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCoolBoardSensors\fP"
.br
.RI "This class handles the On-Board Sensors\&. "
.ti -1c
.RI "struct \fBCoolBoardSensors::lightActive\fP"
.br
.ti -1c
.RI "struct \fBCoolBoardSensors::airActive\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
