.TH "/home/ashiroji/Arduino/libraries/CoolBoard/src/CoolWifi.h" 3 "Fri Aug 11 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/src/CoolWifi.h \- \fBCoolWifi\fP Header File\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include <ESP8266WiFi\&.h>\fP
.br
\fC#include <ESP8266WiFiMulti\&.h>\fP
.br
\fC#include <DNSServer\&.h>\fP
.br
\fC#include <ESP8266WebServer\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCoolWifi\fP"
.br
.RI "This class manages the WiFi connection \&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBCoolWifi\fP Header File\&. 


.PP
\fBAuthor:\fP
.RS 4
Mehdi Zemzem 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
27/06/2017 
.RE
.PP

.PP
Definition in file \fBCoolWifi\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
