.TH "/home/ashiroji/Arduino/libraries/CoolBoard/src/CoolFileSystem.cpp" 3 "Mon Aug 14 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/src/CoolFileSystem.cpp \- \fBCoolFileSystem\fP Source File\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <FS\&.h>\fP
.br
\fC#include 'CoolFileSystem\&.h'\fP
.br
\fC#include 'ArduinoJson\&.h'\fP
.br
\fC#include 'Arduino\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP   1"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCoolFileSystem\fP Source File\&. 


.PP
\fBAuthor:\fP
.RS 4
Mehdi Zemzem 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
27/06/2017 
.RE
.PP

.PP
Definition in file \fBCoolFileSystem\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBUG   1"

.PP
Definition at line 16 of file CoolFileSystem\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
