.TH "/home/ashiroji/Arduino/libraries/CoolBoard/src/CoolBoardLed.h" 3 "Tue Aug 22 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/src/CoolBoardLed.h \- \fBCoolBoardLed\fP Header File\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include <NeoPixelBus\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCoolBoardLed\fP"
.br
.RI "This class handles the led in the Sensor Board\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBCoolBoardLed\fP Header File\&. 


.PP
\fBAuthor:\fP
.RS 4
Mehdi Zemzem 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBCoolBoardLed\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
