.TH "ExternalSensor< T >" 3 "Mon Aug 14 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExternalSensor< T > \- template<class SensorClass> class External Sensor: Derived class from \fBBaseExternalSensor\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExternalSensor\&.h>\fP
.PP
Inherits \fBBaseExternalSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExternalSensor\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual float \fBread\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "T \fBsensor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class ExternalSensor< T >"
template<class SensorClass> class External Sensor: Derived class from \fBBaseExternalSensor\fP\&. 

This is the generic Template for an external sensor This class works automatically with sensors that provide the following methods :
.IP "\(bu" 2
constructor(void);
.IP "\(bu" 2
uint8_t/bool \fBbegin(void)\fP;
.IP "\(bu" 2
int \fBread(void)\fP;
.PP
.PP
If your sensor doesn't provide these methods or is not present in the specialized templates feel free to implement your own specializiation, following the provided generic template , or contact us and we will be glad to expand our list of supported external sensors 
.PP
Definition at line 113 of file ExternalSensor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBExternalSensor\fP< T >::\fBExternalSensor\fP ()\fC [inline]\fP"
Generic Constructor 
.PP
Definition at line 119 of file ExternalSensor\&.h\&.
.PP
.nf
120     {
121     
122     #if DEBUGExternal == 1 
123 
124         Serial\&.println( "ExternalSensor <Generic> Constructor" );
125         Serial\&.println();
126     
127     #endif
128 
129         sensor();
130     }
.fi
.SH "Member Function Documentation"
.PP 
.SS "template<class T > virtual uint8_t \fBExternalSensor\fP< T >::begin (void)\fC [inline]\fP, \fC [virtual]\fP"
Generic begin method 
.PP
Reimplemented from \fBBaseExternalSensor\fP\&.
.PP
Definition at line 137 of file ExternalSensor\&.h\&.
.PP
.nf
138     {
139     
140     #if DEBUGExternal == 1 
141 
142         Serial\&.println( "ExternalSensor <Generic> begin()" );
143         Serial\&.println();
144     
145     #endif
146 
147         return(sensor\&.begin() ); 
148     }
.fi
.SS "template<class T > virtual float \fBExternalSensor\fP< T >::read (void)\fC [inline]\fP, \fC [virtual]\fP"
Generic read method 
.PP
Reimplemented from \fBBaseExternalSensor\fP\&.
.PP
Definition at line 153 of file ExternalSensor\&.h\&.
.PP
.nf
154     {
155     
156     #if DEBUGExternal == 1 
157 
158         Serial\&.println( "ExternalSensor <Generic> read() " );
159         Serial\&.println();
160         
161     #endif
162 
163         return(sensor\&.read());
164     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<class T > T \fBExternalSensor\fP< T >::sensor\fC [private]\fP"

.PP
Definition at line 170 of file ExternalSensor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
