.TH "ExternalSensor< DallasTemperature >" 3 "Wed Aug 30 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExternalSensor< DallasTemperature > \- DallasTemperature Specialization Class This is the template specialization for the Dallas Temperature sensor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExternalSensor\&.h>\fP
.PP
Inherits \fBBaseExternalSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExternalSensor\fP (OneWire *\fBoneWire\fP)"
.br
.ti -1c
.RI "virtual uint8_t \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual float \fBread\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "DallasTemperature \fBsensor\fP"
.br
.ti -1c
.RI "DeviceAddress \fBdallasAddress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
class ExternalSensor< DallasTemperature >"
DallasTemperature Specialization Class This is the template specialization for the Dallas Temperature sensor\&. 
.PP
Definition at line 330 of file ExternalSensor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBExternalSensor\fP< DallasTemperature >::\fBExternalSensor\fP (OneWire * oneWire)\fC [inline]\fP"
\fBExternalSensor()\fP: DallasTemperature specific constructor 
.PP
Definition at line 337 of file ExternalSensor\&.h\&.
.PP
.nf
338     {
339         
340     #if DEBUGExternal == 1 
341 
342         Serial\&.println( "ExternalSensor <DallasTemperature> constructor" );
343         Serial\&.println();
344     
345     #endif
346         sensor=DallasTemperature(oneWire);
347     }
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual uint8_t \fBExternalSensor\fP< DallasTemperature >::begin (void)\fC [inline]\fP, \fC [virtual]\fP"
\fBbegin()\fP: DallasTemperature specific begin method
.PP
\fBReturns:\fP
.RS 4
true if successful 
.RE
.PP

.PP
Reimplemented from \fBBaseExternalSensor\fP\&.
.PP
Definition at line 355 of file ExternalSensor\&.h\&.
.PP
.nf
356     {
357     
358     #if DEBUGExternal == 1 
359 
360         Serial\&.println( "ExternalSensor <DallasTemperature> begin()" );
361         Serial\&.println();
362     
363     #endif
364 
365         sensor\&.begin(); 
366         delay(5);
367         sensor\&.getAddress(this->dallasAddress, 0);   
368         return(true);
369     }
.fi
.SS "virtual float \fBExternalSensor\fP< DallasTemperature >::read (void)\fC [inline]\fP, \fC [virtual]\fP"
\fBread()\fP: DallasTemperature specific read method
.PP
\fBReturns:\fP
.RS 4
the temperature in °C 
.RE
.PP

.PP
Reimplemented from \fBBaseExternalSensor\fP\&.
.PP
Definition at line 376 of file ExternalSensor\&.h\&.
.PP
.nf
377     {
378 
379         sensor\&.requestTemperatures(); // Send the command to get temperatures
380         float result=(float) sensor\&.getTempCByIndex(0);
381     #if DEBUGExternal == 1 
382 
383         Serial\&.println( "ExternalSensor <DallasTemperature> read()" );
384         Serial\&.println();
385 
386         Serial\&.print("Requesting temperature\&.\&.\&.");
387 
388         Serial\&.print( "temperature : ");
389         Serial\&.print( result );
390         Serial\&.print( "°C" );
391         Serial\&.println();
392     
393     #endif
394         
395         return( result );
396     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "DeviceAddress \fBExternalSensor\fP< DallasTemperature >::dallasAddress\fC [private]\fP"

.PP
Definition at line 402 of file ExternalSensor\&.h\&.
.SS "DallasTemperature \fBExternalSensor\fP< DallasTemperature >::sensor\fC [private]\fP"

.PP
Definition at line 401 of file ExternalSensor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
