.TH "ExternalSensor< DallasTemperature >" 3 "Wed Aug 30 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExternalSensor< DallasTemperature > \- DallasTemperature Specialization Class This is the template specialization for the Dallas Temperature sensor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExternalSensor\&.h>\fP
.PP
Inherits \fBBaseExternalSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExternalSensor\fP (OneWire *\fBoneWire\fP)"
.br
.ti -1c
.RI "virtual uint8_t \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual float \fBread\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "DallasTemperature \fBsensor\fP"
.br
.ti -1c
.RI "DeviceAddress \fBdallasAddress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
class ExternalSensor< DallasTemperature >"
DallasTemperature Specialization Class This is the template specialization for the Dallas Temperature sensor\&. 
.PP
Definition at line 329 of file ExternalSensor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBExternalSensor\fP< DallasTemperature >::\fBExternalSensor\fP (OneWire * oneWire)\fC [inline]\fP"
\fBExternalSensor()\fP: DallasTemperature specific constructor 
.PP
Definition at line 336 of file ExternalSensor\&.h\&.
.PP
.nf
337     {
338         
339     #if DEBUGExternal == 1 
340 
341         Serial\&.println( "ExternalSensor <DallasTemperature> constructor" );
342         Serial\&.println();
343     
344     #endif
345         sensor=DallasTemperature(oneWire);
346     }
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual uint8_t \fBExternalSensor\fP< DallasTemperature >::begin (void)\fC [inline]\fP, \fC [virtual]\fP"
\fBbegin()\fP: DallasTemperature specific begin method
.PP
\fBReturns:\fP
.RS 4
true if successful 
.RE
.PP

.PP
Reimplemented from \fBBaseExternalSensor\fP\&.
.PP
Definition at line 354 of file ExternalSensor\&.h\&.
.PP
.nf
355     {
356     
357     #if DEBUGExternal == 1 
358 
359         Serial\&.println( "ExternalSensor <DallasTemperature> begin()" );
360         Serial\&.println();
361     
362     #endif
363 
364         sensor\&.begin(); 
365         delay(5);
366         sensor\&.getAddress(this->dallasAddress, 0);   
367         return(true);
368     }
.fi
.SS "virtual float \fBExternalSensor\fP< DallasTemperature >::read (void)\fC [inline]\fP, \fC [virtual]\fP"
\fBread()\fP: DallasTemperature specific read method
.PP
\fBReturns:\fP
.RS 4
the temperature in °C 
.RE
.PP

.PP
Reimplemented from \fBBaseExternalSensor\fP\&.
.PP
Definition at line 375 of file ExternalSensor\&.h\&.
.PP
.nf
376     {
377 
378         sensor\&.requestTemperatures(); // Send the command to get temperatures
379         float result=(float) sensor\&.getTempCByIndex(0);
380     #if DEBUGExternal == 1 
381 
382         Serial\&.println( "ExternalSensor <DallasTemperature> read()" );
383         Serial\&.println();
384 
385         Serial\&.print("Requesting temperature\&.\&.\&.");
386 
387         Serial\&.print( "temperature : ");
388         Serial\&.print( result );
389         Serial\&.print( "°C" );
390         Serial\&.println();
391     
392     #endif
393         
394         return( result );
395     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "DeviceAddress \fBExternalSensor\fP< DallasTemperature >::dallasAddress\fC [private]\fP"

.PP
Definition at line 401 of file ExternalSensor\&.h\&.
.SS "DallasTemperature \fBExternalSensor\fP< DallasTemperature >::sensor\fC [private]\fP"

.PP
Definition at line 400 of file ExternalSensor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
