.TH "ExternalSensor< Adafruit_TCS34725 >" 3 "Mon Sep 11 2017" "CoolBoard API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExternalSensor< Adafruit_TCS34725 > \- \fBAdafruit_TCS34725\fP Specialization Class This is the template specialization for the Adafruit RGB Sensor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExternalSensor\&.h>\fP
.PP
Inherits \fBBaseExternalSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExternalSensor\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual float \fBread\fP (uint16_t *r, uint16_t *g, uint16_t *b, uint16_t *c, uint16_t *colorTemp, uint16_t *lux)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBAdafruit_TCS34725\fP \fBsensor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
class ExternalSensor< Adafruit_TCS34725 >"
\fBAdafruit_TCS34725\fP Specialization Class This is the template specialization for the Adafruit RGB Sensor\&. 
.PP
Definition at line 428 of file ExternalSensor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBExternalSensor\fP< \fBAdafruit_TCS34725\fP >::\fBExternalSensor\fP ()\fC [inline]\fP"
\fBExternalSensor()\fP: \fBAdafruit_TCS34725\fP specific constructor 
.PP
Definition at line 435 of file ExternalSensor\&.h\&.
.PP
References ExternalSensor< T >::sensor, TCS34725_GAIN_1X, and TCS34725_INTEGRATIONTIME_700MS\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual uint8_t \fBExternalSensor\fP< \fBAdafruit_TCS34725\fP >::begin (void)\fC [inline]\fP, \fC [virtual]\fP"
\fBbegin()\fP: \fBAdafruit_TCS34725\fP specific begin method
.PP
\fBReturns:\fP
.RS 4
true if successful 
.RE
.PP

.PP
Reimplemented from \fBBaseExternalSensor\fP\&.
.PP
Definition at line 455 of file ExternalSensor\&.h\&.
.PP
References ExternalSensor< T >::sensor\&.
.SS "virtual float \fBExternalSensor\fP< \fBAdafruit_TCS34725\fP >::read (uint16_t * r, uint16_t * g, uint16_t * b, uint16_t * c, uint16_t * colorTemp, uint16_t * lux)\fC [inline]\fP, \fC [virtual]\fP"
\fBread(uint16_t *r,uint16_t *g,uint16_t *b,uint16_t *c,uint16_t *colorTemp,uint16_t *lux)\fP: \fBAdafruit_TCS34725\fP specific read method
.PP
modifies the R,G,B,C,lux,ColorTemp input variables 
.PP
Reimplemented from \fBBaseExternalSensor\fP\&.
.PP
Definition at line 487 of file ExternalSensor\&.h\&.
.PP
References ExternalSensor< T >::sensor\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAdafruit_TCS34725\fP \fBExternalSensor\fP< \fBAdafruit_TCS34725\fP >::sensor\fC [private]\fP"

.PP
Definition at line 525 of file ExternalSensor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoard API from the source code\&.
