.TH "/home/ashiroji/Arduino/libraries/CoolBoard/src/ExternalSensors.h" 3 "Wed Aug 30 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/src/ExternalSensors.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include 'ExternalSensor\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExternalSensors\fP"
.br
.RI "This class handles the external sensors run time defintion , configuartion and actions\&. "
.ti -1c
.RI "struct \fBExternalSensors::sensor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
