.TH "ExternalSensors" 3 "Mon Sep 11 2017" "CoolBoard API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExternalSensors \- This class handles the external sensors run time defintion , configuartion and actions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExternalSensors\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsensor\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBbegin\fP ()"
.br
.ti -1c
.RI "String \fBread\fP ()"
.br
.ti -1c
.RI "bool \fBconfig\fP ()"
.br
.ti -1c
.RI "bool \fBconfig\fP (String reference[], String type[], uint8_t address[], int \fBsensorsNumber\fP)"
.br
.ti -1c
.RI "void \fBprintConf\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "struct \fBExternalSensors::sensor\fP \fBsensors\fP [50]"
.br
.ti -1c
.RI "int \fBsensorsNumber\fP =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class handles the external sensors run time defintion , configuartion and actions\&. 
.PP
Definition at line 47 of file ExternalSensors\&.h\&.
.SH "Class Documentation"
.PP 
.SH "struct ExternalSensors::sensor"
.PP 
Array of 50 External Sensors
.PP
An External Sensor is described by :
.PP
\fBsensor\&.reference\fP : the sensor's reference ( \fBNDIR_I2C\fP\&.\&.\&.)
.PP
\fBsensor\&.type\fP : the sensor's Type ( CO2 , Temperature , \&.\&.\&.\&. )
.PP
\fBsensor\&.address\fP : the sensor's Address if it has one
.PP
\fBsensor\&.exSensor\fP : pointer to the dynmacially instanciated sensor 
.PP
Definition at line 76 of file ExternalSensors\&.h\&.
.PP
\fBClass Members:\fP
.RS 4
String \fIreference\fP 
.br
.PP
String \fItype\fP 
.br
.PP
uint8_t \fIaddress\fP 
.br
.PP
\fBBaseExternalSensor\fP * \fIexSensor\fP 
.br
.PP
.RE
.PP
.SH "Member Function Documentation"
.PP 
.SS "void ExternalSensors::begin (void)"
\fBExternalSensors::begin()\fP: This method is provided to initialise the external sensors\&. 
.PP
Definition at line 56 of file ExternalSensors\&.cpp\&.
.PP
References BaseExternalSensor::begin(), ExternalSensors::sensor::exSensor, oneWire(), BaseExternalSensor::read(), sensors, and sensorsNumber\&.
.PP
Referenced by CoolBoard::begin()\&.
.SS "String ExternalSensors::read (void)"
\fBExternalSensors::read()\fP: This method is provided to read the data from the external sensors
.PP
\fBReturns:\fP
.RS 4
json string that contains the sensors data 
.RE
.PP

.PP
Definition at line 110 of file ExternalSensors\&.cpp\&.
.PP
References ExternalSensors::sensor::exSensor, BaseExternalSensor::read(), sensors, sensorsNumber, and ExternalSensors::sensor::type\&.
.PP
Referenced by CoolBoard::readSensors()\&.
.SS "bool ExternalSensors::config ()"
\fBExternalSensors::config()\fP: This method is provided to configure the externalSensors through a configuration file
.PP
\fBReturns:\fP
.RS 4
true if successful,false otherwise 
.RE
.PP

.PP
Definition at line 211 of file ExternalSensors\&.cpp\&.
.PP
References ExternalSensors::sensor::address, ExternalSensors::sensor::reference, sensors, sensorsNumber, and ExternalSensors::sensor::type\&.
.PP
Referenced by CoolBoard::begin()\&.
.SS "bool ExternalSensors::config (String reference[], String type[], uint8_t address[], int sensorsNumber)"
\fBExternalSensors::config(String reference[],String type[],uint8_t address[],int sensorsNumber)\fP: This method is provided to configure the externalSensors without a configuration file
.PP
\fBReturns:\fP
.RS 4
true if successful,false otherwise 
.RE
.PP

.PP
Definition at line 376 of file ExternalSensors\&.cpp\&.
.PP
References ExternalSensors::sensor::address, ExternalSensors::sensor::reference, sensors, sensorsNumber, and ExternalSensors::sensor::type\&.
.SS "void ExternalSensors::printConf ()"
\fBExternalSensors::printConf()\fP: This method is provided to print the configuration to the Serial Monitor 
.PP
Definition at line 419 of file ExternalSensors\&.cpp\&.
.PP
References sensors, and sensorsNumber\&.
.PP
Referenced by CoolBoard::begin()\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBExternalSensors::sensor\fP ExternalSensors::sensors[50]\fC [private]\fP"

.PP
Referenced by begin(), config(), printConf(), and read()\&.
.SS "int ExternalSensors::sensorsNumber =0\fC [private]\fP"
External Sensors Number Maximum is 50 
.PP
Definition at line 88 of file ExternalSensors\&.h\&.
.PP
Referenced by begin(), config(), printConf(), and read()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoard API from the source code\&.
