.TH "/home/ashiroji/Arduino/libraries/CoolBoard/src/Jetpack.h" 3 "Wed Aug 30 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/src/Jetpack.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJetpack\fP"
.br
.RI "This class manages the \fBJetpack\fP shield\&. "
.ti -1c
.RI "struct \fBJetpack::state\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
