.TH "Jetpack::state" 3 "Thu Aug 24 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Jetpack::state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBactif\fP =0"
.br
.ti -1c
.RI "bool \fBtemporal\fP =0"
.br
.ti -1c
.RI "bool \fBinverted\fP =0"
.br
.ti -1c
.RI "String \fBprimaryType\fP =''"
.br
.ti -1c
.RI "String \fBsecondaryType\fP =''"
.br
.ti -1c
.RI "int \fBrangeLow\fP =0"
.br
.ti -1c
.RI "unsigned long \fBtimeLow\fP =0"
.br
.ti -1c
.RI "int \fBhourLow\fP =0"
.br
.ti -1c
.RI "int \fBminuteLow\fP =0"
.br
.ti -1c
.RI "int \fBrangeHigh\fP =0"
.br
.ti -1c
.RI "unsigned long \fBtimeHigh\fP =0"
.br
.ti -1c
.RI "int \fBhourHigh\fP =0"
.br
.ti -1c
.RI "int \fBminuteHigh\fP =0"
.br
.ti -1c
.RI "unsigned long \fBactifTime\fP =0"
.br
.ti -1c
.RI "unsigned long \fBinactifTime\fP =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 86 of file Jetpack\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Jetpack::state::actif =0"

.PP
Definition at line 88 of file Jetpack\&.h\&.
.SS "unsigned long Jetpack::state::actifTime =0"

.PP
Definition at line 118 of file Jetpack\&.h\&.
.SS "int Jetpack::state::hourHigh =0"

.PP
Definition at line 114 of file Jetpack\&.h\&.
.SS "int Jetpack::state::hourLow =0"

.PP
Definition at line 104 of file Jetpack\&.h\&.
.SS "unsigned long Jetpack::state::inactifTime =0"

.PP
Definition at line 120 of file Jetpack\&.h\&.
.SS "bool Jetpack::state::inverted =0"

.PP
Definition at line 92 of file Jetpack\&.h\&.
.SS "int Jetpack::state::minuteHigh =0"

.PP
Definition at line 116 of file Jetpack\&.h\&.
.SS "int Jetpack::state::minuteLow =0"

.PP
Definition at line 106 of file Jetpack\&.h\&.
.SS "String Jetpack::state::primaryType =''"

.PP
Definition at line 95 of file Jetpack\&.h\&.
.SS "int Jetpack::state::rangeHigh =0"

.PP
Definition at line 110 of file Jetpack\&.h\&.
.SS "int Jetpack::state::rangeLow =0"

.PP
Definition at line 100 of file Jetpack\&.h\&.
.SS "String Jetpack::state::secondaryType =''"

.PP
Definition at line 97 of file Jetpack\&.h\&.
.SS "bool Jetpack::state::temporal =0"

.PP
Definition at line 90 of file Jetpack\&.h\&.
.SS "unsigned long Jetpack::state::timeHigh =0"

.PP
Definition at line 112 of file Jetpack\&.h\&.
.SS "unsigned long Jetpack::state::timeLow =0"

.PP
Definition at line 102 of file Jetpack\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
