WiFiManager
NAME
WiFiManager
SYNOPSIS
#include <WiFiManagerReadFileButton.h>
Public Member Functions
WiFiManager ()
boolean autoConnect ()
boolean autoConnect (char const *apName, char const *apPassword=NULL)
boolean startConfigPortal ()
boolean startConfigPortal (char const *apName, char const *apPassword=NULL)
String getConfigPortalSSID ()
void resetSettings ()
void setConfigPortalTimeout (unsigned long seconds)
void setTimeout (unsigned long seconds)
void setConnectTimeout (unsigned long seconds)
void setDebugOutput (boolean debug)
void setMinimumSignalQuality (int quality=8)
void setAPStaticIPConfig (IPAddress ip, IPAddress gw, IPAddress sn)
void setSTAStaticIPConfig (IPAddress ip, IPAddress gw, IPAddress sn)
void setAPCallback (void(*func)(WiFiManager *))
void setSaveConfigCallback (void(*func)(void))
void addParameter (WiFiManagerParameter *p)
void setBreakAfterConfig (boolean shouldBreak)
void setCustomHeadElement (const char *element)
void setRemoveDuplicateAPs (boolean removeDuplicates)
Private Member Functions
void setupConfigPortal ()
void startWPS ()
int connectWifi (String ssid, String pass)
uint8_t waitForConnectResult ()
void handleRoot ()
void handleWifi (boolean scan)
void handleWifiSave ()
void handleInfo ()
void handleReset ()
void handleNotFound ()
void handle204 ()
bool handleFileRead (String path)
boolean captivePortal ()
String getContentType (String filename)
int getRSSIasQuality (int RSSI)
boolean isIp (String str)
String toStringIp (IPAddress ip)
template<typename Generic > void DEBUG_WM (Generic text)
template<class T > auto optionalIPFromString (T *obj, const char *s) -> decltype(obj->fromString(s))
auto optionalIPFromString (...) -> bool
Private Attributes
std::unique_ptr< DNSServer > dnsServer
std::unique_ptr< ESP8266WebServer > server
const char * _apName = 'no-net'
const char * _apPassword = NULL
String _ssid = ''
String _pass = ''
unsigned long _configPortalTimeout = 0
unsigned long _connectTimeout = 0
unsigned long _configPortalStart = 0
IPAddress _ap_static_ip
IPAddress _ap_static_gw
IPAddress _ap_static_sn
IPAddress _sta_static_ip
IPAddress _sta_static_gw
IPAddress _sta_static_sn
int _paramsCount = 0
int _minimumQuality = -1
boolean _removeDuplicateAPs = true
boolean _shouldBreakAfterConfig = false
boolean _tryWPS = false
const char * _customHeadElement = ''
int status = WL_IDLE_STATUS
const byte DNS_PORT = 53
boolean connect
boolean _debug = true
void(* _apcallback )(WiFiManager *) = NULL
void(* _savecallback )(void) = NULL
WiFiManagerParameter * _params [WIFI_MANAGER_MAX_PARAMS]
Detailed Description
Definition at line 67 of file WiFiManagerReadFileButton.h.
Constructor & Destructor Documentation
WiFiManager::WiFiManager ()
Definition at line 65 of file WiFiManagerReadFileButton.cpp.
Member Function Documentation
boolean WiFiManager::autoConnect ()
Definition at line 129 of file WiFiManagerReadFileButton.cpp.
Referenced by CoolWifi::connectAP().
boolean WiFiManager::autoConnect (char const * apName, char const * apPassword = NULL)
Definition at line 134 of file WiFiManagerReadFileButton.cpp.
References connectWifi(), DEBUG_WM(), and startConfigPortal().
boolean WiFiManager::startConfigPortal ()
Definition at line 155 of file WiFiManagerReadFileButton.cpp.
Referenced by autoConnect().
boolean WiFiManager::startConfigPortal (char const * apName, char const * apPassword = NULL)
Definition at line 160 of file WiFiManagerReadFileButton.cpp.
References _apcallback, _apName, _apPassword, _configPortalStart, _configPortalTimeout, _pass, _savecallback, _shouldBreakAfterConfig, _ssid, connect, connectWifi(), DEBUG_WM(), dnsServer, server, and setupConfigPortal().
String WiFiManager::getConfigPortalSSID ()
Definition at line 314 of file WiFiManagerReadFileButton.cpp.
References _apName.
void WiFiManager::resetSettings ()
Definition at line 318 of file WiFiManagerReadFileButton.cpp.
References DEBUG_WM().
void WiFiManager::setConfigPortalTimeout (unsigned long seconds)
Definition at line 328 of file WiFiManagerReadFileButton.cpp.
References _configPortalTimeout.
Referenced by setTimeout().
void WiFiManager::setTimeout (unsigned long seconds)
Definition at line 324 of file WiFiManagerReadFileButton.cpp.
References setConfigPortalTimeout().
Referenced by CoolWifi::connectAP().
void WiFiManager::setConnectTimeout (unsigned long seconds)
Definition at line 332 of file WiFiManagerReadFileButton.cpp.
References _connectTimeout.
void WiFiManager::setDebugOutput (boolean debug)
Definition at line 336 of file WiFiManagerReadFileButton.cpp.
References _debug.
void WiFiManager::setMinimumSignalQuality (int quality = 8)
Definition at line 352 of file WiFiManagerReadFileButton.cpp.
References _minimumQuality.
void WiFiManager::setAPStaticIPConfig (IPAddress ip, IPAddress gw, IPAddress sn)
Definition at line 340 of file WiFiManagerReadFileButton.cpp.
References _ap_static_gw, _ap_static_ip, and _ap_static_sn.
void WiFiManager::setSTAStaticIPConfig (IPAddress ip, IPAddress gw, IPAddress sn)
Definition at line 346 of file WiFiManagerReadFileButton.cpp.
References _sta_static_gw, _sta_static_ip, and _sta_static_sn.
void WiFiManager::setAPCallback (void(*)(WiFiManager *) func)
Definition at line 758 of file WiFiManagerReadFileButton.cpp.
References _apcallback.
void WiFiManager::setSaveConfigCallback (void(*)(void) func)
Definition at line 763 of file WiFiManagerReadFileButton.cpp.
References _savecallback.
void WiFiManager::addParameter (WiFiManagerParameter * p)
Definition at line 68 of file WiFiManagerReadFileButton.cpp.
References _params, _paramsCount, DEBUG_WM(), and WiFiManagerParameter::getID().
void WiFiManager::setBreakAfterConfig (boolean shouldBreak)
Definition at line 356 of file WiFiManagerReadFileButton.cpp.
References _shouldBreakAfterConfig.
void WiFiManager::setCustomHeadElement (const char * element)
Definition at line 768 of file WiFiManagerReadFileButton.cpp.
References _customHeadElement.
void WiFiManager::setRemoveDuplicateAPs (boolean removeDuplicates)
Definition at line 773 of file WiFiManagerReadFileButton.cpp.
References _removeDuplicateAPs.
Referenced by CoolWifi::connectAP().
void WiFiManager::setupConfigPortal () [private]
Definition at line 75 of file WiFiManagerReadFileButton.cpp.
References _ap_static_gw, _ap_static_ip, _ap_static_sn, _apName, _apPassword, _configPortalStart, DEBUG_WM(), DNS_PORT, dnsServer, handleFileRead(), handleInfo(), handleNotFound(), handleReset(), handleRoot(), handleWifi(), handleWifiSave(), and server.
Referenced by startConfigPortal().
void WiFiManager::startWPS () [private]
Definition at line 288 of file WiFiManagerReadFileButton.cpp.
References DEBUG_WM().
Referenced by connectWifi().
int WiFiManager::connectWifi (String ssid, String pass) [private]
Definition at line 222 of file WiFiManagerReadFileButton.cpp.
References _sta_static_gw, _sta_static_ip, _sta_static_sn, _tryWPS, DEBUG_WM(), startWPS(), and waitForConnectResult().
Referenced by autoConnect(), and startConfigPortal().
uint8_t WiFiManager::waitForConnectResult () [private]
Definition at line 265 of file WiFiManagerReadFileButton.cpp.
References _connectTimeout, DEBUG_WM(), and status.
Referenced by connectWifi().
void WiFiManager::handleRoot () [private]
Handle root or redirect to captive portal
Definition at line 361 of file WiFiManagerReadFileButton.cpp.
References _apName, _customHeadElement, captivePortal(), DEBUG_WM(), and server.
Referenced by setupConfigPortal().
void WiFiManager::handleWifi (boolean scan) [private]
Wifi config page handler
Definition at line 385 of file WiFiManagerReadFileButton.cpp.
References _customHeadElement, _minimumQuality, _params, _paramsCount, _removeDuplicateAPs, _sta_static_gw, _sta_static_ip, _sta_static_sn, DEBUG_WM(), WiFiManagerParameter::getCustomHTML(), getRSSIasQuality(), and server.
Referenced by setupConfigPortal().
void WiFiManager::handleWifiSave () [private]
Handle the WLAN save form and redirect to WLAN config page again
Definition at line 540 of file WiFiManagerReadFileButton.cpp.
References _customHeadElement, _params, _paramsCount, _pass, _ssid, _sta_static_gw, _sta_static_ip, _sta_static_sn, connect, DEBUG_WM(), optionalIPFromString(), and server.
Referenced by setupConfigPortal().
void WiFiManager::handleInfo () [private]
Handle the info page
Definition at line 598 of file WiFiManagerReadFileButton.cpp.
References _customHeadElement, DEBUG_WM(), and server.
Referenced by setupConfigPortal().
void WiFiManager::handleReset () [private]
Handle the reset page
Definition at line 638 of file WiFiManagerReadFileButton.cpp.
References _customHeadElement, DEBUG_WM(), and server.
Referenced by setupConfigPortal().
void WiFiManager::handleNotFound () [private]
Definition at line 722 of file WiFiManagerReadFileButton.cpp.
References captivePortal(), and server.
Referenced by setupConfigPortal().
void WiFiManager::handle204 () [private]
bool WiFiManager::handleFileRead (String path) [private]
Handle the read file button
Definition at line 676 of file WiFiManagerReadFileButton.cpp.
References DEBUG_WM(), getContentType(), and server.
Referenced by setupConfigPortal().
boolean WiFiManager::captivePortal () [private]
Redirect to captive portal if we got a request for another domain. Return true in that case so the page handler do not try to handle the request again.
Definition at line 746 of file WiFiManagerReadFileButton.cpp.
References DEBUG_WM(), isIp(), server, and toStringIp().
Referenced by handleNotFound(), and handleRoot().
String WiFiManager::getContentType (String filename) [private]
Definition at line 821 of file WiFiManagerReadFileButton.cpp.
References server.
Referenced by handleFileRead().
int WiFiManager::getRSSIasQuality (int RSSI) [private]
Definition at line 787 of file WiFiManagerReadFileButton.cpp.
Referenced by handleWifi().
boolean WiFiManager::isIp (String str) [private]
Is this an IP?
Definition at line 801 of file WiFiManagerReadFileButton.cpp.
Referenced by captivePortal().
String WiFiManager::toStringIp (IPAddress ip) [private]
IP to String?
Definition at line 812 of file WiFiManagerReadFileButton.cpp.
Referenced by captivePortal().
template<typename Generic > void WiFiManager::DEBUG_WM (Generic text) [private]
Definition at line 780 of file WiFiManagerReadFileButton.cpp.
References _debug.
Referenced by addParameter(), autoConnect(), captivePortal(), connectWifi(), handleFileRead(), handleInfo(), handleReset(), handleRoot(), handleWifi(), handleWifiSave(), optionalIPFromString(), resetSettings(), setupConfigPortal(), startConfigPortal(), startWPS(), and waitForConnectResult().
template<class T > auto WiFiManager::optionalIPFromString (T * obj, const char * s) -> decltype( obj->fromString(s) ) [inline], [private]
Definition at line 192 of file WiFiManagerReadFileButton.h.
Referenced by handleWifiSave().
auto WiFiManager::optionalIPFromString ( ...) -> bool [inline], [private]
Definition at line 195 of file WiFiManagerReadFileButton.h.
References DEBUG_WM().
Member Data Documentation
std::unique_ptr<DNSServer> WiFiManager::dnsServer [private]
Definition at line 117 of file WiFiManagerReadFileButton.h.
Referenced by setupConfigPortal(), and startConfigPortal().
std::unique_ptr<ESP8266WebServer> WiFiManager::server [private]
Definition at line 118 of file WiFiManagerReadFileButton.h.
Referenced by captivePortal(), getContentType(), handleFileRead(), handleInfo(), handleNotFound(), handleReset(), handleRoot(), handleWifi(), handleWifiSave(), setupConfigPortal(), and startConfigPortal().
const char* WiFiManager::_apName = 'no-net' [private]
Definition at line 128 of file WiFiManagerReadFileButton.h.
Referenced by getConfigPortalSSID(), handleRoot(), setupConfigPortal(), and startConfigPortal().
const char* WiFiManager::_apPassword = NULL [private]
Definition at line 129 of file WiFiManagerReadFileButton.h.
Referenced by setupConfigPortal(), and startConfigPortal().
String WiFiManager::_ssid = '' [private]
Definition at line 130 of file WiFiManagerReadFileButton.h.
Referenced by handleWifiSave(), and startConfigPortal().
String WiFiManager::_pass = '' [private]
Definition at line 131 of file WiFiManagerReadFileButton.h.
Referenced by handleWifiSave(), and startConfigPortal().
unsigned long WiFiManager::_configPortalTimeout = 0 [private]
Definition at line 132 of file WiFiManagerReadFileButton.h.
Referenced by setConfigPortalTimeout(), and startConfigPortal().
unsigned long WiFiManager::_connectTimeout = 0 [private]
Definition at line 133 of file WiFiManagerReadFileButton.h.
Referenced by setConnectTimeout(), and waitForConnectResult().
unsigned long WiFiManager::_configPortalStart = 0 [private]
Definition at line 134 of file WiFiManagerReadFileButton.h.
Referenced by setupConfigPortal(), and startConfigPortal().
IPAddress WiFiManager::_ap_static_ip [private]
Definition at line 136 of file WiFiManagerReadFileButton.h.
Referenced by setAPStaticIPConfig(), and setupConfigPortal().
IPAddress WiFiManager::_ap_static_gw [private]
Definition at line 137 of file WiFiManagerReadFileButton.h.
Referenced by setAPStaticIPConfig(), and setupConfigPortal().
IPAddress WiFiManager::_ap_static_sn [private]
Definition at line 138 of file WiFiManagerReadFileButton.h.
Referenced by setAPStaticIPConfig(), and setupConfigPortal().
IPAddress WiFiManager::_sta_static_ip [private]
Definition at line 139 of file WiFiManagerReadFileButton.h.
Referenced by connectWifi(), handleWifi(), handleWifiSave(), and setSTAStaticIPConfig().
IPAddress WiFiManager::_sta_static_gw [private]
Definition at line 140 of file WiFiManagerReadFileButton.h.
Referenced by connectWifi(), handleWifi(), handleWifiSave(), and setSTAStaticIPConfig().
IPAddress WiFiManager::_sta_static_sn [private]
Definition at line 141 of file WiFiManagerReadFileButton.h.
Referenced by connectWifi(), handleWifi(), handleWifiSave(), and setSTAStaticIPConfig().
int WiFiManager::_paramsCount = 0 [private]
Definition at line 143 of file WiFiManagerReadFileButton.h.
Referenced by addParameter(), handleWifi(), and handleWifiSave().
int WiFiManager::_minimumQuality = -1 [private]
Definition at line 144 of file WiFiManagerReadFileButton.h.
Referenced by handleWifi(), and setMinimumSignalQuality().
boolean WiFiManager::_removeDuplicateAPs = true [private]
Definition at line 145 of file WiFiManagerReadFileButton.h.
Referenced by handleWifi(), and setRemoveDuplicateAPs().
boolean WiFiManager::_shouldBreakAfterConfig = false [private]
Definition at line 146 of file WiFiManagerReadFileButton.h.
Referenced by setBreakAfterConfig(), and startConfigPortal().
boolean WiFiManager::_tryWPS = false [private]
Definition at line 147 of file WiFiManagerReadFileButton.h.
Referenced by connectWifi().
const char* WiFiManager::_customHeadElement = '' [private]
Definition at line 149 of file WiFiManagerReadFileButton.h.
Referenced by handleInfo(), handleReset(), handleRoot(), handleWifi(), handleWifiSave(), and setCustomHeadElement().
int WiFiManager::status = WL_IDLE_STATUS [private]
Definition at line 154 of file WiFiManagerReadFileButton.h.
Referenced by waitForConnectResult().
const byte WiFiManager::DNS_PORT = 53 [private]
Definition at line 173 of file WiFiManagerReadFileButton.h.
Referenced by setupConfigPortal().
boolean WiFiManager::connect [private]
Definition at line 180 of file WiFiManagerReadFileButton.h.
Referenced by handleWifiSave(), and startConfigPortal().
boolean WiFiManager::_debug = true [private]
Definition at line 181 of file WiFiManagerReadFileButton.h.
Referenced by DEBUG_WM(), and setDebugOutput().
void(* WiFiManager::_apcallback) (WiFiManager *) = NULL [private]
Definition at line 183 of file WiFiManagerReadFileButton.h.
Referenced by setAPCallback(), and startConfigPortal().
void(* WiFiManager::_savecallback) (void) = NULL [private]
Definition at line 184 of file WiFiManagerReadFileButton.h.
Referenced by setSaveConfigCallback(), and startConfigPortal().
WiFiManagerParameter* WiFiManager::_params[WIFI_MANAGER_MAX_PARAMS] [private]
Definition at line 186 of file WiFiManagerReadFileButton.h.
Referenced by addParameter(), handleWifi(), and handleWifiSave().
Author
Generated automatically by Doxygen for CoolBoard API from the source code.